huggingface/trl

- tests/test_modeling.py
- trl/models/modeling_vhead.py
- trl/ppo.py
This PR fixes a behaviour that we have encountered with #53 - for some reason the aforementioned PR lead to having models that does behave exactly similarly as the reference model, for the policy metrics, more precisely the `kl`, `policykl` `approxkl` were much more different than before. 
The issue seemed to be related to the initialization strategy of the VHead model. In #53 `_init_weights` method was introduced for consistency with `transformers` and to give users the possibility to tweak the initialization strategy of the VHead module. 
This PR fixes the behaviour precised above, by randomly initilazing the weights by default
cc @lvwerra
> [`VHead`] Fix slow convergence issue

- examples/scripts/ppo-sentiment-adam-8bit.py
- tests/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
This PR adds the support of generic optimizers. Before this PR, the `PPOTrainer` was only support adam optimizer. Users are now free to use any optimizer.
Added also an example that leverages `8bitAdam` which is lighter & faster than classic `Adam` optimizer. 
cc @lewtun @lvwerra @edbeeching 
as a side note, 8bitAdam should support DP out of the box
> [`PPOTrainer`] Support generic optimizers

- examples/notebooks/gpt2-sentiment-ppo-training.ipynb
The function "listify_batch" does not exist in "trl==0.0.3", and it will not be used later in this example
> Remove references to "listify_batch"

- examples/scripts/ppo-sentiment-adam-8bit.py
- examples/scripts/ppo-sentiment.py
Specify the `kwarg` for the `model` parameter. I was a bit weirded out by the two-parameter pipeline until I understood it came from `transformers` and you were specifying the model/tokenizer.
Very much a nitpick, feel free to disregard if you disagree!
> Model as kwarg in pipeline

- docs/source/_toctree.yml
- docs/source/models.mdx
- docs/source/trainer.mdx
- examples/notebooks/gpt2-sentiment-ppo-training.ipynb
- trl/__init__.py
- trl/models/modeling_base.py
- trl/models/modeling_value_head.py
- trl/trainer/ppo_trainer.py
Add the following on the documentation
API
- Model classes (`AutoModelForCausalLMWithValueHead` & `PreTrainedModelWrapper`)
- Trainer (`PPOTrainer` & `PPOConfig`)
> [Doc] Improve docs

- docs/source/quickstart.mdx
- tests/test_modeling.py
- tests/test_ppo_trainer.py
- trl/models/modeling_base.py
- trl/models/modeling_value_head.py
This PR addresses saving `v_head` weights when calling `save_pretrained`. Before this PR if a user wanted to share intermediate-trained `v_head` weights it was not possible. The workaround that I have found needs to load the state dict twice, once by the `from_pretrained` method that is called by the `pretrained_model` attribute and once afterwards to manually load the `v_head`.
This PR introduces a new kwarg on the method `from_pretrained` termed as `resume_training` as I think this is quite an edge case.
Added also some tests
TODOs:
- test `push_to_hub`
cc @lvwerra @lewtun
> [core] Push `v_head` when using `AutoModelForCausalLMWithValueHead`

- examples/scripts/ppo-sentiment-adam-8bit.py
- examples/scripts/ppo-sentiment.py
- requirements.txt
- setup.py
- tests/test_ppo_trainer.py
- trl/core.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
This PR removes `wandb` dependency for `trl`
wandb run of this branch: https://wandb.ai/distill-bloom/trl/runs/360f7cdc?workspace=user- 
cc @lvwerra
> [core] remove `wandb` dependency

- .github/workflows/build_documentation.yml
- .github/workflows/build_pr_documentation.yml
Fixes an issue with cross-references in the docs because the repo root is `trl` instead of `src`. Internal Slack thread: https://huggingface.slack.com/archives/C04EX6W3QSY/p1674470759142759
> Fix docs hyperlinks

- tests/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
(please ignore the branch name)
This PR adds safety checkers on the positional arguments of `PPOTrainer` making the API clearer for users if they pass unvalid arguments when initializing the trainer. This PR adds also nice tests
cc @lvwerra
> [core] improve API

- setup.py
We use `datasets` in the `PPOTrainer` so we should add it as a core dependency.
> add `datasets` as a dependancy

- docs/source/sentiment_tuning.mdx
This PR adds hlinks to the corresponding scripts & notebooks in the docs
@lvwerra @mishig25
> [Docs] Add hlinks to scripts & notebooks

- examples/sentiment/scripts/gpt2-sentiment.py
- examples/sentiment/scripts/t5-sentiment.py
- setup.py
- trl/core.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
@lvwerra or @younesbelkada is there any case where a model will be initialized randomly? If so, we need to make sure the seeds are set too.
Also, I ran make style and it modified those two lines of setup, so we can change them here or elsewhere.
> add manual seeding for RL experiments

- examples/sentiment/scripts/gpt2-sentiment.py
- examples/sentiment/scripts/t5-sentiment.py
- tests/trainer/test_ppo_trainer.py
- trl/__init__.py
This adds `set_seed` to the main `__init__.py` so we can `from trl import set_seed`. I think we should move important stuff the users is supposed to use there so they don't have to remember paths. Wdyt @younesbelkada? 
cc @natolambert
> add `set_seed` to __init__.py

- examples/sentiment/notebooks/gpt2-sentiment-control.ipynb
This is an attempt to fix the instabilities in the controlled sentiment generation.
Changes so far:
- fix logit computation for reward (pipeline changes order natively which can cause the position of the logit to switch)
- In generate kwargs add `"eos_token_id": -1`
The last point makes sure that the model keeps generating until the max new tokens is reached. I think what happens otherwise is that sometimes the model only generates 1-2 tokens in which case the PPO loss spikes (don't know why, yet). 
The last successful run is [here](https://wandb.ai/lvwerra/trl/runs/jpcnr7jx?workspace=user-lvwerra).
> Fix Sentiment control notebook

- trl/core.py
- trl/models/modeling_base.py
- trl/models/modeling_value_head.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
> Change unclear variables & fix typos

- examples/sentiment/scripts/gpt2-sentiment.py
- tests/trainer/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
Let's address #133 step by step
This PR just refactors the`train_mini_batch` function, so that the loss function does not have to compute the logits internally - which makes the latest easier to test
Logs:
- gpt2-sentiment: https://wandb.ai/distill-bloom/trl/runs/j2v024qq?workspace=user-younesbelkada
- t5-sentiment: https://wandb.ai/distill-bloom/trl/runs/ncbwpxfx?workspace=user-younesbelkada
> [`core`] Small refactor of forward pass

- examples/sentiment/scripts/t5-sentiment.py
- setup.py
- tests/trainer/test_ppo_trainer.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
This PR fixes issues with forward batching of models that pad to the right (e.g. `bloom`) and seq2seq models (e.g. `T5`).
> fix forward batching for seq2seq and right padding models.

- trl/core.py
- trl/models/modeling_value_head.py
- trl/trainer/ppo_trainer.py
Currently on the `main` branch of `trl` training in `bfloat16` & logging with `wandb` fails. Users will encounter an error that are hard to interpret.
The fixes are the following:
- remove `wandb.watch(model)` as it takes care of logging gradients that are in bf16, otherwise users will get an error that is similar to https://github.com/wandb/wandb/issues/3332 | I propose to remove this is not a core feature and is a main blocking point
- upcast the tensors in fp32 before logging them
- force-upcast the `lm_logits` in fp32 
cc @lvwerra
> [`core`] enable `bf16` training

- trl/trainer/ppo_trainer.py
Currently on the `main` branch of `trl` saving a `PPOTrainer` in a multi-GPU setting is broken. The fix is to first call `self.accelerator.unwrap_model(self.model)` before calling `save_pretrained`
cc @lvwerra
> [`core`] fix saving multi-gpu

- trl/trainer/ppo_trainer.py
I believe the kl we want to record is KL[policy_old || policy_new] 
Perhaps @natolambert can confirm?
> policy kl [old | new]

- tests/test_ppo_trainer.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
This PR adds the support of clipping gradients norm, that was not supported before but implemented in other frameworks such as clean RL: https://github.com/vwxyzjn/cleanrl/blob/2e41da2a3649c50f27121d74896110fe8f69dd52/cleanrl/ppo.py#L286 
This PR also adds a nice test
I can confirm multi-GPU training works with this PR (ran 1 PPO step of `gpt2-sentiment` with 2 GPU)
cc @edbeeching @lvwerra @natolambert
> [`core`] Add `max_grad_norm` support

- .github/workflows/tests.yml
- docs/source/sentiment_tuning_peft.mdx
- setup.py
As `peft` did a new release, this PR adds a new extra dependency for `tests` and creates `trl[peft]`
cc @lvwerra
> [`core`] Update dependency

- examples/toxicity/scripts/gpt-j-6b-toxicity.py
- trl/trainer/ppo_trainer.py
Two changes:
1. Pass the optimizer in the sentiment example (currently variable was not passed into trainier).
2. [I think] fix the kwarg option for wandb config of `Accelerate`. See this [docs page](https://docs.wandb.ai/guides/integrations/accelerate), where `init_kwargs` is handled differently. In trying to use this with the code as is, `wandb` is getting read as a `kwarg` and not handled correctly by [this line](https://github.com/lvwerra/trl/blob/b75d83ab28b59307916beb425207d46406502f11/trl/trainer/ppo_trainer.py#L180). If this is different in Tensorboard, it may just be incompatible.
Let me know if I'm wrong!
Fixes: #215
> Small changes when integrating into H4

- docs/source/customization.mdx
- docs/source/sentiment_tuning_peft.mdx
- examples/sentiment/scripts/gpt-neo-1b-multi-gpu/gpt-neo-1b_peft.py
- tests/test_ppo_trainer.py
- tests/testing_utils.py
- trl/core.py
- trl/models/modeling_base.py
- trl/models/modeling_value_head.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
Trying to load a model in a single device is cool, but what if we can split the model across multiple devices? 
Users will just have to pass a custom `device_map` when loading the model, and it should work out of the box.
This PR adds the support of "Sequential Parallel" - termed as naive Pipeline Parallelism as the real Pipeline parallelism involves dealing with multi-processing and gradients synchronisation that cannot be handled easily.
This PR depends on the following PRs:
- `accelerate`: https://github.com/huggingface/accelerate/pull/1172
- `peft`: https://github.com/huggingface/peft/pull/145
TODOs:
- users should NOT apply DP and/or DeepSpeed with this approach as it remains untested
- should we introduce multi-gpu tests that we optionally run?
- test with 8bit models
- update docs …
> Let's support naive Pipeline Parallelism

- tests/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
The mini batching PR introduced a small bug that led to DP crash using `accelerate` as we tried to all reduce tensors that did not had the same shape. 
The tensors that did not had the same shape were the logprobs tensors, that derive from the inputs. 
The fix is to add a check, that padds correctly the model inputs, and corresponding attention masks, and fills them with the correct value using `accelerator.pad_across_processes`
cc @lvwerra 
run for gpt2 sentiment with DP=2: https://wandb.ai/distill-bloom/trl/runs/p7pzc7yk?workspace=user-younesbelkada
run for t5 sentiment with DP=2: https://wandb.ai/distill-bloom/trl/runs/nb9as16x?workspace=user-younesbelkada
> [`core`] fix DP issue

- examples/sentiment/scripts/gpt-neox-20b_peft/gpt-neo-20b_sentiment_peft.py
- examples/sentiment/scripts/gpt2-sentiment.py
- examples/sentiment/scripts/gpt2-sentiment_peft.py
- examples/sentiment/scripts/t5-sentiment.py
- examples/toxicity/scripts/gpt-j-6b-toxicity.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
- Adds command line arg passing to sentiment and toxicity examples
- Adds gradient accumulation as a command line arg #218 
- Fixes tensors not being detached from graph when stored in stats, leading to an overuse of memory.
- Updates forward_batch_size -> minibatch size in a number of examples
By the way, I think there may be other places we use excessive memory due to storing attached tensors for too long. I will investigate further.
> Grad accumulation and memory bugfix

- docs/source/sentiment_tuning_peft.mdx
- examples/sentiment/scripts/gpt2-sentiment_peft.py
- trl/trainer/ppo_trainer.py
This PR fixes issues related to DP with `peft`
Adds also instructions on how to properly run DP + `peft`
cc @lvwerra
> [`peft`] Fix DP issues

- tests/test_ppo_trainer.py
- trl/import_utils.py
- trl/trainer/ppo_trainer.py
This PR fixes the failing tests related to Pytorch 2.0 upgrade
In Pytorch 2.0, the learning rate schedulers have been re-designed, thus we need a bit of refactoring on `trl` to deal with unexpected behaviors.
In Pytorch 2.0 it seems that the class `_LRScheduler` have been deprecated in favor of `LRScheduler`
```python
class _LRScheduler(LRScheduler):
pass
```
```python
class LambdaLR(_LRScheduler):
"""Sets the learning rate of each parameter group to the initial lr
times a given function. When last_epoch=-1, sets initial lr as lr.
Args:"""
```
Hence the check `isinstance(lr_scheduler, torch.optim.lr_scheduler._LRScheduler)` does not pass anymore with Pytorch >=2.0
> [`test`] attempt to fix CI test for PT 2.0

- docs/source/sentiment_tuning_peft.mdx
- examples/sentiment/scripts/gpt-neo-1b-multi-gpu/gpt-neo-1b_peft.py
- examples/sentiment/scripts/gpt2-sentiment_peft.py
- tests/test_peft_models.py
- tests/testing_utils.py
- trl/models/modeling_base.py
- trl/models/modeling_value_head.py
This PR slightly refactors the way we use / load peft models
For now I think it is important to let users pass the `PeftConfig` to `from_pretrained` , as it is an essential component for create peft models
I also think that we should be able to pass `prepare_int8_training` kwargs directly to `from_pretrained` as well, since sometimes you need some tweaks to enable int8 training
This PR is also fully backward compatible with the previous API
cc @lvwerra
> [`core`] refactor peft API

- trl/trainer/ppo_trainer.py
This PR reduces memory consumption in `batched_forward_pass` of PPOTrainer, by avoiding the storage of logits when they are not necessary.
Before this PR, `batched_forward_pass` stored all of the model's `logits` all the time like other tensors such as `values` and `logprobs`. Here, `logits` tensors have a much larger size (batch_size * tokens * **vocabulary_size**) compared to `logprobs` and `values` tensors (batch_size × tokens), consuming a significant amount of cuda memory.
I have modified `batched_forward_pass` to avoid unnecessary storage of `logits`, which is only required when calculating entropy in the `loss` method.
> Reduce memory consumption in batched_forward_pass

- trl/trainer/ppo_trainer.py
Fixes: #235 
The warning message will be displayed only once, if there is a repetition, as described in the official documentation of `warnings` package: https://docs.python.org/2/library/warnings.html / https://stackoverflow.com/questions/22661745/why-only-one-warning-in-a-loop
cc @lvwerra
> [`core`] Add warning when negative KL

- examples/sentiment/scripts/gpt2-sentiment.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
Adds early stopping to the PPO loop. Fixes #232 
I used a value of 0.1 as the threshold as I observed an initial spike of 0.2 before we had instabilities in gpt2-xl earlier this week:
Note that RL4LM [use a value of 0.5 ](https://github.com/allenai/RL4LMs/blob/main/scripts/training/task_configs/dialog/gpt2_ppo.yml)
My only other concern is gradient accumulation. I think it would it be better to zero the gradients as soon as we see a splike in KL, or to leave them in the as is. I have zeroed them for now, but it would be great to have feedback on this.
> adds early stopping

- trl/trainer/ppo_config.py
Fixes: https://github.com/lvwerra/trl/issues/233
Moving `total_ppo_epochs`, `forward_batch_size` and `log_with` to post init method and let the dataclass automatically assign the other member variables.
cc @edbeeching @lvwerra
> PPO config __init__ is bloated 

- .github/workflows/clear_cache.yml
- .github/workflows/tests.yml
This PR sets the `cache` and `cache-dependency-path` argument of `actions/setup-python` to enable pip caching.
> feat(ci): enable `pip` cache

- docs/source/_toctree.yml
- docs/source/logging.mdx
- trl/trainer/ppo_trainer.py
I wanted to make it clearer in experiments the difference between the reward model score and the KL penalty. Added PR to do that :).
> Improve logging for PPO + Docs page

- trl/trainer/ppo_trainer.py
This PR fixes an issue where the training was hanging in multi-GPU setting and using earyl stopping
In fact, in a multi-GPU setting, we need to compute the average of `policykl` across all GPUs, and call early stopping
I can confirm this solution worked, the way I checked was to add a print after the `self.optimizer_zero_grad` and forcing the coefficient to be `0` :
`if policykl > 0 * self.config.target_kl:`
cc @edbeeching @lvwerra 
```bash
4it [00:03,  1.36it/s]early stopping successfulearly stopping successful
5it [00:04,  1.21it/s]early stopping successful
```
> [`distributed`] Fix early stopping and DP

- tests/test_modeling_value_head.py
- trl/models/modeling_base.py
Fixes https://github.com/lvwerra/trl/issues/258
Before this PR, Llama was not supported by `create_reference_model`, hence users needed to manually define the pattern of the layers to properly create a reference model, and this can be error prone.
This PR simply adds the Llama layer pattern for `create_reference_model`, I also added a tiny Llama model for testing purpose
cc @lvwerra
> Add LlaMa in tests + `create_reference_model`

- docs/source/_toctree.yml
- docs/source/customization.mdx
- docs/source/lora_tuning_peft.mdx
- docs/source/using_llama_models.mdx
Added a shortened version of the blog post, added the scripts to the `peft` docs page, some typo fixes.
> Add LLaMA tutorial to docs

- tests/test_ppo_trainer.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
[issue-255](https://github.com/lvwerra/trl/issues/255)
> add functionality to push best models to the hub during training

- examples/toxicity/scripts/gpt-j-6b-toxicity.py
- trl/trainer/ppo_config.py
Changed defaults to match the run that is in the docs, fixed some config entries.
> Small improvements / fixes to toxicity example

- examples/sentiment/scripts/t5-sentiment.py
- trl/trainer/ppo_trainer.py
Fixes #256 
This PR fixes issues related with negative KL and T5 sentiment example. The first fix was related to the sentiment script that was incorrectly ported.
Before this PR, the padding side of tokenizers was always hardcoded to `left` in `_batched_generate`. in encoder-decoder models, they should be set to their native `padding_side` (i.e. `right` for T5), as the padding is performed on the encoder tokens, and these models have been trained with this specific padding side. I think that the culprit is the way the positional attention bias is computed, that does not take into account the starting position if `padding_side=left`: https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L436-L451 
Thus forcing padding_side=left for encoder-decoder …
> [`t5`] Fix negative kl issue

- examples/README.md
- examples/sentiment/README.md
- examples/summarization/README.md
- examples/toxicity/README.md
The top level readme was all about sentiment classification, so I made a general one and moved the respective readme's to subfolders.
Open to feedback.
> clean examples folder

- trl/trainer/ppo_trainer.py
`self.ref_model` can be None. peft ref_model is got by calling `disable_adapter` method, e.g. ,
```
with self.accelerator.unwrap_model(self.model).pretrained_model.disable_adapter():
ref_logprobs, _, _, _ = self.batched_forward_pass(self.model, queries, responses, model_inputs)
```
> fix DS for peft ref_model in ppo trainer

- tests/test_ppo_trainer.py
With the next release of `huggingface_hub`, the `set_access_token` method has been deprecated, see: https://github.com/huggingface/huggingface_hub/pull/1381
According to https://github.com/huggingface/transformers/pull/22051 - that function was used for code-legacy purposes and one shouldn't use `set_access_token` at the first place according to that PR. Therefore I propose to remove that line to unlock the failing CIs
cc @lvwerra
> [`CI`] Fix broken tests

- examples/sentiment/notebooks/gpt2-sentiment-control.ipynb
- trl/trainer/ppo_trainer.py
There is a lot of stuff with very generic keys in the `PPOConfig` dict, and the user may have logged a `wandb` config dict elsewhere. I know I had that problem. To counter that, I pass the PPOConfig dict in a dict under the key `trl_ppo_trainer_config`, to prevent collisions & be very clear.
> Give a key to the wandb PPOConfig config entry

- docs/source/customization.mdx
Following up on https://github.com/lvwerra/trl/issues/317, I created this PR.
> added doc for using torch.distributed.launch/run

- examples/stack_llama/scripts/README.md
- examples/stack_llama/scripts/merge_peft_adapter.py
* The parameter names for `merge_peft_adapetr.py` are out of date in the README
* LlamaModelForCausalLM does not have an attribute `_get_submodules`
> stack_llama: update instructions in README, fix broken _get_submodules and save tokenizer

- examples/stack_llama/scripts/reward_modeling.py
As I "only" have 24 Gb VRAM, I run out of memory when training the reward model. The dataset was previously truancated to a hardcoded value of 512; I have made this a script argument.
> stack_llama: add parameter to control max_length (to mitigate OOM errors)

- tests/test_peft_models.py
- trl/models/modeling_base.py
Fix the bug in https://github.com/lvwerra/trl/issues/341.
When the local model weight and the lora weight are saved in different locations, the code will try `hf_hub_download` and throw `HFValidationError: Repo id must be in the form 'repo_name'` error twice. In the first time, the error was caught. But the second error will terminate the code.
After loading the local peft model, we can update `pretrained_model_name_or_path` to `pretrained_model` to avoid entering the resume_training branch.
> Fix bug when loading local peft model

- tests/test_peft_models.py
- trl/models/modeling_base.py
This PR enables continue training of peft model by add `is_trainable` as a `kwarg` on `from_pretained` of `PreTrainedWrapper`. (ref. https://github.com/lvwerra/trl/pull/342#discussion_r1191286149)
`is_trainable` is a parameter of `PeftModel.from_pretrained()` which enable continue training. `LoraConfig` do not have `is_trainable` parameter. 
Use case example: https://github.com/huggingface/peft/issues/282#issuecomment-1500804381
Source: https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py#L145
cc @lvwerra @younesbelkada
> add is_trainable in kwargs

- examples/sentiment/scripts/gpt-neox-20b_peft/clm_finetune_peft_imdb.py
- examples/sentiment/scripts/gpt2-sentiment_peft.py
- examples/stack_llama/scripts/rl_training.py
- requirements.txt
The recent changes in `peft` break some of the scripts. E.g., `rl_training` passes the obsolete parameter `layer_norm_names` to the `pretrained_model` call as it detects that it is not consumed by `prepare_model_for_int8_training`, causing an error. Fix: remove all references to `layer_norm_names` and add `peft>=0.3.0` to `requirements.txt`.
> Remove obsolete layer_norm_names parameter and add peft>=0.3.0 to requirements

- docs/source/sft_trainer.mdx
- trl/trainer/sft_trainer.py
This PR fixes https://github.com/lvwerra/trl/issues/362
It puts clearer documentation regarding the usage of `SFTTrainer`
cc @lvwerra
> [`docs`] fix SFT doc

- trl/trainer/ppo_trainer.py
`dataloader must be a torch.utils.data.Dataset`: `dataloader` should be `dataset`
> fix dataloader typo in ppo_trainer.py

- trl/models/modeling_base.py
I also added a warning in case an adapter is found but a peft_config is also given. And I tried to simplify a bit since the same processing is done in PeftConfig.from_pretrained.
is_peft_available() is indirectly checked. If it is not installed, it will trigger an exception and trained_adapter_config will be set to None.
Let me know what you think. If you don't think this is an improvement, I can revert, no problem.
> from_pretrain with peft adapter on the hub (# 379)

- trl/models/modeling_base.py
This PR fixes the following issue: when `save_pretrained(...)` was called for `AutoModelForCausalLMWithValueHead` with an explicitly given `state_dict`, this `state_dict` was deleted from `kwargs` and not passed further. I believe the intended behavior was to keep `state_dict` in `kwargs` if it's already in there.
> keep state_dict kwargs instead of popping it in save_pretrained

- examples/stack_llama/scripts/merge_peft_adapter.py
fixes #368 #386 #297 and partially #327
correctly merge weights with peft's `merge_and_unload`
if merging a reward model, load `sequence classification`
Note that `trl-lib/llama-7b-se-rm-peft` does not contain the `score` weight so I will release my own pretrained reward model adapter weights
> StackLLaMA: correctly merge peft model

- examples/stack_llama/scripts/rl_training.py
added steps argument and break to respect max training epochs added more PPOConfig args to script args
removed llama tokenizer hacks
black + isort
~switched to `LlamaTokenizer` from `AutoTokenizer`~  added `return_token_type_ids=False` to pipeline kwargs because
- the latter loads `LlamaTokenizerFast`
- `LlamaTokenizerFast` will output `token_type_ids` see https://github.com/huggingface/transformers/issues/23818 and https://github.com/huggingface/transformers/pull/23909
-  these `token_type_ids` cause an error in our reward model `pipeline`, namely `TypeError: LlamaForSequenceClassification.forward() got an unexpected keyword argument 'token_type_ids'`
> StackLlama: fixed RL training and added args

- examples/sentiment/notebooks/gpt2-sentiment-control.ipynb
- trl/trainer/ppo_trainer.py
- Ref model should be Optional
- The usual annotation for the Huggingface tokenizers is PreTrainedTokenizerBase. Not using that messes up people's annotation checks.
- Fixed the comments wrt the other two points
> Fixed some type annotations of trl.trainer.PPoTrainer

- examples/stack_llama/scripts/reward_modeling.py
- examples/stack_llama/scripts/supervised_finetuning.py
for supervised finetuning
- removed tokenizer hacks since they are no longer necessary with the updated `llamatokenizer`
- black + isort
for reward modeling
- added `tokenizer_name` so it can be separately specified from model
- again removed old llama tokenizer hacks
- added `eval_first_step` option to add an eval loop after the first step to make nicer graphs
- black + isort
> StackLLaMA: fix supervised finetuning and reward model training

- docs/source/quickstart.mdx
- examples/hello_world.py
- tests/test_e2e.py
Minor minor improvement on docs :)
> Remove unused imports in docs.

- trl/trainer/ppo_config.py
This PR automatically tags the wandb experiments with the git tags and PR number if possible. 
The tag will be helpful later on for RLops for which we compare the performance of some sanity check tasks between different. versions of the library.
> Enable autotag feature w/ wandb

- trl/trainer/ppo_trainer.py
Fixes https://github.com/lvwerra/trl/issues/409
Properly not call `whoami()` method that requires internet connection and raise a proper warning if that's the case.
> handle the offline case

- .github/workflows/tests.yml
Currently the CI fails (probably) because of the latest datasets release 
The culprit seems to be the Python version, I propose to remove the support for Python 3.7 as it will be depracted anyway in few days.
Related failing PR: https://github.com/lvwerra/trl/pull/437
> Drop support for Python 3.7

- trl/trainer/sft_trainer.py
Fixes https://github.com/lvwerra/trl/issues/434
Fixes a small nit, when a user already passes a `ConstantLengthDataset`, the SFTTrainer should accept it out of the box, assuming users know what they did
> [`SFTTrainer`] Relax dataset constraints

- docs/source/sft_trainer.mdx
- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
This PR properly educates users on how to correctly use `formatting_func` method when someone uses a non-packed dataset. 
Since the dataset processing calls `dataset.map(xxx, batched=True)` under the hood, it is important to return an array of processed texts to properly process all texts from the dataset example batch, otherwise it will lead to silent bugs that are hard to understand such as the one described in https://github.com/lvwerra/trl/issues/439
```python
from trl import SFTTrainer
import transformers
dataset = load_dataset("tatsu-lab/alpaca", split="train")
model = transformers.AutoModelForCausalLM.from_pretrained("facebook/opt-350m")
tokenizer = transformers.AutoTokenizer.from_pretrained("facebook/opt-350m")
def …
```
> [`SFTTrainer`] Fix non packed dataset

- docs/source/sft_trainer.mdx
- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
Fixes https://github.com/lvwerra/trl/issues/450 
As reported in that issue, there is an inconsistent behaviour when using `packing=True` and the number of iterations showed in the logs of training. In fact, the inconsistency comes from the fact that in the packed case, sequences are packed all together on the fly until `max_seq_length` is reached, leading to reducing the number of total expected samples.
The fix is to force-set the `infinite` argument to `True` if a user explicity decides to train a model with `max_steps` strategy but properly warn them that the argument has been overriden and warn the user when the dataset is moved to the next iteration.
In the case of epochs training strategy, we should force-set infinite argument to False, otherwise the training will run forever.
Added …
> [`ConstantLengthDataset`] Fix packed dataset issue

- trl/trainer/ppo_config.py
This PR fixes an issue users can encounter when initializing a PPOConfig on a google colab instance
If the autotag function fails, it returns an empty string, therefore `os.environ['WANDB_TAGS']` gets never populated leading to a keyerror in the logging process. 
This PR fixes it by adding the correct indentation
cc @lvwerra @vwxyzjn
> Fix google colab issue

- trl/trainer/utils.py
Added parameter that allows you to turn off shuffling.
> Make shuffle optional

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- scripts/stale.py
- setup.cfg
- setup.py
You can reproduce the existing pipeline with `pre-commit run --all-files` (note that pre-commit however only applies to git's staged and already committed files). I didn't fix the typo pointed out by `codespell` because it might create too many merge conflicts with existing PRs.
> Pre-commit

- trl/trainer/sft_trainer.py
There are two issues with the previous `_prepare_dataset` function.
1. Tortuous and burdensome logic: the `is_already_dataset` variable is confusing and not helpful. So, remove it.
2. The comments and the logics do not match. 
For instance, in the previous version, the comments said "check if torch dataset ... and do nothing". However, when "dataset" is a torch.utils.data.Dataset and `packing = True`? It will still move into the _prepare_non_packed_dataloader(...) function call. 
The corrected version will do nothing if the dataset is already a torch dataloader/dataset/ConstantLengthDataset.
> Debug the tortuous logic in `_prepare_dataset` function

- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
Investigating issue #101 further we found that they are usually caused by abnormally high ratios in the PPO loss. This adds a threshold to skip those batches. See below for a seed that had a spike before and after the fix:
> add ratio threshold to avoid spikes

- examples/stack_llama/scripts/reward_modeling.py
Fix `weight_decay` Field Type
Changed the type of `weight_decay` from `Optional[int]` to `Optional[float]`.
> fix typo in reward_modeling.py

- CONTRIBUTING.md
The contributing guideline mentions `make commit` but this should be `make precommit` as per the Makefile.
> FIX: contributing guidelines command

- examples/sentiment/scripts/gpt2-sentiment.py
- trl/trainer/ppo_trainer.py
Remove padding in batched generation as a post-processing step.
> Remove padding in batched generation.

- examples/sentiment/scripts/gpt2-sentiment.py
- tests/test_ppo_trainer.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
This PR adds some options to stabilize the KL penalty, abs and MSE of KL estimates as detailed [here](http://joschu.net/blog/kl-approx.html).
This PR has a similar motivation of [PR#423](https://github.com/lvwerra/trl/pull/423) but here we focus on the KL penalty calculation between the base model and policy, whereas the other PR is the KL between the policy used for generation and the latest version of the policy after k PPO steps.
I have launched the gpt-sentiment example in three configurations:
- [default](https://wandb.ai/edbeeching/trl/runs/86cnr8py?workspace=user-edbeeching)
- [abs kl](https://wandb.ai/edbeeching/trl/runs/zaejlw0r?workspace=user-edbeeching)
- [mse kl](https://wandb.ai/edbeeching/trl/runs/ptykchil?workspace=user-edbeeching)
**Convergence over 10 seeds - default:** …
> Adds some options to stabilize the KL penalty

- trl/trainer/utils.py
As discussed [here](https://github.com/lvwerra/trl/pull/445#issuecomment-1601544929), `DataCollatorForCompletionOnlyLM ` inherits from the MLM data collator but that means that `mlm` is set to True by default. In reality that does not matter (because the appropriate methods are overridden) but it can still be confusing for the user. So now `mlm` is explicitly set to False (with the option to be changed by the user).
The user now also has the option to decide which index to use to ignore `ignore_index`.
A docstring is added for DataCollatorForCompletionOnlyLM, which was missing. I urge future PRs to always include good documentation and docstrings, otherwise the overview gets lost quickly.
> Disable mlm by default in DataCollatorForCompletionOnlyLM, add ignore_index and docstring

- trl/trainer/ppo_trainer.py
Addresses: https://github.com/lvwerra/trl/issues/440#issuecomment-1623160589 
We should use `float` instead of `double` to avoid issues with MPS device
cc @lvwerra
> Use `float` instead of `double` to avoid issues with MPS device

- trl/models/modeling_value_head.py
Fixes https://github.com/lvwerra/trl/issues/470
This PR correctly deals with prefix tuning when using PEFT + TRL, to reproduce:
```python
import peft
from peft import PrefixTuningConfig, TaskType, get_peft_model
import torch
from tqdm import tqdm
from transformers import AutoTokenizer, HfArgumentParser, pipeline, AutoModelForSeq2SeqLM
from trl import AutoModelForSeq2SeqLMWithValueHead, PPOConfig, PPOTrainer, set_seed
from trl.core import LengthSampler
tqdm.pandas()
config = PPOConfig(
model_name='t5-base',  
batch_size=16,
mini_batch_size=4,
)
sent_kwargs = {"return_all_scores": True, "function_to_apply": "none", "batch_size": 16}
def build_imdb_dataset(tokenizer, input_min_text_length=2, input_max_text_length=8):
ds = load_dataset("imdb", split="train") …
```
> [`PPOTrainer`] Add prefix tuning support

- docs/source/lora_tuning_peft.mdx
- tests/test_ppo_trainer.py
- trl/models/modeling_base.py
- trl/trainer/ppo_trainer.py
Fixes https://github.com/lvwerra/trl/issues/490 
Prompt tunning appends new tokens in the beginning of the generated sentence and make the new vocabulary that is used to generate these tokens trainable. 
Before this PR that PEFT method was not supported out of the box. I propose a v1 to integrate prompt tuning into TRL.
Might be also related to https://github.com/lvwerra/trl/issues/470 
Added also a nice test that fails on main and does not fail on this branch
In my opinion we should zero-out the logits that corresponds to these new tokens as it is not possible to compute reference logits on these tokens, however we shouldn't mask out these tokens in the PPO step
cc @lvwerra
> [`PPOTrainer`] Add prompt tuning support on TRL

- trl/trainer/sft_trainer.py
Fixes https://github.com/lvwerra/trl/issues/467
Replaces https://github.com/lvwerra/trl/pull/481
The original code lead to having examples that were filtered out by the previous check. This ultimately lead to having examples being ignored when processing the data. Probably a copy-pasta from: https://huggingface.co/learn/nlp-course/chapter7/6?fw=pt where I borrowed the original code
The fix is to remove completely that check
cc @lvwerra
> [`SFTTrainer`] Fix the sequence length check of `SFTTrainer`

- trl/trainer/reward_trainer.py
Fixes #451 - "Tensors must be CUDA and dense" bug
This puts the label tensors onto the correct device when evaling with deepspeed.
> Reward trainer multi-gpu eval bug

- trl/models/modeling_base.py
This PR fixes a bug in `_get_current_device()` where the global process index was being returned instead of the local one. 
With this fix, it is possible to run training in **multi-node** environments and avoid the dreaded `RuntimeError: CUDA error: invalid device ordinal` :)
> Use local process index for `_get_current_device()`

- examples/scripts/sft_trainer.py
This is for huggingface models that require using an access token to download (like meta's llama2). Tested by running the following command:
```bash
> huggingface-cli login
> python trl/examples/scripts/sft_trainer.py \
--model_name meta-llama/Llama-2-7b-hf \
--dataset_name timdettmers/openassistant-guanaco \
--load_in_4bit \
--use_peft \
--batch_size 4 \
--gradient_accumulation_steps 2 \
--use_auth_token
```
> Add `use_auth_token` arg to sft_trainer example

- trl/trainer/sft_trainer.py
This tiny PR adds the optional argument `num_proc` to the SFTTrainer so that the mapped tokenization can occur in parallel if the user wishes that.
> ADD: num_proc to SFTTrainer

- examples/scripts/sft_trainer.py
- trl/trainer/sft_trainer.py
While debugging why some users got 0 loss when fine-tuning Llama-2 on Guanaco, it seems the issue was caused by padding tokens being appended on the left. 
The fix for that model seems to be to force `tokenizer.padding_side = "right"` to successfully fine-tune Llama-2. Therefore we advise users to do that for their training. 
Related: https://gist.github.com/younesbelkada/9f7f75c94bdc1981c8ca5cc937d4a4da?permalink_comment_id=4636728#gistcomment-4636728
cc @lvwerra
> [`SFTTrainer`] Add warning for wrong padding_side

- docs/source/lora_tuning_peft.mdx
- examples/scripts/sft_trainer.py
Just some small things I noticed while reading the docs and examples
> Minor typo and whitespace fixes

- docs/source/sft_trainer.mdx
As per title and as discussed offline, this PR adds a section on the docs about how to FT a model using SFTTrainer on completions only.
cc @lvwerra
> Add `DataCollatorForCompletionOnlyLM` in the docs

- examples/scripts/reward_trainer.py
Fixes #558
In `examples/scripts/reward_trainer.py`,
- set `num_labels=1` when loading the pre-trained model, so that the reward model produces a scalar output.
- add validation dataset
- correct a logging glitch
> Fix model output dim in reward trainer example

- examples/scripts/sentiment_tuning.py
- tests/test_ppo_trainer.py
- trl/core.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
I got so fed up with negative KL that I have added an option to calculate the KL for the entire distribution. 
It is memory intensive for large sequences with an allocation of `8*vocab_size` per token, but it should stabilize training and cannot be negative! Memory usage could be greatly reduced but would require a larger refactor.
Single seed runs for gpt2-sentiment:
> Computes the KL penalty using the entire distribution

- examples/scripts/sft_trainer.py
I believe this was supposed to be here already, as the `--seq_length` argument doesn't currently seem to be getting used, and there is no other way I can see to set max_seq_length.
I may be mistaken though, I'm not familiar with the code yet.
> Add missing max_seq_length arg to example sft_trainer.py

- trl/trainer/ppo_trainer.py
Fixes: https://github.com/lvwerra/trl/issues/553
When users uses different combinations of batch size and forward batch size it might lead to breaking behaviours as explained on the attached issue.
This PR fixes it by adding the suggestion proposed by one of the user which is perfectly backward compatible
cc @lvwerra
> [`PPO`] fix corner cases with PPO batch size and forward_batch_size

- tests/test_sft_trainer.py
- trl/trainer/utils.py
Fixes https://github.com/lvwerra/trl/issues/588
This PR fixes issue https://github.com/lvwerra/trl/issues/588 encountered in the DataCollatorForCompletionOnlyLM class. Originally, the class compared self.response_token_ids with examples[i]["input_ids"], which caused a RuntimeError under certain circumstances.
This PR changes the comparison target to batch["labels"][i] from examples[i]["input_ids"] and add unit tests.
The added unit test reproduces the bug reported in the issue. Additionally, I have confirmed that the changes I made cause the added unit test to pass.
Please review and let me know if any changes are required.
> Fix comparison in DataCollatorForCompletionOnlyLM (#588)

- trl/models/modeling_base.py
Fixes https://github.com/lvwerra/trl/issues/602
As per title, let's add the `token` argument in the from_pretrained method to allow users to pass their HF tokens to download from private repos.
cc @lvwerra
> [`Modeling`] Add token support for `hf_hub_download`

- docs/source/logging.mdx
As the title says. There are also some naming issues:
* Inconsistent naming, `queries_dist` should be `tokens/queries_len_dist`, `responses_dist` should be `tokens/responses_len_dist`.
* We should remove `ppo/mean_scores` and `ppo/std_scores`. They are aliases it means?
* Inconsistent naming, some have `mean, var` but some do not. E.g., `objective/kl` could be `objective/kl_mean`, but this is ok.
* Inconsistent naming, some have `dist` some do not. `ppo/policy/ratio` should be `ppo/policy/ratio_dist`, `ppo/policy/advantages` should be `ppo/policy/advantages_dist`
* off naming, `objective/logprobs` is not an objective and should be `tokens/logprobs_dist` and `objective/ref_logprobs` should be `tokens/ref_logprobs_dist`
> Add docs explaining logged metrics

- examples/scripts/sft_trainer.py
It's in the script arguments, but not used
```
log_with: Optional[str] = field(default=None, metadata={"help": "use 'wandb' to log with wandb"})
```
> Use log_with argument in SFT example

- docs/source/sft_trainer.mdx
- tests/test_data_collator_completion_only.py
- trl/trainer/utils.py
This PR fixes issue described in https://github.com/lvwerra/trl/issues/598
Some tokenizers will tokenize the same string differently, depending on whether it has left context or not. An example of this is the tokenizer of `meta-llama/Llama-2-7b-hf`, that tokenizes the `response_template` differently in these cases:
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
def print_tokens_with_ids(txt):
tokens = tokenizer.tokenize(txt, add_special_tokens=False)
token_ids = tokenizer.encode(txt, add_special_tokens=False)
print(list(zip(tokens, token_ids)))
prompt = """### User: Hello\n\n### Assistant: Hi, how can I help you?"""
print_tokens_with_ids(prompt)  # [..., ('▁Hello', 15043), ('<0x0A>', 13), ('<0x0A>', 13), ('##', 2277), …
```
> Allow already tokenized sequences for `response_template` in `DataCollatorForCompletionOnlyLM`

- README.md
- docs/source/_toctree.yml
- docs/source/customization.mdx
- docs/source/how_to_train.md
- docs/source/index.mdx
- docs/source/use_model.md
The goal of this PR is to improve the overall docs:
- add links to blogs (maybe we could add thumbnails?)
- improve readme
- how to generate and which metrics to look for in PPO
- how to use a trained model for inference (#599)
> Improve docs

- docs/source/customization.mdx
- examples/scripts/multi_adapter_rl_v2.py
- examples/scripts/sentiment_tuning.py
- trl/models/modeling_base.py
- trl/trainer/__init__.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
- trl/trainer/utils.py
Add score (aka reward) scaling/normalization/clipping to improve PPO training stability based on Section 5.3.1 of [Secrets of RLHF in Large Language Models Part I: PPO](https://arxiv.org/pdf/2307.04964.pdf) and https://github.com/OpenLMLab/MOSS-RLHF:
The following is tested on a Google Colab notebook with an Nvidia T4 GPU.  My notebook gets disconnected by itself after a few hours while I was getting 1 iteration per minute, so my runs crashed fairly early.
```
python examples/scripts/sentiment_tuning.py --log_with wandb
```
Command for score scaling/normalization/clipping:
```
python examples/scripts/sentiment_tuning.py --log_with wandb --use_score_scaling --use_score_norm --score_clip 0.5
```
Command for baseline:
```
python examples/scripts/multi_adapter_rl_v2.py --model_name …
```
> Add score scaling/normalization/clipping

- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
PR for #624. The goal is to allow DPOTrainer to allow for `ref_model=None`. If the model to be trained is a `peft` model, or a `peft_config` is provided, we use the base model for improved memory consumption. Otherwise, a reference model is created on the fly by copying the `model`.
> Allow for ref_model=None in DPOTrainer

- examples/scripts/sft_trainer.py
The SFT example `sft_trainer.py` does not support all `HFArguments` available. This PR adds argparser flags for common `HFArguments`, so that the example is more usable.
This is a very simple feature change.
> Add more args to SFT example

- examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
The script missed copying `per_device_eval_batch_size` to `training_args`, which makes it use the default size of 8 for eval_batch_size instead of 1 as set in this script. This PR fixes the issue by copying the `per_device_eval_batch_size` from `script_args` to `training_args`.
fixes #671
> propagating eval_batch_size to TrainingArguments

- trl/trainer/reward_trainer.py
Currently the CI is failing on main due to the new release of transformers that included https://github.com/huggingface/transformers/pull/25435
Now `TrainingArguments` are unmutable, meaning to change a value in a `TrainingArguments` object one needs to create a copy of that object with the desired change
Fixes the failing CI in https://github.com/huggingface/trl/pull/649
cc @lvwerra
> [`CI`] Fix unmutable `TrainingArguments` issue

- examples/research_projects/tools/calculator.py
- examples/research_projects/tools/python_interpreter.py
- examples/research_projects/tools/triviaqa.py
- trl/trainer/ppo_trainer.py
Currently in the 0.7.0 version `ppo_trainer.log_stats` fails with the error
```bash
KeyError                                  Traceback (most recent call last)
<ipython-input-6-aac057b11b52> in <cell line: 138>()
155     #### Run PPO step
156     stats = ppo_trainer.step(query_tensors, response_tensors, rewards)
--> 157     ppo_trainer.log_stats(stats, batch, rewards)
/usr/local/lib/python3.10/dist-packages/trl/trainer/ppo_trainer.py in log_stats(self, stats, batch, rewards)
1297 
1298                 table_rows = [
-> 1299                     list(r) for r in zip(batch["query"], batch["response"], batch["answer"], rewards.cpu().tolist())
1300                 ]
1301                 logs.update(
KeyError: ‘answer’
```
Introduced in #424 the fix is to create a new parameters …
> [`PPOTrainer`] A workaround for failing log_stats

- docs/source/sft_trainer.mdx
Fixes https://github.com/huggingface/trl/issues/714
Fixes issues here and there regarding docs about SFTTrainer, in fact, the trainer does not support some args such as `torch_dtype`
cc @lvwerra @vwxyzjn
> [`Docs`] Fix sft mistakes

- trl/trainer/dpo_trainer.py
Fix #669
In ZeRO3, issues like #669 are caused by running `deepspeed.initialize` on only one of the two models passed to DPO_Trainer.
Most users use `.from_pretrained` to get the weight of the model, and inside from_pretrained is the code below.
```python
if is_deepspeed_zero3_enabled():
import deepspeed
logger.info("Detected DeepSpeed ZeRO-3: activating zero.init() for this model")
init_contexts = [deepspeed.zero.Init(config_dict_or_path=deepspeed_config())] + init_contexts
elif load_in_8bit or low_cpu_mem_usage:
init_contexts.append(init_empty_weights())
with ContextManagers(init_contexts):
model = cls(config, *model_args, **model_kwargs)
```
Models that don't use ZeRO3 don't matter, 
But most of the heavier models like LLM are run using ZeRO3, so `from_pretrained`, …
> Fix: RuntimeError: 'weight' must be 2-D issue

- docs/source/reward_trainer.mdx
- docs/source/trainer.mdx
- examples/scripts/reward_trainer.py
- tests/test_reward_trainer.py
- trl/__init__.py
- trl/trainer/__init__.py
- trl/trainer/reward_trainer.py
- trl/trainer/training_args.py
- trl/trainer/training_configs.py
This PR migrates the `max_length` arg of the `RewardTrainer` into a dedicated `RewardTrainingArguments` class that can also be used for storing future hyperparameters.
To be backwards compatible, I've left the variable in the trainer's init, with a warning that this will be removed in some future version.
Tested with:
```shell
accelerate launch --multi_gpu --num_processes 2 examples/scripts/reward_trainer.py --batch_size 1
```
> Refactor RewardTrainer hyperparameters into dedicated dataclass

- trl/trainer/sft_trainer.py
Fixes https://github.com/huggingface/trl/issues/667 
Fixes https://github.com/huggingface/trl/issues/735
if PEFT is not installed SFTTrainer will throw an error when checking `isinstance(model, (PreTrainedModel, PeftModel))` as `PeftModel` is defined nowhere in the script if PEFT is not available
cc @lvwerra
> [`SFTTrainer`] Check correctly for condition

- trl/trainer/ppo_trainer.py
- Add epsilon to score normalization for numerical stability;
- Call `Tensor.to` on running mean and std
Running
```commandline
python examples/scripts/sentiment_tuning.py --log_with wandb --use_score_scaling --use_score_norm --score_clip 0.5
```
> Add epsilon to score normalization

- docs/source/reward_trainer.mdx
- examples/scripts/reward_trainer.py
- examples/scripts/sentiment_tuning.py
- examples/scripts/sft_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/training_configs.py
Edit: to be merged after #726 
This PR allows users to disable gradient checkpointing for PEFT models in the `RewardTrainer`. The motivation for this is to bypass the `RuntimeError: Expected to mark a variable ready only once.` issue noted in https://github.com/huggingface/trl/issues/480 at the expense of using more vRAM. More generally, I think it's good when a library allows users to configure settings like these, since there are tradeoffs involved (i.e. computation time for memory).
With this change, it is now possible to train PEFT reward models in multi-GPU contexts as follows:
```shell
accelerate launch --multi_gpu --num_processes 4 examples/scripts/reward_trainer.py --use_peft --load_in_8bit --gradient_checkpointing false
```
When gradient checkpointing is activated the script …
> Enable gradient checkpointing to be disabled for reward modelling

- trl/models/modeling_sd_base.py
Fixes https://github.com/huggingface/autotrain-advanced/issues/259
With https://github.com/huggingface/diffusers/pull/4829 being merged it changed a bit the structure of diffusers lib. the method `randn_tensor` which always lives inside `diffusers.utils.torch_utils` has been removed from `diffusers.utils`' init. Therefore causes import issues for users that are using the latest diffusers or in the next release. This PR fixes this
cc @kashif @vwxyzjn
> [`core`] Fix import of `randn_tensor`

- docs/source/sft_trainer.mdx
- docs/source/using_llama_models.mdx
- examples/research_projects/stack_llama_2/scripts/sft_llama2.py
- trl/models/modeling_base.py
- trl/trainer/dpo_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/sft_trainer.py
since `peft` has deprecated `prepare_model_for_int8_training`
also add `use_gradient_checkpointing=args.gradient_checkpointing` to automatically follow the gradient checkpointing choice in training args
For RewardTrainer, this is the workaround to #480 proposed by #694. 
Concurrently @lewtun is working on #726 which adds the `use_gradient_checkpointing` for RewardTrainer. I'm happy to wait until it is merged to merge this.
> update to `prepare_model_for_kbit_training`

- .github/workflows/benchmark.yml
Having weird issues with `pip` caches in self-hosted runners. Taking them off.
> benchmark CI fix

- .github/workflows/benchmark.yml
https://github.com/huggingface/trl/pull/754#issuecomment-1715990325 actually triggered an infinite loop — this is because the comment contained "Here are the benchmark results" which somehow triggered the `contains(github.event.comment.body, '/Benchmark')` condition. This PR tighten things up further with `/benchmark-core-trl-experiments` command, making accidentally triggering the CI less likely.
> Imrpove benchmark ci

- trl/trainer/ppo_trainer.py
It took a while to understand why zero-masked tokens are one less than the length of query tokens. 
If I got it correctly, it is because the first logit (and state-value) from the outputs refers to the second token in the query. 
Hope this comment can be helpful to others who may encounter a similar question in the first-pass reading of the code :)
> [PPOTrainer] - add comment of zero masking (from second query token)

- .github/workflows/benchmark.yml
Basically just use `gh pr checkout xx` to support dealing with fork in the benchmark CI
> Support fork in benchmark CI

- trl/trainer/reward_trainer.py
In #726 we replaced the `RewardTrainer.args` with a dedicated `RewardConfig` to collect all hyperparameters in a dedicated class (in particular `max_length`).
Unfortunately, that implementation wasn't backwards compatible because `RewardTrainer.args` was of type `transformers.TrainingArguments` and that object doesn't have the `max_length` attribute. This meant that part of the logic which checks for the presence of `args.max_length` would throw an error for any users who hadn't updated their code to use `RewardConfig`.
This PR fixes that by first checking the type of `RewardTrainer.args` and raising a warning if it's `transformers.TrainingArguments`.
Happy to add a unit test for this, but I felt it was a bit of overkill.
> Ensure `RewardConfig` is backwards compatible

- examples/scripts/sft_trainer.py
This change avoids setting report_to="all" (the default behavior in transformers v4), which could lead to unexpected error messages for inexperienced users. Note that the default value of report_to will change anyway to "none" in transformers v5.
Fixes https://github.com/huggingface/trl/issues/788
> Changed the default value of the `log_with` argument

- examples/dpo.py
This reverts commit d603e7c52704054a9e7f306ae63acdafaa3d179a.
Temporarly reverts #759 as the example script seems to fail on main, making it not usable for users, flagged in https://github.com/huggingface/trl/commit/d603e7c52704054a9e7f306ae63acdafaa3d179a#commitcomment-127787118
Let's revert the PR until we find a better fix 
cc @natolambert
> [`DPO`] Revert "Add default Optim to DPO example (#759)"

- trl/trainer/ppo_trainer.py
Fixes https://github.com/huggingface/trl/issues/793
fixes a typo in the docstring and raises an error in case users pass a tensor with the wrong shape, hence redircting them to the correct usage.
cc @lvwerra
> [`PPOTrainer`] Fixes ppo trainer generate nit

- tests/test_data_collator_completion_only.py
- trl/trainer/utils.py
This is to make multi-turn chat conversation training work -
```python
instruction_template_with_context = "\n### Human:"  # We added context here: "\n". This is enough for this tokenizer
instruction_template_ids = tokenizer.encode(instruction_template_with_context, add_special_tokens=False)[2:]  # Now we have it like in the dataset texts: `[2277, 29937, 4007, 22137, 29901]`
response_template_with_context = "\n### Assistant:"  # We added context here: "\n". This is enough for this tokenizer
response_template_ids = tokenizer.encode(response_template_with_context, add_special_tokens=False)[2:]  # Now we have it like in the dataset texts: `[2277, 29937, 4007, 22137, 29901]`
data_collator = DataCollatorForCompletionOnlyLM(
instruction_template=response_template_ids, …
```
> Allow passing the token_ids as instruction_template in DataCollatorForCompletionOnlyLM

- examples/scripts/reward_trainer.py
- examples/scripts/sentiment_tuning.py
- examples/scripts/sft_trainer.py
In the maintained examples, `trust_remote_code` is set to `True` by default which means they cannot be run with the Falcon models due to the existence of custom modelling code in the model repos (takes precedence over `transformers` modelling code).
This PR sets it to `False` by default, which is also the default in `transformers`
> Set trust remote code to false by default

- examples/research_projects/stack_llama/scripts/merge_peft_adapter.py
This PR clarifies various docstrings, help messages, and assert messages within `merge_peft_adapter.py`. In addition, it also corrects an assertion to the intended test condition.
No functionality change was made.
> Clarify docstrings, help messages, assert messages in merge_peft_adapter.py

- trl/import_utils.py
IIUC, the check is currently comparing 3 to 3.8 and so is always true. I noticed this because Pyright [crashes](https://github.com/microsoft/pyright/issues/6116) because it special cases the version check.
> Fix version check in import_utils.py

- trl/import_utils.py
- trl/models/modeling_base.py
Fixes https://github.com/huggingface/trl/issues/852
in transformers we have recently moved deepspeed modules inside the `integrations` modules
This PR makes necessary changes so that users with previous transformers version can still use TRL.
cc @lvwerra
> [`core`] Fix import issues

- docs/source/sft_trainer.mdx
- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
This PR adds NEFTune: a new technique for enhancing Supervised fine-tuning results results proposed in: https://arxiv.org/abs/2310.05914
I propose a very simple API which is as simple as passing a valid `neftune_noise_alpha` argument when initializing the `SFTTrainer`. To avoid any surprising behaviour, we should revert to the original forward method at the end of the training. This is handled inside `def train()` that is a wrapper around `Trainer`'s `train` method. 
```python
from trl import SFTTrainer
dataset = load_dataset("imdb", split="train")
trainer = SFTTrainer(
"facebook/opt-350m",
dataset_text_field="text",
max_seq_length=512,
neftune_noise_alpha=5,
)
```
I still need to add few lines in the documentation. …
> [`SFTTrainer`] Adds NEFTune into `SFTTrainer`

- examples/scripts/reward_modeling.py
To make `reward_modeling.py` runnable again
> Remove duplicate key in `reward_modeling.py`

- examples/scripts/reward_modeling.py
Script arguments 'load_in_8_bit' and 'load_in_4_bit' were repeated multiple times.
Also removed truncation=True in the preprocess_function as it is already removing samples with higher lengths than reward_config.max_length in the filtering step.
It avoids problems with the scenario when reward_config.max_length is equal to the tokenizer max length. In this scenario, if truncation is set to True, we won't filter samples that have a higher maximum length than reward_config.max_length.
> [reward_modeling] Cleaning example script

- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
1. From LLaMA 2 paper, it says:
```
We also find it important to whiten the final linear scores (shown here by reversing the sigmoid with the logit function) in order to increase stability and balance properly with the KL penalty term (β) above.
```
2. This function is taken from [alpaca_farm](https://github.com/tatsu-lab/alpaca_farm/blob/64e489c67ea502ab5fa944bebde3078c9722f6ee/src/alpaca_farm/rl/ppo_trainer.py#L86)
> Add whiten ops before compute advatanges

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
As per title, this looks indeed much cleaner than monkey patching the forward pass of the embedding layer
No changes on the API are required
Stronger checks added on the CI 
cc @BenjaminBossan @lewtun @lvwerra
> [`NEFTune`] Make use of forward hooks instead

- trl/trainer/reward_trainer.py
There are some cases in which users may specify some callbacks. Then `PeftSavingCallback` should be appended. The current implementation will ignore it in this case.
> [Update reward_trainer.py] append PeftSavingCallback if callbacks is not None

- .github/workflows/tests.yml
Since it is super flaky recently let's deactivate it until we find a better and more stable solution.
> deactivate MacOS CI

- trl/trainer/ppo_config.py
adding specific dict structure to tracker_kwargs doc string to enable changing tracker params like wandb experiment name for ease, avoids needing to go deep into accelerate source
> updating PPOTrainer docstring

- setup.py
https://github.com/huggingface/trl/pull/897 uses `tyro.conf.arg(constructor=...)`, which is only available in `0.5.11`!
@vwxyzjn
> Bump minimum `tyro` version

- trl/trainer/dpo_trainer.py
Fixes https://github.com/huggingface/trl/issues/801
Fixes https://github.com/huggingface/peft/pull/1056
For DPO, when one uses `gradient_checkpointing` we need to attach hooks to enable inputs to have requires grad to true, otherwise the training will either silently fail or completely fail
cc @lvwerra
> [`DPO`] fix DPO + GC issues

- trl/trainer/dpo_trainer.py
addresses #914
DPO trainer logs a `wandb.Table` which gets added to the trainer's `state.log_history` and then can't be converted to a json when the trainer is trying to save the state.
This removes the `wandb.Table` from the log history, in a kind of ugly way.
> hotfix for dpo trainer

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
As per title, https://github.com/huggingface/transformers/pull/27141 is going to be merged in transformers, therefore this PR makes sure `SFTTrainer`'s NEFTune does not conflict with transformers Trainer one
cc @lvwerra
> [`SFTTrainer`] Make sure to not conflict between `transformers` and TRL implementation

- trl/trainer/dpo_trainer.py
Fixes https://github.com/huggingface/trl/issues/877
Indeed as stated in the issue when using `PeftModel` and call `generate` you need to pass explicit positional arguments otherwise generate will fail 
cc @lvwerra
> Fix DPOTrainer + PEFT 

- tests/test_modeling_value_head.py
- tests/test_sft_trainer.py
- trl/models/modeling_base.py
As per title, this PR fixes current failing CI on main due to the newest transformers release. The issue was mainly that we were checking for the presence of `pytorch_model.bin` files when loading the model checkpoints using `from_pretrained`. As safe serialization became the default saving behaviour in transformers we need to adapt things accordingly here to make sure we correctly deal with safe serialized models. 
Also pushed 2 models on the Hub under `trl-internal-testing` using safetensors, one which is sharded and the other one which is not sharded
Fixed also some issues with `SFTTrainer`.
cc @lvwerra
> [`CI`] Fix CI with new transformers release

- trl/trainer/sft_trainer.py
Fixes issues discussed [here](https://github.com/huggingface/transformers/pull/27162#discussion_r1380707614).
cc @younesbelkada
> Fix unwrapping peft models

- trl/trainer/dpo_trainer.py
- trl/trainer/sft_trainer.py
- Adds model as string support to the DPOTrainer.
- Adds model_kwargs optional args to SFT and DPO trainers.
- Refactors some of the SFT model instantiation logic as I thought the implementation was overly complicated.
This will greatly simplify the alignment handbook so it would be great to have it in the next trl release.
> Adds model kwargs to SFT and DPO trainers

- trl/models/modeling_value_head.py
Resolving issue #670.
Fixes #670
> Added support for custom EncoderDecoder models

- trl/trainer/dpo_trainer.py
ref_model and model shouldnt share the same ds config, so we shouldnt modify the ds config directly. or else, it will cause sth wrong when init deepspeed engine
> fix: dpo trainer ds config

- trl/trainer/sft_trainer.py
Currently TRL==0.7.3 is broken (a simple `from trl import SFTTrainer` fails) for users that do not have PEFT installed because of the typehint. This PR fixes it and I can confirm everything works fine on a fresh new enviornment on Google Colab
cc @lvwerra
> [`core`] Fix peft config typehint

- setup.py
Currently the doc builder job fails because of the issue described in https://github.com/TimDettmers/bitsandbytes/pull/859
The fix should be to pin bnb to the previous working version - 0.41.1
cc @lvwerra @mishig25
> Pin bnb to <=0.41.1

- docs/source/dpo_trainer.mdx
- docs/source/learning_tools.mdx
- docs/source/reward_trainer.mdx
- docs/source/sentiment_tuning.mdx
- docs/source/sft_trainer.mdx
- examples/research_projects/stack_llama/scripts/README.md
- examples/research_projects/stack_llama_2/scripts/README.md
- examples/research_projects/toxicity/README.md
Hi to whoever is reading this PR! 🤗 
While going through the `TRL` docs at https://huggingface.co/docs/trl/main/en/dpo_trainer, I realised there were some outdated links to the `examples`, and since those are now under different directories and/or paths, I've updated some of those references to point users to the actual examples.
> [DOCS] Fix outdated references to `examples/`

- trl/trainer/utils.py
This PR displays a warning message when the values of `pad_token_id` and `eos_token_id` are identical. This is to prevent unexpected behavior during multi-turn training.
After the multi-turn data training with [DataCollatorForCompletionOnlyLM](https://github.com/huggingface/trl/blob/9e9f024399b76842ece3552884bbc4f304fd4153/trl/trainer/utils.py#L56), I encountered an issue where the model continued generating outputs even after the assistant's turn had been completed. This issue was due to the equivalence of the tokenizer's eos token and pad token by default in some model, resulting in the eos token not being properly trained.
For instance, in the torch_call() function within [data_collator.py](https://github.com/huggingface/transformers/blob/7ee995fd9c692761c4601ddbffa2ac2ec9f27b0b/src/tra …
> [DataCollatorForCompletionOnlyLM] Warn on identical `eos_token_id` and `pad_token_id`

- docs/source/sft_trainer.mdx
Linked issue: https://github.com/huggingface/trl/issues/976 
While finding a proper fix, I propose to first clarifiy the docs a bit
As a follow up work, one needs to propose a proper fix for the case where `tokenizer.pad_token_id == tokenizer.eos_token_id`. 
cc @lvwerra
> [`DataCollatorForCompletionOnlyLM`] Add more clarification / guidance in the case `tokenizer.pad_token_id == tokenizer.eos_token_id`

- trl/trainer/ppo_trainer.py
This PR is to fix the issue in https://github.com/huggingface/trl/issues/960#issuecomment-1810865206
The issue will cause "gather stat" not to work for other distributed scenarios other than `MULTI_GPU`.
> make distributed true for multiple process

- trl/trainer/utils.py
Fixes #972
In `trl/trainer/utils.py` the code `func.__code__.co_varnames` is being used to check if the user passed a **formatting_func** with more than 1 parameter. This code actually counts the function variables rather than function parameters.
For instance
```
def add_v1(a):
return a + 1
def add_v2(a):
b = a + 1
return b
print("Number of parameters for add_v1 is", len(add_v1.__code__.co_varnames))
print("Number of parameters for add_v2 is", len(add_v2.__code__.co_varnames))
```
outputs
```
Number of parameters for add_v1 is 1
Number of parameters for add_v2 is 2
```
The proposed fix is to change the following:
```python
formatting_func_signature = formatting_func.__code__.co_varnames
if len(formatting_func_signature) > 1:
warnings.warn(
"The passed formatting_func has more than one …
```
> Fixed wrong trigger for warning

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
As flagged internally by @regisss
This fixes the case where the base model is not quantized and one uses gradient checkpointing
cc @lvwerra
> Adds `requires_grad` to input for non-quantized peft models

- examples/scripts/ppo_multi_adapter.py
- trl/models/modeling_base.py
- trl/models/modeling_value_head.py
A simpler and cleaner version of #472 focused on the main issues
`examples/multi_adapter_ppo.py` fails with multi-gpu
1.  you can't call `model.compute_reward_score` if `model` is wrapped in `DDP`
- fix by using `unwrap_model`
2. running crashes with `RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one....`
- Caused because the reward score is being calculated with gradient
- Add a `torch.no_grad()` and make sure that the reward adapter's `score` has `requires_grad=False`
in `modeling_base.py`, create the reward adapter before initializing the model and pass score into `init`
- makes adding the reward adapter a class method that can be extended
- makes the reward adapter name and score module more explicit, setting them in the init
- makes …
> [Multi-Adapter PPO] Fix and Refactor reward model adapter 

- examples/research_projects/stack_llama/scripts/rl_training.py
We load dataset twice, but in line 149 (new), we do  `ds = train_dataset.map` anyway
> Remove duplicate data loading in rl_training.py

- docs/source/sft_trainer.mdx
I noticed this minor bug while reading through the documentation. Please see the screenshot below or [visit the document page](https://huggingface.co/docs/trl/sft_trainer#trl.SFTTrainer).
Notice the additional ```` ```python ````. In addition, the `PretrainedModel` kwargs in the `SFTTrainer` is missing.
To resolve the issue, the following changes were made:
- Add the missing backticks.
- Add `model_init_kwargs` to `SFTTrainer` initialization to demonstrate its usage.
> [Document] Minor fixes of sft_trainer document

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
Implemented the IPO training loss from the paper:
A General Theoretical Paradigm to Understand Learning from Human Preferences
https://arxiv.org/pdf/2310.12036.pdf
> [DPO] IPO Training loss

- trl/trainer/dpo_trainer.py
Address part 1 of #952 by removing `store_metrics` and switching to more standard `compute_metrics` letting `Trainer` handle logging
> [DPO] Refactor eval logging of dpo trainer

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
With this PR we'll precompute the packed iterable dataloader and push it into a dataset. That will make sure the epoch estimate is right and we have a working progress bar. 
Fixes #1008 #1004
> [SFT Trainer] precompute packed iterable into a dataset

- trl/models/modeling_base.py
If using ```dummy_accelerator = Accelerator()```, it will cause the ```ACCELERATE_USE_DEEPSPEED``` environment variable to be set in advance, resulting in the regeneration of ```DeepSpeedPlugin``` and causing a change in the type of ```trainer.accelerator.state.deepspeed_plugin.hf_ds_config```
[source code: regeneration DeepSpeedPlugin](https://github.com/huggingface/accelerate/blob/3499cf25aa431ed3eeb7969f1d9b501ef20d0911/src/accelerate/accelerator.py#L284-L292)
[source code: HfTrainerDeepSpeedConfig  -> HfDeepSpeedConfig ](https://github.com/huggingface/accelerate/blob/3499cf25aa431ed3eeb7969f1d9b501ef20d0911/src/accelerate/utils/dataclasses.py#L600)
which may lead to errors similar to https://github.com/microsoft/DeepSpeed/issues/3733, …
> Improve PreTrainedModelWrapper._get_current_device

- trl/trainer/sft_trainer.py
The `compute_metrics` argument defaults to `None` in the `SFTTrainer` class, but the docstring was inaccurate. This PR updates the descriptions of the argument to match the definition in the constructor.
> Update doc for the computer_metrics argument of SFTTrainer

- tests/test_peft_models.py
- tests/test_sft_trainer.py
- trl/models/modeling_base.py
Fixes failing tests on main due to PEFT release that introduced safetensors default serialization
cc @lvwerra
> [`core`] Fix failing tests on main

- trl/trainer/sft_trainer.py
Fixes https://github.com/huggingface/trl/issues/1055
This PR makes sure the SFTTrainer deals correctly the args when it is set to `None`, thus avoiding the issue described on https://github.com/huggingface/trl/issues/1055
cc @lvwerra
> [`SFTTrainer`] Fix Trainer when args is None

- trl/trainer/dpo_trainer.py
Hi to whoever is reading this! 🤗
This PR only adds the IPO loss within the available ones within the exception message of `ValueError` when `self.loss_type` is neither `hinge`, `sigmoid` or `ipo`.
> Add missing `loss_type` in `ValueError` message

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
add Tahneman-Tversky optimization (KTO) loss function from https://github.com/ContextualAI/HALOs]
fixes #1072
> [DPO] add KTO loss

- examples/scripts/sft.py
Adds a few args to the SFT example to enable simpler training of Mixtral from the command line
> Add args to SFT example

- tests/test_ppo_trainer.py
4.36.0 introduced SDPA support by default which led to tiny numerical differences
> Make CI happy

- examples/research_projects/stack_llama_2/scripts/README.md
- examples/research_projects/stack_llama_2/scripts/sft_llama2.py
This PR removes `tyro in `examples/research_projects/stack_llama_2/scripts/sft_llama2.py`. 
Closes #1032
Wandb run seems ok — the loss goes down. 
https://wandb.ai/costa-huang/huggingface/runs/ora3z20f
> Removing `tyro` in `sft_llama2.py`

- examples/scripts/sft.py
Use `report_to` instead of `log_with` to keep consistency with transformers.
> Log arg consistency

- examples/research_projects/stack_llama_2/scripts/sft_llama2.py
- examples/research_projects/toxicity/scripts/evaluate-toxicity.py
- examples/scripts/ddpo.py
- examples/scripts/ppo.py
- trl/__init__.py
- trl/core.py
- trl/import_utils.py
- trl/models/modeling_base.py
- trl/trainer/ppo_trainer.py
Since npu already supports Transformer/Accelerate and Peft out of the box, this would be a good addition to run TRL out of the box on npu.
cc @younesbelkada and @lvwerra
> [Feature] Add Ascend NPU accelerator support 

- docs/source/sft_trainer.mdx
- setup.py
- trl/trainer/__init__.py
- trl/trainer/reward_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
1. Inline with QLoRA code when using bf16 [here](https://github.com/artidoro/qlora/blob/main/qlora.py#L396-L405), added `peft_module_casting_to_bf16`.
2. Added `append_concat_token` flag so that datasets which already have `eos_token` at the end of each sample can skip appending the eos/concat token
3. Removes the callback `PeftSavingCallback` and bumps the minimum transformers version to `4.31.0` which handles this by default. The current `PeftSavingCallback` would fail when using PEFT+DeepSpeed and the trainer handles this properly.
> `peft_module_casting_to_bf16` util method, `append_concat_token` flag, remove callback `PeftSavingCallback`

- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
1. Tokenization using chat template doesn't add special tokens such as bos_token by default. https://github.com/huggingface/transformers/blob/17506d1256c1780efc9e2a5898a828c10ad4ea69/src/transformers/tokenization_utils_base.py#L1750
2. Related issue elsewhere: https://github.com/vllm-project/vllm/issues/2012
3. This leads to redundant bos/special tokens being added by the tokenizer in SFT training here: 
https://github.com/huggingface/trl/blob/f100ca34cca92e3a09a04b0f07950703b0aa7fd0/trl/trainer/utils.py#L429
This PR makes it configurable while retaining backwards compatibility.
> Make prepending of bos token configurable.

- trl/trainer/sft_trainer.py
1. Enables proper handling of `gradient_checkpointing_kwargs` when using PEFT without the quantization, such as PEFT+DeepSpeed.
> fix gradient checkpointing when using PEFT

- trl/trainer/ddpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
As per title, this PR adds the tag `"trl-xxx"` whenever someone pushes a model with SFTTrainer, PPOTrainer or DPOTrainer
Example repo here: https://huggingface.co/ybelkada/out-test
cc @lvwerra
> [`xxxTrainer`] Add tags to all trainers in TRL

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
The kto loss in the DPOTrainer is a special-case of the general KTO loss, and as such we will implement a separate KTOTrainer and rename the special case loss to `kto_pair`
> [DPO] rename kto loss

- docs/source/sft_trainer.mdx
This PR adds details about unsloth library: https://github.com/unslothai/unsloth that can bring very interesting out of the box speedups to users. In the future, I'll make sure users that use unsloth + SFTTrainer have the tag `unsloth` when they push models on the hub with unsloth
cc @danielhanchen @lvwerra 
@danielhanchen let me know if the content does look to you! Feel free to add any suggestion directly in the PR
Related: https://github.com/unslothai/unsloth/issues/34
> [`Docs`] Add unsloth optimizations in TRL's documentation

- trl/trainer/ddpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
Instead of pushing a single tag, this PR changes the current behaviour of `xxxTrainer` tagging to push multiple tags (e.g. `trl` & `sft`) instead of a single tag
cc @lvwerra @osanseviero 
example here: https://huggingface.co/ybelkada/test-multi-tag
> [`xxxTrainer`] multi-tags support for tagging

- examples/research_projects/stack_llama/scripts/README.md
- examples/research_projects/stack_llama/scripts/supervised_finetuning.py
no_gradient_checkpointing is always false
> clear up the parameters of supervised_finetuning.py

- trl/core.py
Hi all,
Just a quick PR to add type hinting to `core.py`
I noticed a few methods are not currently used in the codebase, such as `build_bert_batch_from_txt` and `listify_batch`. Not sure if they are being used elsewhere or we should clean them up. Let me know!
Zach
> Add type hints to core.py

- examples/scripts/ddpo.py
In `examples/scripts/ddpo.py` , the `AestheticScorer.mlp` loads weights to cuda device by default 
```python
self.mlp.load_state_dict(state_dict)
state_dict = torch.load(cached_path)
```
which throws an error for non-cuda devices, so loading weights on cpu first 
```python
self.mlp.load_state_dict(state_dict, map_location=torch.device('cpu'))
state_dict = torch.load(cached_path)
```
and then copy to target device 
```python
if is_npu_available():
scorer = scorer.npu()
elif is_xpu_available():
scorer = scorer.xpu()
else:
scorer = scorer.cuda()
```
> fix_ddpo_demo

- trl/trainer/ddpo_trainer.py
- trl/trainer/ppo_trainer.py
#1133 broke `PPOTrainer`s `push_to_hub` method. Since `PPOTrainer` does not inherit from `transformers.Trainer` for the PPOTrainer we just need to manually add the tag `ppo` in the model card template. 
An example here for PPO: https://huggingface.co/ybelkada/test-ppo-tag 
and for DDPO: https://huggingface.co/ybelkada/test-ddpo-tag
I will make a patch release to include this commit
cc @lvwerra
> [`PPOTrainer` / `DDPOTrainer`] Fix ppo & ddpo push to Hub

- docs/source/sft_trainer.mdx
- examples/scripts/sft.py
After experiencing issues with GPTQ Conversion, discussed in this issue https://github.com/huggingface/trl/issues/1138.
I was able to resolve it by passing the Tokenizer into the `SFTTrainer`.
I also noticed that lowering `gradient_accumulation_steps` helps resolve the `linalg.cholesky` error experienced with pytorch.
I've left a note under `Best Practices` in the `sft_trainer.mdx` file.
We can decide where to best put this note in regards to GPTQ Conversion.
> SFT Tokenizer Fix

- trl/trainer/dpo_trainer.py
Currently, when calculating metrics in `DPOTrainer`, the values are moved to the CPU and the mean is calculated. However, when doing this, the cost of moving the values to the CPU is very large.
So I changed the device order to improve speed. Below are the `torch profiler` results before and after changing the order in my experiment.
As shown in the figure, the operation to move to the CPU has a similar cost to the forward of the model.
After making the change, the time taken has decreased significantly.
> Change device access order for speedup of calculating metrics in DPOTrainer

- examples/scripts/ddpo.py
- tests/test_ddpo_trainer.py
- trl/models/modeling_base.py
- trl/models/modeling_sd_base.py
- trl/trainer/ddpo_trainer.py
It's time.
Cc: @metric-space @younesbelkada
> add: support for `peft` in ddpo.

- trl/trainer/ppo_trainer.py
`train_minibatch` is called by `step` [here](https://github.com/huggingface/trl/blob/20428c48ba651b2bc11b2a73e9eb9568b1af3f96/trl/trainer/ppo_trainer.py#L795) (and only there), with minibatches of first dimension size `self.config.mini_batch_size`. To match this, the docstring in `train_minibatch` should say that the inputs are of shape `[mini_batch_size, XXX_length]`, not `[batch_size, XXX_length]`. Alternatively, to be very precise, one could instead say that they are of size `[self.config.mini_batch_size, XXX_length]`.
> Correct shapes in docstring of PPOTrainer's train_minibatch method

- trl/trainer/ppo_trainer.py
> Fix batch all gather

- docs/source/ppo_trainer.mdx
**The usage of the variable “epoch” is misleading (incorrect) in the original Doc:**
the dataloader does not contain the data for ALL epochs, but 1 epoch only, thus  
`"for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader))" ` is misleading and does not actually stores the epoch #. 
The correct version comes from the TRL PPO notebook tutorial  (https://github.com/huggingface/trl/blob/main/examples/notebooks/gpt2-sentiment-control.ipynb), which uses an outer loop to capture the epochs.
I posted also the question on forum: https://discuss.huggingface.co/t/confusing-and-possibly-misleading-ppo-trainer-code-from-trl-api-doc-tutorial/67531
> Fix misleading variable "epoch" from the training loop from PPOTrainer Doc.

- trl/trainer/sft_trainer.py
I've noticed that SFTTrainer removes dataset columns before passing samples to the data collator, even when remove_unused_columns is set to False in the training arguments.
This happens here:
https://github.com/huggingface/trl/blob/main/trl/trainer/sft_trainer.py#L410
This PR adds a check to see if `args.remove_unused_columns` is set to `True` (the default). If not, it sets `remove_columns` to `None` in the call to `dataset.map()`, i.e. it doesn't remove other columns.
This can be useful if you'd like access to dataset features other than the tokenizer output in your data collator.
Closes #1186.
> SFTTrainer: follow args.remove_unused_columns

- trl/trainer/dpo_trainer.py
Some tokenizers, like Llama BPE tokenizer, might merge tokens into one such as the case where there is a space follow by some characters like `$`. 
In a previous PR we handled the case for chosen/rejected but one small improvement is to remove the extra space token from the end of the prompt used for generation in `get_batch_samples`. It should left to the model if the next generated token is just the space token or one such that it combines the space with other token into one. To do so, we need to manually check `prompt_ids` for chosen/rejected and by itself and chose the shortest knowing that they can only differ by 1 token. 
Given the following example, `prompt + chosen` will leave the space after `[\INST]` unchanged but it wont be the case for `prompt+rejected` since it starts with …
> Handle last token from generation prompt

- docs/source/dpo_trainer.mdx
- trl/trainer/dpo_trainer.py
I tend to use QLoRA for larger base model fine-tunes (30b+), but for the DPO phase I end up having a bit of a dilemma.
If I don't want to load the model twice, I need to merge the adapter into the base model, then create another adapter on top of the merged model (so the existing unload mechanism works).
There are two ways to merge, the way recommended by Tim Dettmers, in which you load the model in 4 bit, then upscale it back to bf16, then merge the weights in.  Using this method leads to 1-2% increase in benchmark scores pretty universally:
https://github.com/jondurbin/qlora/blob/main/qmerge.py
Or the standard merge where you don't prequantize the weights:
https://github.com/jondurbin/qlora/blob/main/merge.py
If you use that quant->dequant->merge method, it means you've already …
> Allow swapping PEFT adapters for target/ref model.

- tests/test_data_collator_completion_only.py
- trl/trainer/utils.py
The current code in DataCollatorForCompletionOnlyLM assumes that the first deteced occurence of `instruction_template` comes before the first detected occurence of `response_template`. This is reasonable, since in current applications conversations are initiated by the user, not the assistant. However, this can fail if the first instruction is marked differently from all the other instructions, which can if a context-sensitive tokenizer such as Llama-2 tokenizes the instruction_template differently at the start of a string than in the middle.
This PR fixes this by checking if the first detected instruction is after the first detected response. If that is the case, we can assume we missed the first instruction. We then insert a new `human_token_ids_idxs` starting at 0.
Fixes #1184.
> Fix instruction token masking

- tests/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
PPO trainer currently separately calculates the KL that's reported in the stats and to wandb, and always uses the estimated KL for this. That's fine when the estimated KL is also used for training (`kl_penalty = 'kl'`), but leads to a mismatch when using `kl_penalty = 'abs'`, `kl_penalty = 'mse'`, or `kl_penalty = 'full'`. Additionally, this can lead to a warning about negative KL being triggered even in cases where the KL used in training is not and cannot be negative.
This PR changes it so that instead the KL that is calculated during training is kept and used for stats and reporting.
Tested using the PPO example script in both single-GPU and Deepspeed stage 2 training, leading to identical results in the `kl_penalty = 'kl'`case. Verified also that `kl_penalty = 'abs'` now does not …
> Fix reported KL in PPO trainer

- tests/test_dpo_trainer.py
- tests/testing_utils.py
- trl/__init__.py
- trl/import_utils.py
- trl/trainer/dpo_trainer.py
- trl/trainer/utils.py
Fixes https://github.com/huggingface/trl/issues/1202 which is a regression 
https://github.com/huggingface/trl/pull/1143 introduced `peft_module_casting_to_bf16` for `DPOTrainer` which worked fine when ` generate_during_eval` is set to `False`.
`peft_module_casting_to_bf16` will cast the LayerNorm layers in fp32 for stability purposes for smoother training, in case one uses peft + 4-bit quantization (QLoRA).
If one uses `bf16=True` in the `TrainingArguments`, `Trainer` will automatcially compute the loss under the torch.cuda.amp.autocast regime, making the forward pass possible to work without any dtype mismatch issue
However, we need to make sure all other methods inside `DPOTrainer` that call the model's forward pass will also use that context manager to make sure there is no dtype …
> [`DPOTrainer`] Fix peft + DPO + bf16 if one uses `generate_during_eval` or pre-computed logits

- trl/trainer/ddpo_trainer.py
The content of `latents` is defined in the following code in `modeling_sd_base.py`:
```python
latents = self.prepare_latents(
batch_size * num_images_per_prompt,
num_channels_latents,
height,
width,
prompt_embeds.dtype,
device,
generator,
latents,
)
```
As a result, the shape of `latents` and `next_latents` mentioned in the description of the `calculate_loss` method in the `DDPOTrainer` class should be `[batch_size, num_channels_latents, height, width]`.
> Fix shape descriptions in calculate_loss method

- trl/trainer/reward_trainer.py
This fixes an error in reward training when the `loss` field of model output is non-empty, and `model(...)[0]` returns loss instead of logits. That can happen with FSDP. This PR changes it so the trainer explicitly grabs `model(...)["logits"]` instead.
Closes #1195
> Fix FSDP error

- docs/source/dpo_trainer.mdx
- docs/source/sft_trainer.mdx
> Update Unsloth SFT, DPO docs

- .github/workflows/docker-build.yml
- docker/trl-latest-gpu/Dockerfile
- docker/trl-source-gpu/Dockerfile
As discussed internally, this is a first step towards creating our CI system that will run on self-hosted runners on GPU. I want to test everything on two scenarios:
- transformers / accelerate / peft all installed from source
- all the libraries above installed from latest pypi 
We currently use similar docker images in transformers & peft and this is very convenient for testing purpose and tracking down where the issues do come from. 
The dockerfile files are mostly copied from PEFT: https://github.com/huggingface/peft/blob/main/docker/peft-gpu/Dockerfile
cc @lvwerra
> [`core` / `Docker`] Add  workflow to build TRL docker images

- trl/trainer/__init__.py
- trl/trainer/reward_config.py
- trl/trainer/reward_trainer.py
Based on discussion here: https://github.com/huggingface/trl/pull/1181#discussion_r1445606450
Basic idea is to have have a dedicated config per trainer, each in their own module. Since the code path was never exposed as an absolute path, I believe this is backwards compatible
> Refactor RewardConfig to own module

- trl/trainer/dpo_trainer.py
Logs metrics on all distributed processes when using FSDP. 
All processes need access to the metrics in order for things like "Early Stopping" / "Load Best Model At End" to work. You get a `KeyError` on workers #1 - #N, otherwise.
There is no need for this guard as the logging callbacks themselves check if they are the main process before printing metrics to the terminal.
> Logs metrics on all distributed processes when using DPO & FSDP

- tests/test_dpo_trainer.py
- trl/trainer/utils.py
Fixes #1149. Improves the error message when `tokenizer.pad_token` is `None` by providing the cause of the error and suggesting the next step to take.
```python
> tokenizer = AutoTokenizer.from_pretrained(...)
> print(tokenizer.pad_token)
None
> dpo_trainer = DPOTrainer(...)
> dpo_trainer.train()
...
TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
```
```python
> tokenizer = AutoTokenizer.from_pretrained(...)
> print(tokenizer.pad_token)
None
> dpo_trainer = DPOTrainer(...)
> dpo_trainer.train()
...
ValueError: Padding is enabled, but the tokenizer is not configured with a padding token. Explicitly set `tokenizer.pad_token` (e.g. `tokenizer.pad_token = tokenizer.eos_token`) before calling the trainer.
```
Thanks in advance!
> fix: improve error message when `pad_token_id` is not configured

- trl/trainer/sft_trainer.py
> Fix a typo in variable name

- docs/source/dpo_trainer.mdx
- trl/trainer/dpo_trainer.py
so that the beta is not dependent on the sequence length with IPO
> [DPO] average_log_prob when loss is IPO

- docs/source/sft_trainer.mdx
- trl/trainer/sft_trainer.py
This PR address #1249. With the fix, the new data preprocessing times become:
```bash
accelerate launch \
--config_file="./conf/accelerate/single_gpu.yaml" \
--num_processes 1 \
examples/sft.py
accelerate launch \
--config_file="./conf/accelerate/multi_gpu.yaml" \
--num_processes 8 \
examples/sft.py
```
So there is still some overhead in the distributed setting, but this is a big improvement over the 10X slowdown I was previously seeing.
My only note is that I wasn't exactly sure where to put the `PartialState().is_main_process` in the `SFTTrainer`, so that could maybe use a second set of eyes @younesbelkada. Thanks!
> Only load data on main process

- commands/run_sft.sh
- docs/source/lora_tuning_peft.mdx
- examples/scripts/sft.py
I also tested with `python examples/scripts/sft.py --output_dir sft_openassistant-guanaco  --model_name meta-llama/Llama-2-7b-hf --dataset_name timdettmers/openassistant-guanaco --load_in_4bit --use_peft --per_device_train_batch_size 4 --gradient_accumulation_steps 2` which seems to work (https://wandb.ai/costa-huang/huggingface/runs/m35stukl/logs)
> Fix SFT tuner in CI

- docs/source/dpo_trainer.mdx
In the [Accelerate DPO fine-tuning using unsloth](https://huggingface.co/docs/trl/dpo_trainer#dpo-trainer) code example, `args` receives a variable named `training_args`, while the variable created is called `args`.
> Fix wrong variable name in DPOTrainer documentation example

- trl/trainer/dpo_trainer.py
Recently I have seen many tutorials that passes both the ref_model and a peft_config, this should be not allowed as it is very memory inefficient. This PR enhances the UX by raising a value error if peft_config if passed together with a ref_model and guiding the user on what should be the best practice.
cc @kashif
> [`PEFT` + `DPO`] Raise value error if one passes a ref_model and a peft_config

- trl/trainer/dpo_trainer.py
1. The padding token in DPO trainer is wrongly set to 0 when tokenizer uses a different token id for padding and tokenizer is passed. This happens because the conditional statement is checking if padding value is `None` but if the default is 0, it is never `None`.
> fix padding in dpo trainer

- trl/trainer/dpo_trainer.py
Fixes: https://github.com/huggingface/trl/issues/1217 
Fixes: https://github.com/huggingface/transformers/issues/26877
Fixes: https://github.com/huggingface/trl/issues/1266
Simply setting `use_cache=False` circumvents all issues with FA-2 + DPO + Mistral. in fact we should bypass that check since we are not in text generation mode when computing the loss function. `use_cache` is retrieved from the model config by default which falls back always to `True`. The cache is not used anyway when purely computing the logits so this change is fully BC
cc @kashif @vwxyzjn 
To test that, I managed to repro the issue by adding `--attn_implementation "flash_attention_2"` in the dpo shell script on a A100 machine, and I confirm this PR fixes it. Unfortunately our CI runners are not compatible with FA2 …
> [`DPOTrainer`] Fix DPO trainer + mistral + FA2

- examples/scripts/dpo.py
- trl/trainer/dpo_trainer.py
Adds the simple fix proposed in https://github.com/huggingface/trl/pull/1255 to speed up data processing for DPO + multi GPU + fixes the example test that I made it fail after https://github.com/huggingface/trl/pull/1289 
cc @kashif
> [`DPOTrainer`] Load data only on main process + fix dpo example test

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
Happens when one passes a str model + peft_config
cc @lvwerra
> Fix sft trainer when args is None

- trl/trainer/dpo_trainer.py
Some issues were leading the auto-generation of the API reference to fail and the args were overlapped in the documentation page, see screenshot below:
*Note that the issue was most likely due to a duplicated colon (:) within the args `model_init_kwargs` and `ref_model_init_kwargs`.*
> Fix `DPOTrainer` docstrings

- examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
- examples/scripts/dpo.py
- trl/core.py
- trl/environment/base_environment.py
- trl/models/modeling_base.py
- trl/trainer/dpo_trainer.py
- trl/trainer/iterative_sft_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/utils.py
This was done automatically with [hauntsaninja/no_implicit_optional](https://github.com/hauntsaninja/no_implicit_optional).
This will help avoid bugs such as the one fixed by #1295, since possibly-`None` values are marked as such by the type annotations.
> Types: Fix PEP 484 implicit-optional compliance

- trl/trainer/dpo_trainer.py
Added the num_proc parameter to the eval_dataset processing (similar to train_dataset)
cc @kashif
> [DPOTrainer] Add multiprocessing for the eval_dataset map

- tests/slow/test_dpo_slow.py
- tests/slow/test_sft_slow.py
- tests/test_best_of_n_sampler.py
- tests/test_core.py
- tests/test_data_collator_completion_only.py
- tests/test_dataset_formatting.py
- tests/test_ddpo_trainer.py
- tests/test_dpo_trainer.py
- tests/test_environments.py
- tests/test_modeling_value_head.py
- tests/test_no_peft.py
- tests/test_peft_models.py
- tests/test_ppo_trainer.py
- tests/test_reward_trainer.py
- tests/test_sft_trainer.py
This PR runs https://github.com/akx/codemod-unittest-to-pytest-asserts to rewrite Unittest `self.assert...` assertions as plain assertions that can be introspected by Pytest's [assert rewriting](https://docs.pytest.org/en/7.1.x/how-to/assert.html).
> Codemod Unittest assertions to bare asserts

- trl/trainer/dpo_trainer.py
Issue: An `AttributeError` was being raised due to trying to call `.to()` on an integer object. This error occurred because `ref_logratios` was initialized as an integer (`0`) instead of a tensor. https://github.com/huggingface/trl/issues/1238
Fix: The fix involved initializing `ref_logratios` as a tensor with PyTorch's `torch.tensor()` function before calling the `.to()` method.  Also, `ref_logratios` is now stored as an instance variable `self.ref_logratios` during initialization to ensure it retains its value throughout the lifecycle of the object.
> Fix AttributeError in dpo_trainer for reference_free case in dpo_loss function

- docs/source/ppo_trainer.mdx
Both the argument's name and the value need to be renamed in the code snippet. Otherwise we get both
`NameError: name 'train_dataset' is not defined`
and
`TypeError: PPOTrainer.__init__() got an unexpected keyword argument 'train_dataset'`
> Fix doc snippet PPOTrainer argument train_dataset -> dataset

- docs/source/dpo_trainer.mdx
In the document as it is now, the best practice recommendations on merging adaptors into the base model seem neither consistent nor correct.
For example, the documentation links a tweet with a recommendation to merge adaptors into a quantized model, and a script that supposedly illustrates how to apply that recommendation. But the script actually does the opposite of what the tweet recommends, first dequantizing the model. 
There are similar inconsistencies/ambiguities further in that paragraph. For example, saying that using an unquantized model would lead to lower performance (I changed it to "higher memory demand").
Overall, I updated the paragraph to improve consistency and provided links to slightly more evidence-based merging recommendations.
> Best practice recommendation update for dpo_trainer.mdx

- .pre-commit-config.yaml
- examples/hello_world.py
- examples/research_projects/stack_llama/scripts/rl_training.py
- examples/research_projects/tools/calculator.py
- examples/research_projects/tools/python_interpreter.py
- examples/research_projects/tools/triviaqa.py
- examples/research_projects/toxicity/scripts/gpt-j-6b-toxicity.py
- examples/scripts/dpo.py
- examples/scripts/ppo.py
- examples/scripts/ppo_multi_adapter.py
- examples/scripts/reward_modeling.py
- examples/scripts/sft.py
- pyproject.toml
- scripts/log_example_reports.py
- scripts/log_reports.py
- scripts/stale.py
- setup.cfg
- tests/test_no_peft.py
- tests/test_ppo_trainer.py
- tests/test_reward_trainer.py
- trl/core.py
- trl/environment/base_environment.py
- trl/extras/best_of_n_sampler.py
- trl/models/modeling_base.py
- trl/models/modeling_sd_base.py
- trl/models/modeling_value_head.py
- trl/trainer/ddpo_config.py
- trl/trainer/ddpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/sft_trainer.py
As discussed in #1297, this PR wires up `ruff` (it apparently had been partially configured in #690 but never enabled) and fixes some common issues.
> pre-commit: replace linters + formatters with Ruff; fix some issues

- README.md
Clarify that language models must be transformers models for text. This is a bit redundant with intro description, but attempts to better address a question that does come up (issue 1257).
Fixes #1257 
Cc: @saptab @younesbelkada
> Update README.md to clarify model requirement

- trl/models/modeling_sd_base.py
- trl/models/sd_utils.py
Fixes recent issues with respect to diffusers import by copying over the method we try to import in diffusers. 
Fixes https://github.com/huggingface/trl/issues/1293
cc @lvwerra @abhishekkrthakur
> [`core` / `DDPO`] Fix diffusers import issue

- .github/workflows/tests-main.yml
As per title and similar PR as https://github.com/huggingface/peft/pull/1461 - let's test also on transformers / PEFT main whenever we push a commit on main to make sure we can catch early bugs on transformers main before the releases
cc @lvwerra
> [`CI`] Add tests on transformers peft main on push main

- examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
see https://github.com/huggingface/trl/issues/1348
> fix 8-bit multi-gpu training bug 

- trl/import_utils.py
To be consistent with the existing code and maintain compatibility for environments running Python versions earlier than 3.8, this pull request includes a minor adjustment to the `is_transformers_greater_than` function.
> Fix transformers version checking for Python < 3.8

- .github/workflows/docker-build.yml
- .github/workflows/tests-main.yml
As per title and a follow up PR of https://github.com/huggingface/peft/pull/1503 
Now we should get notifications on slack for docker image build & TRL CI tests on  transformers / PEFT main on each commit on the main branch
cc @lvwerra
> ENH: Send Docker and transformers main CI results on slack after merging on main

- docs/source/sft_trainer.mdx
- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
Fixes: https://github.com/huggingface/trl/issues/1343
Adds the possibility for users to enable/disable packing for the eval_dataset using a ternary logic (if None -> packing else eval_packing)
cc @lvwerra @kashif
> FEAT: [`SFTTrainer`] Add  `eval_packing`

- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
Fixes: https://github.com/huggingface/trl/issues/1365
This gives more flexibility to users that know what they're doing, by creating a new flag `force_use_ref_model` in case they want to use a different ref_model that the base model 
cc @kashif
> FEAT: `force_use_ref_model` for power users

- .github/workflows/tests-main.yml
This will enable running the slack webhook for the transformers tests
> FIX: Change ci to fail-fast=False

- examples/scripts/ddpo.py
Fixes `TypeError: Got unsupported ScalarType BFloat16` when logging the reward during bf16 finetuning with ddpo
> Log ddpo reward as float to fix numpy conversion during bf16 training

- examples/research_projects/stack_llama/scripts/rl_training.py
1. Fix the following error:
```
File "/mnt/disk4/yuanwu/workspace/trl/examples/research_projects/stack_llama/scripts/rl_training.py", line 263, in <module>
pipe_outputs = sentiment_pipe(texts, **sent_kwargs)
File "/mnt/disk4/yuanwu/workspace/transformers/src/transformers/pipelines/text_classification.py", line 156, in __call__
result = super().__call__(*args, **kwargs)
File "/mnt/disk4/yuanwu/workspace/transformers/src/transformers/pipelines/base.py", line 1143, in __call__
outputs = list(final_iterator)
File "/mnt/disk4/yuanwu/workspace/transformers/src/transformers/pipelines/pt_utils.py", line 124, in __next__
item = next(self.iterator)
File "/mnt/disk4/yuanwu/workspace/transformers/src/transformers/pipelines/pt_utils.py", line 125, in __next__
processed = self.infer(item, …
```
> Fix the pad_token_id error

- examples/scripts/reward_modeling.py
- trl/trainer/model_config.py
- trl/trainer/utils.py
Fixes https://github.com/huggingface/trl/issues/1379
Indeed, `task_type` is always hard-coded to `CAUSAL_LM` which should be modulable for other scripts such as `reward_modeling.py` to be able to pass other `task_type`.
cc @lewtun @kashif WDYT?
> FIX [`RewardModeling`] Fix RM script for PEFT

- trl/core.py
The `top_k_top_p_filtering()` method will be deprecated (i.e. removed) from `transformers >= 4.39` and the simplest solution is to copy the method directly into `trl` 
Closes #1409
> Fix import error from  deprecation in transformers

- trl/trainer/kto_trainer.py
fix model init when args are given
> [KTO] model init when args are given

- tests/test_iterative_sft_trainer.py
- tests/test_no_peft.py
- tests/test_ppo_trainer.py
The recent accelerate release includes: https://github.com/huggingface/accelerate/pull/2472 that sets `set_to_none` to `True` by default for optimizers, leads to our tests failing since we explictly check for `param.grad` after the optimization step. The fix is to patch the `optimizer.zero_grad` method to expliclty call it with `set_to_none=False`
cc @lvwerra
> CI: Fix CI on main

- tests/test_kto_trainer.py
- trl/trainer/kto_trainer.py
since the kwargs is a dict the torch_dtype might be a string but transformer needs the dtype
> [Kto] torch_dtype kwargs fix

- trl/__init__.py
This PR fixes the current failing doc build on main: https://github.com/huggingface/trl/actions/runs/8325681030/job/22779801587 
When implementing the lazy import, I forgot to add `__version__` in `extra_objects`. This PR fixes it
cc @lvwerra
> FIX: fix doc build on main

- README.md
The current PPOTrainer example given in the main README does not work for two reasons: 1) pad token, 2) relationship between batch size, minibatch size, and gradient accumulation steps.
This PR addresses these two issues :).
Fixes: https://github.com/huggingface/trl/issues/1442
> Fix PPOTrainer README example

- README.md
- docs/source/dpo_trainer.mdx
- docs/source/ppo_trainer.mdx
> FEAT: Update README to add DPO + CLIs

- examples/scripts/chat.py
- trl/commands/scripts
This PR passes the `revision` arg to the tokenizer so one can chat with models at a given branch/revision. I also set the padding token ID to suppress warnings on models that don't have this in their config.
> Fix chat CLI for model revisions

- tests/test_reward_trainer.py
Since we are requiring peft >= 0.4.0
This check fails when peft_version = "0.10.0"
> [peft] Update test_reward_trainer.py to fix tests

- trl/trainer/cpo_trainer.py
- trl/trainer/orpo_trainer.py
This PR fixes the bug described in #1477, similarly to the former issue within the `DPOTrainer` solved by @younesbelkada  (so kudos to him!).
Adding `use_cache=False` when running the forward pass during training is not needed, because we're not in an inference use case, only computing the logits, and it runs into conflicts with Flash Attention 2, so disabling it has no other impact than fixing the collision bug with FA2.
Closes #1477 
cc @kashif @younesbelkada
> Add `use_cache=False` in `{ORPO,CPO}Trainer.concatenated_forward`

- docs/source/trainer.mdx
Hey! Thanks for this great project...
I noticed that several Trainer/Config classes are missing here: https://huggingface.co/docs/trl/main/en/trainer
I'm adding them and introducing alphabetical order.
> docs: add missing Trainer classes and sort alphabetically

- examples/scripts/kto.py
This PR removes the custom preprocessing that's applied with the Anthropic dataset in favour of:
* A small, high quality dataset that's already suitable to apply a chat template to
* A small, but good SFT model that has a chat template
The current script runs in about ~2' on a single node. The current set of hparams show margins going up / loss going down which is sufficient for a demo.
> Update KTO example with good dataset & chat format

- trl/trainer/model_config.py
the type hint forces a list which raises a "all-linear" layer not found. forcing a string makes it work. updating the type hint to `Union[str, list[str]]` also raise a parsing error
looks like peft handles this by making the arg a str and using comma delimited values 
https://github.com/huggingface/peft/blob/main/examples/sft/train.py#L30
> hackey update to ModelConfig to allow lora_target_modules="all-linear"

- examples/scripts/kto.py
- trl/models/utils.py
This PR tweaks the KTO example to use a small Qwen model that is better at following the chat template than the previous one. I've also added support for ChatML so users can align the base model directly.
> Update KTO example to use better model and ChatML support

- trl/trainer/orpo_trainer.py
torch.log1p is more accurate for smaller values
> [ORPO] use log1p for loss

- docs/source/dpo_trainer.mdx
The argument for the trainer is `ref_model` instead of `model_ref`
> Fix DPO Unsloth example in Docs

- docs/source/ppo_trainer.mdx
The usage of ppo_epochs is incorrect here. 
In https://github.com/huggingface/trl/blob/8534f0edf8608ad6bcbea9beefae380fa60ded77/trl/trainer/ppo_config.py#L104C8-L104C58
the ppo_epochs was described as the "Number of optimisation epochs per batch of samples". 
However, here it is used as the usual epoch number, in which you do one iteration over the training dataset.
> Correct ppo_epochs usage

- tests/test_rich_progress_callback.py
- trl/trainer/utils.py
Fix #1495 by modifying the RichProgressCallback.
- Corrected evaluation & prediction bebaviours,
- Handle object creation and release more cautious,
- Corrected the total steps of the evaluation progress bar.
> Fix `RichProgressCallback`

- trl/trainer/orpo_trainer.py
This PR updates how the NLL loss in ORPO is being calculated so as to use the `input_ids` for the chosen response i.e. the whole conversation, instead of only the labels i.e. the ids for the chosen response only.
As mentioned by @nlee-208, calculating the full prompt loss instead of solely the loss on the chosen response leads to better results in MT-Bench, leading then to a more faithful reproduction of the original codebase at https://github.com/xfactlab/orpo.git (see the screenshot shared by Noah below where the `wo-pl`, standing for without prompt loss, fine-tune performs worst on MT-Bench)
Kudos to @nlee-208, @jiwooya1000 and @lewtun
> [ORPO] Update NLL loss to use `input_ids` instead

- docs/source/sft_trainer.mdx
Small doc change, following up on https://github.com/huggingface/trl/pull/1520
> [DOC] Add data description for sfttrainer doc

- examples/scripts/vsft_llava.py
Fixes two things that were missing from the vsft script:
- Adds generation prompt to the Chat template
- Adds processor push to hub at end of script
> VSFT hotfix - adds gen prompt to template and processor to hub

- docs/source/ppo_trainer.mdx
This fixes the PPO documentation and replaces `PPOTrainer.save_model` with `PPOTrainer.save_pretrained`, as `save_model` does not exist. I ran the document's code to make sure the save function works. This discrepancy was noted in ticket #1443.
> save_model -> save_pretrained in ppo_trainer.mdx

- tests/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
In the PPOTrainer.generate function, the primary model was being used instead of the reference model to generate reference responses for single samples. This change uses the correct  model and introduces a test to check for this. The new test was failing with the previous codebase.
> Fixed ref model not used in PPO generation

- trl/trainer/sft_trainer.py
Fix the add_special_tokens issue as is mentioned in this issue: https://github.com/huggingface/trl/issues/1400
Fixes #1400
> fix add_special_tokens issue for data with template

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
add Binary Classifier Optimization (BCO) loss function from https://arxiv.org/abs/2404.04656
Implemented bce loss and reward shift in the paper.
I will make separate PR for unpaired version of BCO after rebase and polishing.
> [DPO] add 'bco_pair' loss_type

- docs/source/sft_trainer.mdx
- examples/scripts/sft.py
- examples/scripts/vsft_llava.py
- tests/slow/test_sft_slow.py
- tests/test_sft_trainer.py
- trl/__init__.py
- trl/commands/__init__.py
- trl/commands/cli_utils.py
- trl/trainer/__init__.py
- trl/trainer/sft_config.py
- trl/trainer/sft_trainer.py
Add a SFTConfig training argument dataclass together with deprecation warnings to the SFTTrainer
> [SFT] add SFT Trainer Config dataclass

- commands/run_dpo.sh
- commands/run_sft.sh
- docs/source/clis.mdx
- example_config.yaml
- tests/slow/testing_constants.py
- tests/test_cli.py
- tests/test_dpo_trainer.py
as per title
Pushed an updated tiny-llama that has the pad_token_id fixed to something different to -1, which caused issues on transformers main with errors such as:
```bash
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/transformers/generation/configuration_utils.py", line 669, in save_pretrained
raise ValueError(str([w.message for w in caught_warnings]))
ValueError: [UserWarning('`pad_token_id` should be positive but got -1. This will cause errors when batch generating, if there is padding. Please set `pas_token_id` explicitly by `model.generation_config.pad_token_id=PAD_TOKEN_ID` to avoid errors in generation, and ensure your `input_ids` input does not have negative values.')]
```
> FIX: Fix CI on transformers main 

- trl/commands/__init__.py
> Core: removed unexisting `SftArgumentParser`

- docs/source/kto_trainer.mdx
- examples/scripts/bco.py
- setup.py
- tests/test_kto_trainer.py
- trl/import_utils.py
- trl/trainer/kto_config.py
- trl/trainer/kto_trainer.py
add Binary Classifier Optimization (BCO) loss function from https://arxiv.org/abs/2404.04656
Implemented BCE loss, reward shift and underlying distribution matching.
Also added example script at `examples/scripts/bco.py`
> [`KTOTrainer`] add BCO (reward shift and underlying distribution matching)

- examples/scripts/chat.py
As a user of the chat CLI, I expect the model to be loaded on GPU by default instead of having to manually specify `--device "cuda"` 
I believe this can be achieved by simply setting `device_map="auto"` which will also work on CPU if the user should require it.
> [CLI] Use auto device map for model load

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_config.py
- trl/trainer/dpo_trainer.py
arxiv: https://arxiv.org/abs/2405.00675
> support loss function for Self-play Preference Optimization

- trl/models/utils.py
This PR incorporates a fix from @pacman100 to enable the `unwrap_model_for_generation()` context manager to work with other trainers like DPO. 
The basic issue with our original implementation is that we weren't removing all active parameters during the hook removal and this led to DeepSpeed errors like:
```
AssertionError: {'id': 0, 'status': 'AVAILABLE', 'numel': 25755648, 'ds_numel': 25755648, 'shape': (50304, 512), 'ds_shape': (50304, 512), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': {182}, 'ds_tensor.shape': torch.Size([3219456])}
```
Tested with this gist: https://gist.github.com/pacman100/a6c89a681f8f76bdf17f5bf6874eb983
cc @edbeeching you should rebase on `main` once this is merged so #1605 will work
Closes #1543
> Fix ZeRO-3 generation context manager

- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/orpo_trainer.py
The original implementation in DPO/CPO will add BOS and EOS token to a tokenized sequence regardless if its already there. This is problematic when using tokenizers (e.g., gemma-2b) whose chat template _already_ adds BOS/EOS token.
The change is therefore to simply check if the start/last token is already BOS/EOS, before adding it.
> fixed adding bos and eos token unconditionally

- trl/trainer/orpo_trainer.py
Recent [fix](https://github.com/huggingface/trl/commit/57aebe9c36021e679662181468b04ff42432daf3) for calculating NLL loss for a whole sequence introduced a bug. When input_ids are copied to labels, pad tokens are not masked.
This PR aims to patch this by masking labels based on the attention mask.
I've tested it with batch_size=1, and now the initial loss is correct.
> [ORPO] Correct label mask for pad tokens

- examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
- examples/research_projects/stack_llama_2/scripts/sft_llama2.py
SFTTrainer now takes a STFConfig argument
> Update sft_llama2.py to work with the latest API

- trl/trainer/utils.py
1. While the QLoRA repo https://github.com/artidoro/qlora/blob/7f4e95a68dc076bea9b3a413d2b512eca6d004e5/qlora.py#L395-L405 casts the trainable parameters to `bfloat16`(half-precision), this is incorrect and can lead to unstable training when using automatic mixed precision. Hence, this PR avoid casting the trainable params to half precision. This is inline with the changes we are making to fix this issue at https://github.com/artidoro/qlora/blob/7f4e95a68dc076bea9b3a413d2b512eca6d004e5/qlora.py#L395-L405
2. The impact of this PR would be increase in the GPU memory consumption as the trainable params are now in full precision.
> don't cast the trainable lora layers to half precision

- trl/trainer/ppov2_config.py
- trl/trainer/rloo_config.py
Hi, I get the following error when importing PPOv2Config
`TypeError: non-default argument 'output_dir' follows default argument`
Changing the order of inheritance in the class definition solves this problem.
> Fix inheritance order in PPOv2Config

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_config.py
- trl/trainer/dpo_trainer.py
- trl/trainer/utils.py
Implementation of the [TR-DPO](https://arxiv.org/pdf/2404.09656) method
> 🤫 TR-DPO implementation

- trl/trainer/sft_trainer.py
1. When using FSDP, all tensors need to be of the same type when it flattens them. As such, we need to avoid upcasting the adapter parameters.
> Do not upcast adapters when using FSDP+QLoRA

- docs/source/ppov2_trainer.md
- docs/source/rloo_trainer.md
- examples/scripts/ppo/ppo.py
- examples/scripts/ppo/ppo_tldr.py
- examples/scripts/ppo/ppo_zephyr.py
- examples/scripts/rloo/rloo.py
- examples/scripts/rloo/rloo_tldr.py
- examples/scripts/rloo/rloo_zephyr.py
- tests/test_ppov2_trainer.py
- tests/test_rloo_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/rloo_config.py
- trl/trainer/rloo_trainer.py
> Fix ppov2 test case

- trl/models/modeling_base.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
Fixes https://github.com/huggingface/trl/issues/1663
Adds the possibility to use `gradient_checkpointing` through a simple API (passing `gradient_checkpointing=True` in `PPOConfig`) + fixes the bug mentioned above.
cc @vwxyzjn
> FIX / PPO: Fix `enable_input_require_grads` issues with PPO models

- trl/trainer/kto_trainer.py
For encoder_decoder models the argument, `max_completion_length` is missing in the kto_trainer, leading to an error in [line 205](https://github.com/huggingface/trl/blob/1d0a7ea17b8055a6850970ab59a34709d8ca494d/trl/trainer/kto_trainer.py#L205).
> Fix max_completion_length for encoder_decoder models in KTO Trainer

- docs/source/dpo_trainer.mdx
- tests/test_dpo_trainer.py
- trl/trainer/dpo_config.py
- trl/trainer/dpo_trainer.py
from the paper: https://arxiv.org/pdf/2404.19733
> intial RPO loss

- trl/trainer/ppo_config.py
Removed the unneeded else branch and added a check to prevent both options being set at the same time
Fixes: #1689
> Fix overriding optimize_device_cache with optimize_cuda_cache in PPOConfig

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
This PR allows users to initialize an instance of the SFT Trainer with no formatting function / dataset_text_field, assuming `dataset_kwargs["skip_prepare_dataset"]` is truthy, for the case `packing=True`.
In support of: https://github.com/huggingface/trl/issues/1672
Fixes: https://github.com/huggingface/trl/issues/1672
> Skip packing validation

- examples/scripts/evals/generate_tldr.py
- examples/scripts/evals/gpt_tldr_judge.py
The `from vllm import SamplingParams, SingleGPULLM` was really from my own fork. This PR fixes it and makes it work with regular `vllm`.
> Quick fix on GPT4-eval

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
Fixes: https://github.com/huggingface/transformers/issues/31280
This PR makes sure users can still pass `TrainingArguments` to `SFTTrainer` without facing errors
cc @vwxyzjn @kashif
> SFTTrainer: Fix backward Compatibility issue with `TrainingArguments`

- docs/source/cpo_trainer.mdx
- tests/test_cpo_trainer.py
- trl/trainer/cpo_config.py
- trl/trainer/cpo_trainer.py
This PR adds a variant of CPO reference-free method, called SimPO (https://arxiv.org/abs/2405.14734). The only difference is SimPO adds a reward margin and does not use BC regularization. 
Thanks for your help and notice!
cc @kashif @lewtun
> Add a variant of CPO, SimPO

- trl/trainer/dpo_trainer.py
fixes the nll for RPO loss from #1686 and log it when `rpo_alpha` is not `None`
> [RPO] fix nll loss

- trl/commands/cli_utils.py
fixes #1712
reformatted cli_utils with ruff
> fix yaml parser for derived config classes

- trl/trainer/dpo_config.py
dpo_config default padding value should be None, not 0, otherwise it by default overrides the padding value of any tokenizer to 0
> Fix default padding_value in dpo_config.py

- docs/source/kto_trainer.mdx
- tests/test_kto_trainer.py
- trl/trainer/kto_trainer.py
> ktotrainer: Refuse datasets which contain only one class of labels

- trl/commands/cli_utils.py
- correctly overrides yaml config with command line arguments
do this by changing the defaults to values in the yaml so we get dataclass default < yaml config < command line arguments
- adds return_remaining_strings
- when return_remaining_strings is False, raises error if yaml contains extra args that are not in the dataclasses
- removes the need to have a `config` field in one of your dataclasses (I can revert this if this is preferred)
- simpler and cleaner than previous yaml parsing without the need for merging dataclasses 
Fixes #1733
@younesbelkada let me know if you have comments or suggestions!
> better trl parser with yaml config

- setup.py
- tests/test_best_of_n_sampler.py
TRL has an optional dependency with DeepSpeed which is right now not compatible with numpy >= 2.0.0
Related: https://github.com/microsoft/DeepSpeed/issues/5671
cc @vwxyzjn
> CI / core: Pin `numpy` to `!=2.0.0` for CI and to users

- trl/commands/cli_utils.py
https://github.com/huggingface/trl/pull/1739 introduced raising errors if users passed extra un-used arguments in the config file. Before that PR we were not raising errors and some users reported that it worked before on their setup (and might be convenient for some use-cases) we should re-enable that through a simple API `ignore_extra_args=True` when creating the `TrlParser`
cc @philschmid @mnoukhov @vwxyzjn
> `TrlParser`: Add ignore extra args option

- trl/trainer/cpo_config.py
I accidentally pushed the fix of the red CI on main. 
https://github.com/huggingface/trl/pull/1734 overrides `TrainingArguments` `__post_init__` method without returning `super().__post_init__()`. 
https://github.com/huggingface/trl/commit/4e23d958f20fd4fdd795cb06c2cdb7ebea704855 combined with this PR should make the CI happy
cc @kashif @vwxyzjn
> CPO / DPO: Fix red CI

- trl/trainer/ppov2_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/utils.py
`prepare_deepspeed` currently assumed `bf16`, this allows for bf16, fp16, or neither
> prepare deepspeed accomodate fp16 and bf16

- trl/trainer/ppo_trainer.py
Current handling of `response_masks` inside `batch_forward_pass` function does not take padding into consideration which results with shape unmatch during masking as stated in #1717. Response mask can directly be used for the masking operation instead of doing preprocessing such as concatenation.
Remove the concatenation of the response mask, remove the slicing from the response mask since response mask already has the length of `end - start`, which is equal to length of `masks[j, start:end]`.
Update the docstring for `masks` parameter under `_step_safety_checker` which is incompatible with the docstring under `step` function.
Fixes #1717
> Fix masking of response tokens

- examples/scripts/sft.py
When executing the command located at the top of [examples/scripts/sft.py](https://github.com/huggingface/trl/blob/34d273f227b30507c6d94ff1f93b6939794f38a3/examples/scripts/sft.py#L16), an error is thrown due to the `dataset_text_field` not being specified. I have added `"text"` as the `dataset_text_field` to align with the default dataset format used in timdettmers/openassistant-guanaco.
```shell
Repo card metadata block was not found. Setting CardData to empty.
/data/juyoung/.cache/pypoetry/virtualenvs/easylm--LeJdRf2-py3.11/lib/python3.11/site-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': model_init_kwargs. Will not be supported from version '1.0.0'.
Deprecated positional argument(s) used in SFTTrainer, please use the …
```
> Fix: Add dataset_text_field in examples/scripts/sft.py

- examples/datasets/sentiment_descriptiveness.py
Slightly more organized and uniform. Here, we assume the dataset always has a train and test split.
> New sentiment and descriptiveness dataset

- docs/source/cpo_trainer.mdx
- tests/test_cpo_trainer.py
- trl/trainer/cpo_config.py
- trl/trainer/cpo_trainer.py
This PR adds the following features:
1. Add an `cpo_alpha` to control the strength of the BC regularization.
2. Add the CPO-SimPO method (more details [here](https://github.com/fe1ixxu/CPO_SIMPO)). The difference between this version and the original SimPO implementation is that setting `loss_type="simpo"` with a non-zero `cpo_alpha` enables CPO-SimPO. If `cpo_alpha=0`, it defaults to the standard SimPO.
3. Highlight SimPO and CPO-SimPO in the `cpo_trainer.mdx`. We had multiple rounds of discussions with the SimPO authors, and we all agree it was an unintentional oversight. The SimPO method should be better highlighted within the CPO implementation.
More information:
1. [CPO-SimPO Github](https://github.com/fe1ixxu/CPO_SIMPO/tree/main)
2. …
> Add CPO-SimPO method

- docs/source/cpo_trainer.mdx
- docs/source/dpo_trainer.mdx
- docs/source/kto_trainer.mdx
- docs/source/orpo_trainer.md
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/orpo_trainer.py
This fixes #1544  
It optionally enables adding the load balancing loss (also aux_loss) of Mixture of Experts models in DPO, KTO, CPO or ORPO.
We are using this for a while now and in our experiments, the models that were fine-tuned using this option perform best at the moment. Maybe that applies to other project as well, so I wanted to open-source the idea and leave it to the users to enable it or not.  
This option is simply enabled by setting `output_router_logits=True` in the MixtralConfig and optionally scale it with `router_aux_loss_coef =...`(default is 0.001)
@kashif @lewtun
> MoE Models: option to add load balancing loss

- trl/trainer/sft_config.py
This PR addresses the issue of long URL causing text overflow in the documentation string for the SFTConfig class. By adding line breaks to long URLs and adjusting the formatting, the documentation is now more readable and properly contained within the text box.
> Fix Documentation Overflow Issues for Long URLs in SFTConfig

- docs/source/sft_trainer.mdx
'STFConfig' instead of 'SFTConfig' appears multiple times in the doc, causing error when running the correspondent code snippets.
> Fixed typo in SFT trainer docs

- examples/scripts/sft.py
Fix `SFTTrainer` warning by moving `model_init_kwargs` to the `SFTConfig`
> [SFT] add model_init_kwargs to training_args

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
This fixes a bug introduced in #1707, where if you create a `transformers.TrainingArguments` and pass it into `SFTTrainer`, you end up with `SFTTrainer.args.hub_token = "<PUSH_TO_HUB_TOKEN>"`, breaking the push-to-Hub functionality.
`TrainingArguments.to_dict()` redacts token fields ([transformers/src/transformers/training_args.py:2417](https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L2417)), so we have to individually copy them over when converting to SFTConfig to avoid breaking push_to_hub functionality.
To be clear, users can work around this bug by directly creating an `SFTConfig` rather than creating a `TrainingArguments` object, but strangely some tutorials mix and match them, so maintaining compatibility seems prudent.
This PR also adds a …
> Bugfix: Preserve token fields when converting TrainingArguments to SFTConfig

- trl/trainer/reward_trainer.py
`print_rich_table` is called twice and the first call doesn't restrict to `num_print_samples`. Remove the first, extra call
> Remove extra print in reward_trainer.py

- examples/scripts/dpo.py
- examples/scripts/sft.py
- examples/scripts/vsft_llava.py
- trl/commands/cli.py
- trl/env_utils.py
This PR fixes how the `TRL_USE_RICH` environment variable value is handled, since at the moment it cannot be disabled.
> [!WARNING]
> I'm not really happy with the current implementation since the `TRL_USE_RICH` environment variable is not used in the core, but it's used in the `examples/scripts` triggered via the CLI, which means that the same function needs to be used more than once and defining that once per file feels weird too. So would love your input here @vwxyzjn on what would be the best approach to ensure that the value is properly handled, but at the same time without adding noise to the codebase 😩 
Closes #1800
> Fix `TRL_USE_RICH` environment variable handling

- setup.py
- trl/__init__.py
> 0.9.6 release

- docs/source/index.mdx
Fixed a typo in `docs/source/index.mdx`. Should fix the broken link (https://huggingface.co/docs/trl/v0.9.4/en/text_environment) mentioned under [API documentation](https://huggingface.co/docs/trl/en/index#api-documentation).
It ain't much but it's honest work.
> Fixed the broken link to Text Environments doc in `docs\source\index.mdx`

- trl/models/modeling_base.py
The issue occurs when the following conditions are met
- we want to create any subclass of `PreTrainedModelWrapper` through the `from_pretrained` method
- the referenced model repository contains a Peft adapter
- the referenced model repository is private
The following things happen:
- the `adapter_config.json` gets downloaded using the token as authentication
since an adapter is present we
- instantiate and attempt to download the base model passing the token in the kwargs
- instantiate and attempt to download the PEFT adapter without passing the token
-> since the adapter repository is private, we're not able to load the adapter without passing the token. The `from_pretrained` method throws an error
We pass the token as a keyword argument when instantiating the PeftModel.
> Fix: authentication token kwarg not passed when loading PEFT adapters

- trl/trainer/ppov2_trainer.py
Tensorboard log fails because current code doesn't update global step.
- before:
- after this PR:
- test command
```
python examples/scripts/ppo/ppo.py \
--learning_rate 3e-6 \
--output_dir ./output \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 1 \
--total_episodes 100 \
--model_name_or_path Qwen2/Qwen2-0.5B-Instruct \
--non_eos_penalty \
--sft_model_path Qwen2/Qwen2-0.5B-Instruct \
--reward_model_path Qwen2/Qwen2-0.5B-Instruct \
--report_to tensorboard \
--local_rollout_forward_batch_size 1 \
--logging_strategy steps \
--logging_steps 1 
```
> fix ppov2_trainer tensorboard logging bug

- examples/scripts/chat.py
Fixes a small parsing issue introduced in https://github.com/huggingface/trl/pull/1739. The default config will be enforced by adding it to the `args`.
> fix arg parsing in chat.py

- examples/scripts/online_dpo.py
#1864 updated configs but missed a couple of changes.
> Small fixes to online dpo example

- tests/test_modeling_value_head.py
CI fails since https://github.com/huggingface/transformers/commit/6f40a213eb10e38a5f242d0645519d413d32d798
Caused by BigBird Pegasus, which does not support param buffer assignment. Fixed here: https://github.com/huggingface/transformers/pull/32222
Skip the test until we dumb to the next transformers version
> Skip BigBird save and load test until next transformers version

- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/utils.py
In [dpo_trainer.py](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L860), the `bos_token` will be  automatically added if the first token in current tokenized sentence is not equal to  `bos_token`. Currently this `bos_token` is read from tokenizer config file, but in some LLMs, like [Qwen2](https://huggingface.co/Qwen/Qwen2-7B-Instruct/blob/main/tokenizer_config.json), `bos_token` is leaving to `None` in config, which results in `None` is added to the input_ids tensor , as shown below:
and then the followiing trace will be raised when running dpo:
```
Traceback (most recent call last):
File "examples/scripts/dpo.py", line 185, in <module>
File "/usr/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
return …
```
> fix dpo_trainer bug for LLMs without bos_token in config

- trl/trainer/utils.py
This issue is related to PR #1869  
When training in a distributed setup, the collected count of the RunningMoments class ended up being a tensor, not an integer. This led to errors in json serializtion.  
This fixes the type of xs_count in distributed trainings.  
Previous fix (see https://github.com/huggingface/trl/pull/1869/commits/c22035049d857775ce6ba82763e82b934959064b) caused tests to fail and was therefore reverted by @kashif. Also @seanexp
> fix serialization of RunningMoments on multiple GPUs

- trl/trainer/online_dpo_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/rloo_trainer.py
https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
> `lr_scheduler.step()` after `optimizer.step()`

- trl/trainer/alignprop_trainer.py
- trl/trainer/ddpo_trainer.py
- trl/trainer/ppo_trainer.py
As of August 2, TRL model repos are no longer automatically tagged as `transformers` repos (previously this was inferred from the existence of a `config.json` file). 
This PR adds an explicit `library_name` tag to the TRL trainers that do not subclass `transformers.Trainer`. For all other trainers, the correct tag will be added via https://github.com/huggingface/transformers/pull/32623
cc @osanseviero
> Add transformers library name for TRL repos

- tests/test_trainers_args.py
- trl/trainer/bco_trainer.py
- trl/trainer/kto_config.py
minor fixes on top of #1869 :
- file name of running moments serialized object
- also save the logistic regression classifier (due to training the classifier on random samples, this is not always the same otherwise)
- remove deprecated parameters from KTOConfig
@kashif @seanexp
> minor BCO fixes

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/iterative_sft_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/sft_trainer.py
Some trainers don't tag the models when pushed to hub. This fixes it.
> Properly label all models when pushed to the hub

- trl/trainer/online_dpo_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/rloo_trainer.py
This PR fixes a small bug where tables of model completions were being logged on all processes.
> Log WandB tables on main process

- trl/trainer/online_dpo_trainer.py
This PR aligns the `global_step` to increment in the same way as the outer update loop. This ensures that the intermediate checkpoints align with the value set in `save_steps`.
The main impact of this change is that it affects the LR scheduler since the global step in incremented differently. See e.g. these two WandB runs:
* Without fix: https://wandb.ai/huggingface/huggingface/runs/t1v4qfj1?nw=nwuserlewtun
* With fix: https://wandb.ai/huggingface/huggingface/runs/sfebrzr6/overview
This subsequently affects the training dynamics, but I am unsure if the original implementation was actually correct or not wrt the global step.
Closes #1889
> [ODPO] Fix global step for consistent checkpointing with global updates

- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
When using the `precompute_ref_log_probs=True` option, the training process is halted( the training loss sucks at 0.6932 which shows the model is not training). This issue arises due to the following code segment:
```
if (
"reference_chosen_logps" in batch
and "reference_rejected_logps" in batch
and self.args.rpo_alpha is not None
):
reference_chosen_logps = batch["reference_chosen_logps"]
reference_rejected_logps = batch["reference_rejected_logps"]
```
The condition `self.args.rpo_alpha` is not None prevents the `reference_chosen_logps` and `reference_rejected_logps` from being used in the training process when `rpo_alpha` is set to None. This is problematic because when `precompute_ref_log_probs=True`, we still need to access these log probabilities from the batch regardless of the …
> Fix issue with precompute_ref_log_probs not working when rpo_alpha is None

- trl/trainer/dpo_trainer.py
This PR addresses an issue where unnecessary cache clearing was performed during the log probability calculation in the training loop. The original code included calls to `torch.cuda.empty_cache()` and `self.accelerator.free_memory()` to avoid out-of-memory (OOM) errors, but these were not necessary and may have introduced performance overhead. By removing these calls, this PR optimizes the memory management during training.
This change improves the efficiency of the log probability calculation during training by eliminating redundant memory management operations. This can lead to better performance and more efficient use of GPU memory.
Anyone in the community is welcome to review this PR once the tests have passed. Feel free to tag members or contributors who may be …
> Optimize DPO log probability calculation by retaining necessary cache, saving up to 30GB of memory (#1968)

- trl/trainer/kto_trainer.py
Fixes #1911
With the current `_get_kl_dataset` in [`kto_trainer.py`](https://github.com/huggingface/trl/blob/main/trl/trainer/kto_trainer.py) you can have this situation when the batch size is odd:
```python
from typing import Any, Dict, List
def _get_kl_dataset(batch: Dict[str, List[Any]]) -> Dict[str, List[Any]]:
"""Creates mismatched pairs of prompts and completions for the KL dataset by reversing the order of completions."""
batch["answer_input_ids"] = batch["answer_input_ids"][::-1]
batch["answer_attention_mask"] = batch["answer_attention_mask"][::-1]
return batch
input_ids = ["example_0", "example_1", "example_2"]
attention_mask = ["attention_mask_0", "attention_mask_1", "attention_mask_2"]
batch = {"answer_input_ids": input_ids, "answer_attention_mask": attention_mask}
kl_dataset = …
```
> New mismatch pair creation strategy

- trl/trainer/online_dpo_trainer.py
> Remove MPS

- trl/trainer/online_dpo_trainer.py
Needed to avoid a huge number of warnings in the logs
> Set KV cache false when gradient checkpointing is enabled

- docs/source/judges.mdx
- setup.py
- tests/test_judges.py
- trl/__init__.py
- trl/trainer/__init__.py
> Promote `PairRMJudge` to top-Level import

- trl/trainer/callbacks.py
> [DPO] TR-DPO gather the target model params as well when syncing

- .pre-commit-config.yaml
- examples/scripts/alignprop.py
- examples/scripts/ddpo.py
- examples/scripts/ppo.py
- examples/scripts/reward_modeling.py
- scripts/stale.py
- setup.py
- trl/extras/best_of_n_sampler.py
- trl/models/sd_utils.py
- trl/trainer/bco_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/rloo_trainer.py
update to the latest pre-commit ruff version and removed  jupyter from the list of allowed filetypes
> [pre-commit] update pre-commit yaml

- docs/source/sft_trainer.mdx
Document a famous package `Liger-Kernel` usage in SFT trainer page that can can effectively increase multi-GPU training throughput by 20% and reduces memory usage by 60%.
Reference: [Liger-Kernel](https://github.com/linkedin/Liger-Kernel/tree/main)
followup of: https://github.com/huggingface/transformers/pull/32860
> [Docs] Add Liger-Kernel usage to SFTTrainer page

- setup.py
Fix windows CI failures by pinning numpy version < 2
> [ci] pin numpy to < 2 on windows

- docs/source/kto_trainer.mdx
The "*" symbol in markdown doesn't show. I changed it to $\times$ so the mathematical formula is clearer
correct formatting of star sign in kto_trainer.mdx
- [X ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
> correct formatting of star sign in kto_trainer.mdx

- trl/trainer/sft_config.py
- trl/trainer/sft_trainer.py
> Fix `packing` doc in `SFTConfig` and fix error when neither `dataset_text_field` nor `formatting_func` is provided.

- trl/trainer/dpo_trainer.py
This PR fixes https://github.com/huggingface/trl/issues/2038.
Fix unpackaging error due to additional `aux_loss` returned by `concatenated_forward` function when `aux_loss_enabled=True`.
> fix: unpackaging error in Custom Mixture of Experts model when `aux_loss_enabled` is set to True.

- trl/trainer/kto_trainer.py
There is a bug in the following [few lines](https://github.com/huggingface/trl/blob/a20e8227375f53435a3457b33079ab690ff51496/trl/trainer/kto_trainer.py#L1327C9-L1328C78) of code in `kto_trainer.py`
```
logits_dict = {
"eval_logits/chosen": metrics["logits/chosen"],
"eval_logits/rejected": metrics["logits/rejected"],
}
logits = tuple(v.unsqueeze(dim=0) for k, v in logits_dict.items() if k not in ignore_keys)
logits = torch.stack(logits).mean(axis=1).to(self.accelerator.device)
```
This assumes that the values in the `logits_dict` are tensors, but they are not. These values are computed in `get_batch_loss_metrics` where the the logits are averaged and `.item()` is called on the resulting tensor to get a `float`.
This causes the following error when running a KTO training:
``` …
```
> Fix logits compuation in KTO trainer prediction step

- examples/scripts/dpo.py
- examples/scripts/dpo_visual.py
- examples/scripts/sft.py
- examples/scripts/vsft_llava.py
- trl/commands/cli.py
- trl/trainer/sft_trainer.py
This PR removes the `RichProgressCallback` from the example scripts because it (a) leads to very messy logs in distributed training, (b) produces hard-to-trace bugs like those encountered in #2043 and (c) introduces a lot of unnecessary branching logic to our scripts just for aesthetic purposes. It has also led to headaches in other libs like `accelerate` as noted in the issues below:
* https://github.com/huggingface/accelerate/issues/1630
* https://github.com/huggingface/accelerate/issues/765
* https://github.com/huggingface/transformers/issues/26085
See also this internal thread where `rich` interfered with cloud training: https://huggingface.slack.com/archives/C04EX6W3QSY/p1720008806136549
**Questions**
* Does this count as a breaking change since we are technically changing the …
> Remove `RichProgressCallback` from examples

- trl/trainer/online_dpo_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/rloo_trainer.py
remove the `min_new_tokens=args.max_new_tokens` from the generation configs of online methods.
remove un-needed masking
> [online models] remove min_new_tokens=args.max_new_tokens

- docs/source/kto_trainer.mdx
- examples/scripts/kto.py
- trl/trainer/kto_config.py
recommendation for the KTO learning rate to be small. See: https://x.com/ethayarajh/status/1834780782126153763
> [KTO] learning rate recomentations for kto

- tests/test_callbacks.py
- trl/trainer/callbacks.py
While training some models with `GKDTrainer` I ran into an issue with ZeRO-3 and `WinRateCallback` where the initial model provided by the callback is _unwrapped_ and this incompatible with `unwrap_model_for_generation()`. I also realised that using `eval_steps` is far more intuitive for both `WinRateCallback` and `LogCompletionsCallback` because we usually reserve logging for fast computations like the loss, and `LogCompletionsCallback` produces a major bottleneck in the logging if we generate every `logging_steps`.
This PR fixes both issues
members/contributors who may …
> Use wrapped model for reference completions in `WinRateCallback` and set default `freq` to `eval_steps` in LogCompletionsCallback`

- trl/trainer/kto_trainer.py
The calculation of the `logits/chosen` and `logits/rejected` metrics in `kto_trainer` seem to be wrong. A `nansum()` followed by `nanmean()` applied to the `policy_rejected_logits` is wrong.
Our fix is to apply `nansum()` followed by an other `nansum()` and then devide the result by `count/chosen` or `count/rejected`.
> [WIP] Fix `logits/chosen` and `logits/rejected` metrics in `kto_trainer`.

- trl/trainer/ppov2_trainer.py
> Fix deepspeed for `PPOv2Trainer`

- docs/source/cpo_trainer.mdx
- docs/source/gkd_trainer.md
- docs/source/nash_md_trainer.md
- docs/source/online_dpo_trainer.md
- docs/source/orpo_trainer.md
- docs/source/reward_trainer.mdx
- docs/source/sft_trainer.mdx
- docs/source/xpo_trainer.mdx
- examples/scripts/alignprop.py
- examples/scripts/bco.py
- examples/scripts/cpo.py
- examples/scripts/ddpo.py
- examples/scripts/kto.py
- examples/scripts/orpo.py
- examples/scripts/ppo.py
- examples/scripts/ppo/ppo.py
- examples/scripts/ppo/ppo_tldr.py
- examples/scripts/reward_modeling.py
- examples/scripts/rloo/rloo.py
- examples/scripts/rloo/rloo_tldr.py
- tests/slow/test_sft_slow.py
- tests/test_alignprop_trainer.py
- tests/test_callbacks.py
- tests/test_ddpo_trainer.py
- tests/test_dpo_trainer.py
- tests/test_iterative_sft_trainer.py
- tests/test_trainers_args.py
Let's use `training_args` for all instances of `TrainingArguments`
> Standardize `training_args`

- trl/trainer/kto_trainer.py
The function _process_tokens in trl/trainers/kto_trainer.py crashes if the prompt_input_ids are an empty list.
- added a check for nonzero length
- added a check for nonzero length of answer_input_ids for consistency
The checks happen when determining if 1 should be subtracted from max_length (happens when BOS/EOS is already present).
Fixes #2087
[documentation guidelines). (not needed?)
> Fixes #2087 -  _process_tokens for empty prompts in KTOTrainer

- trl/trainer/bco_trainer.py
- trl/trainer/kto_trainer.py
This is a continuation from #2077.  
For the logits metric: when logging, aggregate the sum and divide by final count. Do not divide earlier.  
Plus, this adds the same metric for BCO as well
@kashif @qgallouedec @PhilipMay
> KTO: fix logits metric, add logits metric to BCOTrainer

- examples/scripts/ppo/ppo.py
- examples/scripts/rloo/rloo.py
While debugging https://github.com/huggingface/trl/issues/1891, I noticed the PPO/RLOO examples do not work with DDP/ZeRO-3 due to having too small an evaluation dataset:
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/fsx/lewis/git/hf/trl/examples/scripts/rloo/rloo.py", line 131, in <module>
[rank1]:     trainer.train()
[rank1]:   File "/fsx/lewis/git/hf/trl/trl/trainer/rloo_trainer.py", line 474, in train
[rank1]:     self.generate_completions(sampling=True)
[rank1]:   File "/fsx/lewis/git/hf/trl/trl/trainer/rloo_trainer.py", line 496, in generate_completions
[rank1]:     query = batch["input_ids"]
[rank1]: TypeError: 'NoneType' object is not subscriptable
[rank4]: Traceback (most recent call last):
[rank4]:   File "/fsx/lewis/git/hf/trl/examples/scripts/rloo/rloo.py", …
```
> Fix PPO/RLOO examples

- examples/scripts/alignprop.py
- examples/scripts/bco.py
- examples/scripts/cpo.py
- examples/scripts/ddpo.py
- examples/scripts/dpo.py
- examples/scripts/dpo_online.py
- examples/scripts/dpo_visual.py
- examples/scripts/gkd.py
- examples/scripts/kto.py
- examples/scripts/nash_md.py
- examples/scripts/orpo.py
- examples/scripts/ppo/ppo.py
- examples/scripts/ppo/ppo_tldr.py
- examples/scripts/reward_modeling.py
- examples/scripts/rloo/rloo.py
- examples/scripts/rloo/rloo_tldr.py
- examples/scripts/sft.py
- examples/scripts/sft_vlm.py
- examples/scripts/xpo.py
- trl/trainer/alignprop_config.py
- trl/trainer/ddpo_config.py
- trl/trainer/utils.py
Standardise pushing to hub in the examples. Will help #2123.
adds
```python
trainer.save_model(training_args.output_dir)
if training_args.push_to_hub:
trainer.push_to_hub()
```
> Standardize pushing to Hub in examples

- examples/scripts/gkd.py
- tests/test_gkd_trainer.py
- trl/trainer/gkd_config.py
- trl/trainer/gkd_trainer.py
- trl/trainer/utils.py
This PR exposes aligns the `eos_token_id` attribute from `transformers.GenerationConfig` in GKD to support distillation of Llama 3 models which use special tokens `<|eot_id|>` and `<|eom_id|>` instead of the EOS token `<|endoftext|>` to indicate the end of a turn or message. We do this by checking the model's `generation_config` attribute and including the `eos_token_id` values in the GKD trainer's `GenerationConfig`.
> [GKD] Set custom EOS tokens in generation config

- tests/test_bco_trainer.py
- tests/test_dpo_trainer.py
- tests/test_kto_trainer.py
- tests/test_sft_trainer.py
This PR fixes the CI. 
https://github.com/huggingface/trl/actions/runs/11129906698/job/30928084389?pr=2131#step:5:4257
Example:
```
FAILED tests/test_sft_trainer.py::SFTTrainerTester::test_sft_trainer_uncorrect_data - ValueError: You have set `args.eval_strategy` to steps but you didn't pass an `eval_dataset` to `Trainer`. Either set `args.eval_strategy` to `no` or pass an `eval_dataset`.
```
> [CI] Don't use `eval_strategy="steps"` when no eval dataset

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/iterative_sft_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/ppov2_trainer.py
- trl/trainer/rloo_trainer.py
Fixes #2161
The next step is to make the same modification as in Transformers: #2162 
> 🩹 [Hotfix] Add setter for tokenizer

- trl/trainer/dpo_trainer.py
- trl/trainer/sft_trainer.py
For ref, all these args has been deprecated since v0.8.7 (DPO: #1554, SFT: #1530)
> 🗑️ Set deprecation version for DPO and SFT arguments to version 0.13

- docs/source/cpo_trainer.mdx
- docs/source/dataset_formats.mdx
- examples/scripts/cpo.py
- tests/test_cpo_trainer.py
- trl/data_utils.py
- trl/trainer/cpo_config.py
- trl/trainer/cpo_trainer.py
> Conversational dataset support for `CPOTrainer`

- docs/source/kto_trainer.mdx
- examples/scripts/kto.py
- trl/trainer/kto_config.py
- trl/trainer/kto_trainer.py
- change the default learning rate from 5e-7 to 1e-6; for models 7B and up (which is what most people use w/ or w/o LoRA), i this works better with the default beta=0.1 than an lr=5e-7, which can lead to slow learning
- add explanations in the docs on choosing the learning rate
- (important) change the batch size of the KL data to be the per-step batch size, not the effective batch size; the current implementation leads to worse results when gradient accumulation is used
- allow dropout to be used, like in DPOTrainer
cc @kashif @qgallouedec
> minor KTO setting changes + KL batch size

- docs/source/alignprop_trainer.mdx
- docs/source/bco_trainer.mdx
- docs/source/cpo_trainer.mdx
- docs/source/ddpo_trainer.mdx
- docs/source/dpo_trainer.mdx
- docs/source/gkd_trainer.md
- docs/source/iterative_sft_trainer.mdx
- docs/source/kto_trainer.mdx
- docs/source/nash_md_trainer.md
- docs/source/online_dpo_trainer.md
- docs/source/orpo_trainer.md
- docs/source/ppo_trainer.mdx
- docs/source/ppov2_trainer.md
- docs/source/reward_trainer.mdx
- docs/source/rloo_trainer.md
- docs/source/sft_trainer.mdx
- docs/source/xpo_trainer.mdx
If you don't select `trl` tag, you can get model from other lib. The most annoying case is PPO, which is widely used in standard rl. Check https://huggingface.co/models?other=ppo
> 🏷️ Model badges: select only TRL models

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/orpo_trainer.py
Fix the bug of aux_loss coefficient being 0 during training (#2197) in non-DPO trainers. The same update as #2200 is applied to the other trainers that support aux_loss.
@kashif @qgallouedec
> Fix the bug of aux_loss coefficient being 0 in BCOTrainer, CPOTrainer, KTOTrainer, and ORPOTrainer

- README.md
Added Command Line Interface (CLI) examples for SFT, DPO, and Chat features. Improved the "How to Use" section by providing code examples for SFTTrainer and RewardTrainer. Included installation instructions for both Python Package and source-based installation. Refined highlights to better showcase efficiency and scalability features. Updated the repository clone instructions for working with examples. Added new links to CLI documentation and contribution guide for better navigation.
> Updated README.md with CLI examples and additional usage instructions

- CONTRIBUTING.md
As I was looking to for the code linting commands for a pr, I was confused by what I think is missing linting commands. It looks like a bad copy/paste?
> Update commands for code linting in contributing guidelines

- trl/trainer/dpo_trainer.py
Currently,
1. removing unused column isn't supported
2. when not explicitly passing `--no_remove_unused_columns`, the following warning appears:
```
$ accelerate launch examples/scripts/dpo.py --output_dir Qwen2-0.5B-DPO --dataset_name trl-lib/lm-human-preferences-sentiment --model_name_or_path Qwen/Qwen2-0.5B-Instruct --logging_steps 10 --report_to none
/fsx/qgallouedec/trl/trl/trainer/dpo_trainer.py:720: UserWarning: When using DPODataCollatorWithPadding, you should set `remove_unused_columns=False` in your TrainingArguments. We have set it for you, but you should do it yourself in the future.
warnings.warn(
```
This PR adds support for removing unused columns, which resolves the warning.
|                                     | Before | After |
| ----------------------------------- | …
> DPO support `remove_unused_columns`

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/gkd_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/nash_md_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/xpo_trainer.py
follows https://github.com/huggingface/transformers/pull/34198
> 🔀 Rename `get_batch_sample` and add `num_items_in_batch` to `compute_loss`

- tests/test_callbacks.py
- trl/trainer/callbacks.py
> Use `processing_class` instead of `tokenizer` in `LogCompletionsCallback`

- tests/test_dataset_formatting.py
- trl/models/utils.py
Hi TRL team,
The context for this PR is from https://github.com/ggerganov/llama.cpp/pull/9778 . The user called `setup_chat_format` on base model `Llama-3.2-3B-Instruct`, which already has the llama-3.2 chat template. This will result in sub-optimal end result.
I believe it will be better to throw an error here, so that we don't overwrite chat template of the base model.
(feel free to edit this part)
> setup_chat_format: throw error if there is already a template in base model

- requirements.txt
- setup.py
We use `processing_class` instead of `tokenizer`. Consequently we need to bump the transformers min version to v4.46.
This PR will be merged after transformers v4.46 release.
> Bump the minimum transformers version to v4.46

- trl/trainer/orpo_trainer.py
Improves numerical stability and performance for ORPO loss computation. Use `F.logsigmoid(x)` to replace `torch.log(F.sigmoid(x))`.
> Replace log(sigmoid(log_odds) with logsigmoid(log_odds) for ORPO

- trl/trainer/bco_trainer.py
- trl/trainer/kto_trainer.py
This PR prepends `bos_token_id` only if it exists. Previously, KTO/BCO Trainer raise RuntimeError when `bos_token_id` is None and this hinders training models without `bos_token` (such as Qwen series models)
@kashif @qgallouedec @claralp
> [KTO/BCO Trainer] add bos_token_id only if it exists

- trl/trainer/nash_md_trainer.py
The initial version of KL divergence in NashMD Trainer had a bug: the gradient of the given KL estimate did not correspond to the actual stochastic gradient of KL divergence between the current policy and the reference policy. 
This PR intended to fix this issue by computing a REINFORCE-like estimate, taking into account that the current model generated the completion.
@kashif 
> Fix the computation of KL divergence loss in Nash MD

- trl/trainer/callbacks.py
(write with AI claude)
This PR improves type hints in the trainer callbacks by changing the parameter types of `num_prompts` and `freq` from `int` to `Optional[int]` to better reflect that these parameters can accept None values. This is a type annotation improvement with no functional changes.
Yes  (human response)
No, this is a minor type annotation improvement.
No documentation updates needed as this only affects type hints.
No new tests needed as this is only changing type hints.
Anyone familiar with Python type hints can review this PR. This is a straightforward type annotation improvement in the trainer callbacks.
> Update callbacks.py for fix small python type error

- docs/source/online_dpo_trainer.md
- examples/scripts/dpo.py
- examples/scripts/dpo_online.py
- examples/scripts/gkd.py
- examples/scripts/nash_md.py
- examples/scripts/reward_modeling.py
- examples/scripts/xpo.py
- tests/test_judges.py
- tests/test_nash_md_trainer.py
- tests/test_online_dpo_trainer.py
- tests/test_trainers_args.py
- tests/test_xpo_trainer.py
- trl/trainer/nash_md_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/xpo_trainer.py
This PR allows any reward model to be used with Online DPO, i.e. it removes the requirement to have the same chat template and tokenizer.
The user must now provide `reward_processing_class`.
```python
trainer = OnlineDPOTrainer(
model=model,
reward_model=reward_model,
train_dataset=train_dataset,
processing_class=tokenizer,
reward_processing_class=reward_tokenizer,  # <-
)
```
> Use any reward model for online methods

- CITATION.cff
- setup.py
- trl/__init__.py
- trl/trainer/judges.py
> ⏫ Bump dev version to `0.13.0.dev0`

- .github/workflows/tests.yml
For some tests, we don't use matrix. So you can't set the name with, eg, `Results with ${{ matrix.python-version }} on ${{ matrix.os }} with dev dependencies`
It doesn't fail but renders like this:
> 🪧 Fix slack notification titles

- trl/trainer/dpo_trainer.py
> Fix wrong truncating index of tensor in DPOTrainer's concatenated_forward()

- examples/scripts/dpo_online.py
- examples/scripts/nash_md.py
- examples/scripts/xpo.py
In the examples including xpo, nash_md, and dpo_online, `{"use_reentrant": True}` is assigned to `script_args.gradient_checkpointing_kwargs`. I have replaced `script_args` with `training_args` like other examples.
> Fix gradient_checkpointing_kwargs assignment in examples

- trl/models/modeling_value_head.py
Allows
```python
from trl import AutoModelForCausalLMWithValueHead
model = AutoModelForCausalLMWithValueHead.from_pretrained("THUDM/chatglm3-6b-128k", trust_remote_code=True)
```
Fixes #2299
> 🧞 Add `output_layer` to the list of `lm_head_namings` in `AutoModelForCausalLMWithValueHead`

- CONTRIBUTING.md
- docs/source/judges.mdx
- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/gkd_trainer.py
- trl/trainer/iterative_sft_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/nash_md_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/xpo_trainer.py
#2162 introduced a breaking change on all trainers except DPO and SFT (`tokenizer` arg replaced by `processing_class`. We've had feedback that this change was too abrupt, so we're reintroducing this argument with an extended timeline for its removal and also clarifying our removal strategy.
This PR will be part of a patch release for v0.12
Here is the proposed schedule depending of the usage for each trainer:
| Trainer       | Num models on the Hub | Argument removed in version |
| ------------- | --------------------- | ------------------- |
| SFT           | 15,097                 | 0.16                |
| DPO           | 3,053                 | 0.16                |
| PPO           | 441                   | 0.15                |
| ORPO          | 320                   | 0.15 …
> 👈 Add `tokenizer` arg back and add deprecation guidelines

- trl/trainer/bco_trainer.py
- trl/trainer/kto_trainer.py
The error text is saying:
> "Prompt input ids and answer input ids should have the same length."
This is very misleading. The code does not compare prompt and answer in this case.
> 🖨️ Fix error text in BCO and KTO tokenizing function

- tests/test_callbacks.py
- trl/trainer/callbacks.py
adds an option to use soft judges in win-rate callback and logs the results appropriately.
> ⚖️ Add `use_soft_judge` option to `WinRateCallback`

- trl/models/modeling_base.py
- trl/trainer/nash_md_trainer.py
When calling the GeometricMixture generation mixer, the model is left in eval mode.
> 🔮 Inference mode in `GeometricMixtureWrapper.forward`

- trl/trainer/ppo_trainer.py
- trl/trainer/rloo_trainer.py
- Use the specified `data_collator` instead of using hard-coded `DataCollatorWithPadding`
- When no `data_collator` is specified use `DataCollatorWithPadding` (previous behavior)
Fixes #2354 
> 🗃️ Use specified `data_collator` in `RLOOTrainer` and `PPOTrainer`

- examples/scripts/ppo/ppo.py
- examples/scripts/ppo/ppo_tldr.py
- tests/test_ppo_trainer.py
- trl/trainer/ppo_config.py
- trl/trainer/ppo_trainer.py
This PR provides an initial implementation of PEFT support for PPOTrainer, targeted towards the policy model. The existing functionality remains fully intact and unaffected by these modifications.
The following tasks have been completed:
- Add `peft_config` for `PPOTrainer`
- Add unit test for `tests/test_ppo_trainer.py` (next: implement unit tests to cover the new `peft_config` integration)
- Update `examples/scripts/ppo/ppo_tldr.py`
- Update `examples/scripts/ppo/ppo.py`
As of now, this implementation does not support **quantization** or **gradient checkpointing**.
If there’s anything inappropriate or suboptimal in my implementation, please feel free to let me know—I’m open to all feedback and eager to improve to align with the project standards.
Fixes #1916
to it …
> 📉 Add PEFT support for `PPOTrainer`

- trl/trainer/dpo_config.py
The description of the "generate_during_eval" parameter is incorrectly that of "truncation_mode" in the DPO config.
I aligned it with other similar trainer configs such as BCO or KTO.
> 📃 Fix description for parameter "generate_during_eval" in dpo_config 

- tests/slow/test_dpo_slow.py
- tests/slow/test_sft_slow.py
- tests/test_dpo_trainer.py
- tests/testing_utils.py
To avoid this warning in our tests:
```
../transformers/src/transformers/testing_utils.py:1163
/fsx/qgallouedec/transformers/src/transformers/testing_utils.py:1163: PytestUnknownMarkWarning: Unknown pytest.mark.bitsandbytes - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
return pytest.mark.bitsandbytes(test_case)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> 🧲 Use our own `require_bitsandbytes`

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/reward_trainer.py
Ignores the warning:
```
Could not estimate the number of tokens of the input, floating-point operations will not be computed
```
The floating-point operations remains not computed. Let's consider this as normal trainer operation (feature not available). In this respect, there's no need to issue a warning, which the user can't solve anyway.
```python
import tempfile
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import CPOConfig, CPOTrainer
model_id = "qgallouedec/tiny-Qwen2ForCausalLM-2.5"
model = AutoModelForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
with tempfile.TemporaryDirectory() as tmp_dir:
training_args = CPOConfig(
output_dir=tmp_dir, …
```
> 🙈 Suppress warning for estimating tokens in trainers

- docs/source/detoxifying_a_lm.mdx
- examples/scripts/ppo/ppo.py
- examples/scripts/ppo/ppo_tldr.py
- trl/trainer/ppo_trainer.py
> 👮 Deprecate `policy` in favor of `model` in `PPOTrainer`

- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/sft_trainer.py
I realized that the deprecation warnings were not displayed because the `deprecate_kwarg` function compares the version passed as an argument (for us it's the TRL version) with the **version of transformers**. And if this version is higher, then the message is not displayed. 
We could implement our own version of this decorator to use the TRL version (and not the transformers version), but the easiest way is to hack the function with the argument `warn_if_greater_or_equal_version`.
> 🤐 Fix deprecation warnings

- examples/scripts/sft_vlm_smol_vlm.py
Fixes #2408
This PR presents a standalone version for adding support to [SmolVLM models](https://huggingface.co/collections/HuggingFaceTB/smolvlm-6740bd584b2dcbf51ecb1f39). It may benefit from a generalization to be compatible with [sft_vlm.py](https://github.com/huggingface/trl/blob/main/examples/scripts/sft_vlm.py) (similar idea that for #2236)
@lewtun @edbeeching @qgallouedec
> 👁️ Added SFT support for `SmolVLM` models via standalone script `sft_vlm_smol_vlm.py`

- docs/source/sft_trainer.mdx
Sets best practice to avoid the footgun associated with special tokens in chat templates and LoRA SFT: https://x.com/_lewtun/status/1840804557800292843
> Add note about special tokens in chat templates for LoRA SFT

- tests/test_modeling_value_head.py
- trl/models/modeling_value_head.py
I don't know why we have this error.  Removing it doesn't induce any subsequent error. 
Fixes #2362
> 🔓 Remove lm_head check in `AutoModelForCausalLMWithValueHead`

- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
This PR provides a quick fix for issue #2403. Previously, DPOTrainer did not support LLaVA-Next because the required `image_sizes` parameter from the LLaVA-Next forward function was being removed during data processing within DPOTrainer. This update modifies DPOTrainer to retain the image_sizes parameter if it is returned by the image processor and passes it to the model when present.
While this fix resolves the issue on my end - I successfully ran DPOTrainer with LLaVA-Next - but it has not been extensively tested. I would appreciate assistance or guidance on the next steps to ensure broader compatibility and robustness.
Maybe @qgallouedec
> 🌋 Add support for LLaVA-Next in `DPOTrainer`

- tests/test_dpo_trainer.py
- trl/trainer/dpo_config.py
- trl/trainer/dpo_trainer.py
> 🧑‍🍳 Add precompute batch size argument in `DPOTrainer` for reference model

- trl/trainer/rloo_trainer.py
Fixes #2401 
I'm not entirely sure why it works but the problem is gone for varying batch size, rloo k, world size, grad accumulation step.
> 🧮 Fix `max_steps` calculation in `RLOOTrainer`

- setup.py
- trl/__init__.py
pins the transformers version to <4.47
fixes [#2445](https://github.com/huggingface/trl/issues/2445)
> Pin transformers version <4.47

- tests/test_utils.py
- trl/trainer/utils.py
Fixes #2449 
Fix DataCollatorForChatML unexpected generation prompt
DataCollatorForChatML will add generation prompt like `<|start_header_id|>assistant<|end_header_id|>` after model response, which is not suitable for instruction tuning, as is referred in #2449 
to it if that's the case.  https://github.com/huggingface/trl/issues/2449
[documentation guidelines](https://github.com/huggingface/trl/tree/main/docs).  Will do it afterwards if necessary.
> [bugfix] Fix DataCollatorForChatML unexpected generation prompt

- tests/test_ppo_trainer.py
- trl/trainer/ppo_trainer.py
> 🛠️ Update tests and fix PPO

- trl/scripts/utils.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_config.py
- trl/trainer/kto_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/utils.py
> ⚰️ Remove deprecated

- docs/source/index.mdx
This PR makes a small change to the prose of the link to smol course. I made the simpler for beginners to understand. 
cc @qgallouedec
> 🗣️ Improve prose for smol course

- trl/trainer/orpo_trainer.py
Calculate the ORPO chosen nll loss with respect to the chosen completion only rather than the whole prompt+compeletion.
Also return the shifted logits when the model is decoder only
> [ORPO] fix orpo chosen-nll loss

- tests/test_rloo_trainer.py
We don't test examples. We only test scripts (trl/scripts).
> ❎ Remove RLOO example test

- trl/trainer/dpo_trainer.py
Have a unique `_prepare_dataset` function.
Support for:
- DatasetDict for eval dataset
- Iterable datasets
> 👨‍🍳 Clarify DPO data preparation

- trl/trainer/bco_config.py
- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/gkd_config.py
- trl/trainer/gkd_trainer.py
- trl/trainer/kto_config.py
- trl/trainer/kto_trainer.py
- trl/trainer/online_dpo_config.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/prm_config.py
- trl/trainer/prm_trainer.py
- trl/trainer/reward_config.py
- trl/trainer/reward_trainer.py
> 💧 Generalize `disable_dropout`

- docs/source/dpo_trainer.mdx
- tests/test_collators.py
- trl/trainer/dpo_trainer.py
To keep consistency with `transformers.DataCollatorForLanguageModeling`
> 👬 Rename collator `PreferenceCollator` to ` DataCollatorForPreference`

- CONTRIBUTING.md
- tests/test_dpo_trainer.py
- trl/trainer/dpo_config.py
- trl/trainer/dpo_trainer.py
> 🏛️ Improve DPO configuration documentation structure

- tests/test_bco_trainer.py
- tests/test_cpo_trainer.py
- tests/test_dpo_trainer.py
- tests/test_kto_trainer.py
- tests/test_orpo_trainer.py
- tests/test_prm_trainer.py
- tests/test_reward_trainer.py
> 🪄 Minor comment style modif

- .github/workflows/issue_auto_labeller.yml
I was playing around with OpenAI API and was thinking about useful things we could do with the repos and all the data like issues and feedbacks and trying to automate some tasks or just do something useful with them like analysis or reports and I thought of an auto labeller.
This auto labeller uses OpenAI API, so it needs an `OPENAI_API_KEY` secret. It will cost a few bucks per month, but there are also string-based and regex-based labellers that may be faster.
If you are interested then we could test and see how consistent it is.
couple of ideas for improvement :
we could one-shot or few-shot prompt it for more accuracy or use different kinds of models both of which can cost more.
as for the speed, it takes about 30 seconds to label an issue.
any other ideas on anything useful we could …
> 🔖 Issues Auto-Labeller

- docs/source/rloo_trainer.md
- tests/test_rloo_trainer.py
- trl/trainer/rloo_config.py
- trl/trainer/rloo_trainer.py
Fixes the implementation of Token Level KL
Fixes #2562 and #2581
> [RLOO] fix token_level_kl

- CONTRIBUTING.md
- docs/source/reducing_memory_usage.md
- trl/trainer/bco_config.py
- trl/trainer/cpo_config.py
- trl/trainer/dpo_config.py
- trl/trainer/kto_config.py
- trl/trainer/online_dpo_config.py
- trl/trainer/orpo_config.py
- trl/trainer/prm_config.py
- trl/trainer/prm_trainer.py
- trl/trainer/reward_config.py
- trl/trainer/reward_trainer.py
Not truncating by default is a bad idea as it will lead to OOM in most cases.
Having one long sequence in a dataset is enough for causing an OOM.
> ✂️ Truncate by default

- docs/source/reducing_memory_usage.md
> 🎞️ Fix documentation SFT -`max_seq_length` instead of `max_length`

- tests/test_cli.py
CI has been recently failing with Python 3.9 due to
```
RuntimeError: Failed to import transformers.generation.streamers because of the following error (look up to see its traceback):
unsupported operand type(s) for |: 'type' and 'NoneType'
```
It's a python>3.10 syntax begin used in transformers. I'm not sure why it causes issue only with the CI but my feeling is that we can safely ignore it as it seems to be a pretty niche limitation (CLI under Python3.9)
If anyone has a fix, I would be happy to merge it though.
> 🫣 Ignore CLI test for Python 3.9

- tests/test_cli.py
> Fix merge error

- docs/source/installation.mdx
- setup.py
Adds uv install to the docs (see Slack [thread](https://huggingface.slack.com/archives/C01N44FJDHT/p1737377177709279) for more context)!
cc @lewtun
> ⚡ Add uv installation instructions

- trl/models/__init__.py
- trl/models/utils.py
- trl/trainer/grpo_trainer.py
```sh
accelerate launch --config_file configs/zero3.yaml src/open_r1/grpo.py \
--output_dir Qwen2.5-0.5B-GRPO \
--model_name_or_path Qwen/Qwen2.5-0.5B-Instruct \
--dataset_name AI-MO/NuminaMath-TIR \
--per_device_train_batch_size 2 \
--gradient_accumulation_steps 8 \
--logging_steps 10 \
--bf16
```
tested locally, it works!
> 👐 DeepSpeed integration for GRPO

- docs/source/grpo_trainer.md
- trl/trainer/grpo_trainer.py
When you've more than one reward func, you want to have the reward fo each one logged. Example:
```python
from trl import GRPOConfig, GRPOTrainer
dataset = load_dataset("trl-lib/tldr", split="train")
dataset = dataset.map(lambda x: {"ground_truth": x["completion"]}, remove_columns=["completion"])
def my_verifier(completions, **kwargs):
return [-len(completion) for completion in completions]
training_args = GRPOConfig(
output_dir="Qwen2-0.5B-GRPO",
logging_steps=2,
gradient_accumulation_steps=2,
max_prompt_length=64,
max_completion_length=32,
num_generations=4,
)
model="Qwen/Qwen2-0.5B-Instruct",
reward_funcs=[my_verifier, "trl-internal-testing/tiny-Qwen2ForSequenceClassification-2.5"],
) …
```
> 🔎 Finegrained reward logging for GRPO

- trl/trainer/grpo_trainer.py
Don't compute the logits of the prompt, to save memory
```python
import torch
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2.5-0.5B")
prompt_completion_ids = torch.randint(0, 100, (8, 256))
prompt_length = 100
completion_length = 156
def get_per_token_logps_prev(model, input_ids):
logits = model(input_ids).logits  # (B, L, V)
logits = logits[:, :-1, :]  # (B, L-1, V), exclude the last logit: it corresponds to the next token pred
input_ids = input_ids[:, 1:]  # (B, L-1), exclude the first input ID since we don't have logits for it
per_token_logps = []
for logits_row, input_ids_row in zip(logits, input_ids):
log_probs = logits_row.log_softmax(dim=-1)
token_log_prob = torch.gather(log_probs, dim=1, …
```
> 📉 Use `num_logits_to_keep` to reduce memory usage in GRPO

- setup.py
When building the package:
```bash
$ python -m build
...
/tmp/build-env-kw_0huok/lib/python3.11/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'trl.templates' is absent from the `packages` configuration.
!!
********************************************************************************
############################
############################
Python recognizes 'trl.templates' as an importable package[^1],
but it is absent from setuptools' `packages` configuration.
This leads to an ambiguous overall configuration. If you want to distribute this
package, please make sure that 'trl.templates' is explicitly added
to the `packages` configuration field.
Alternatively, you can also rely on setuptools' discovery methods
(for example by using …
```
> 📦 `trl.templates` in excluded packages

- CONTRIBUTING.md
The link labeled "Good First Issue" in the documentation is broken—it currently points to a non-existent page.
I've updated it to the correct URL, which should now direct users to the appropriate issues page.
This should help contributors find suitable issues more easily.  
**Changes:**  
- Updated the "Good First Issue" link from `https://github.com/huggingface/trl/contribute` to `https://github.com/huggingface/trl/issues`.  
Anyone
> docs: Fix broken "Good First Issue" link in CONTRIBUTING.md

- tests/test_trainers_args.py
- trl/trainer/dpo_config.py
- trl/trainer/orpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/reward_trainer.py
> ☠️ Remove deprecated

- tests/test_grpo_trainer.py
- trl/trainer/grpo_trainer.py
overwrite the prediction_step in the trainer to log the eval loss.
> 📋 Add eval loss logging during prediction in GRPO

- README.md
> Improve GRPO example

- docs/source/learning_tools.md
I noticed a mistake in the calculation of Olivia's remaining money.
Previously, it was incorrectly calculated that Olivia had $10 left after buying baguettes. However, if she spent $3 on each of the 5 baguettes, she spent a total of $15. Since she initially had $23, the correct remaining amount is $8.
I've updated the logic to reflect this.  
Anyone
> 💰 Fix incorrect calculation in Olivia's baguette spending logic

- examples/datasets/ultrafeedback-prompt.py
A typo in the filename where "ultra" was misspelled as "ulta" (missing the letter "**r**").
Fixed ultafeedback-prompt.py → **ultrafeedback-prompt.py**
Anyone
> fix: Fix typo in filename in ultrafeedback-prompt.py

- docs/source/logging.md
Noticed a typo in the alias descriptions: "sed" should be "used".
Fixed both occurrences to improve clarity.
Anyone
> docs: Fix typos in alias descriptions

- tests/test_grpo_trainer.py
- trl/trainer/grpo_trainer.py
Fix a small yet dangerous issue -- not adding `attention_mask` when computing logits.
Will add more notes.
```python
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2.5-Coder-0.5B", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-Coder-0.5B")
prompts = [
"hello, 1 + 1 = ?",
"hello, 12781297598217521580 + 120481209481290482 = ?",
]
prompt_inputs = tokenizer(
prompts, return_tensors="pt", padding=True, padding_side="left", add_special_tokens=False
).to(model.device)
generation_config = GenerationConfig(
max_new_tokens=100,
do_sample=True,
temperature=0.2,
num_return_sequences=4,
pad_token_id=tokenizer.pad_token_id,
)
prompt_completion_ids = model.generate(
**prompt_inputs, …
```
> ⚠️ Fix Attention Masking in GRPO

- setup.py
Fixes #2745 by ensuring minimum vllm version.
> 📌  vLLM >= 0.7.1 for device fix

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
Adds datatype argument for vllm in grpo Trainer/Config,
T4 in collab need fp16 and vllm defaults to bf16 :)
@qgallouedec
> 📐 Add vLLM dtype configuration for GRPO trainer

- docs/source/logging.md
- tests/test_grpo_trainer.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
when using torch compile, there is one more layer to unwrap before we can send the state dict to vlllm
> 🤖 Properly unwrap torch.compile-ed models in GRPO

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
By default, the vLLM model will be set up to support the max context of the input model.
However, during training we know we will only observe at most max_prompt_length + max_completion_length tokens, so we can use that to have a reduced memory footprint.
This is especially relevant when running on limited hardware as the improvement in memory can be significant.
> ↔️  GRPO: Set max_model_len when initializing vLLM instance

- trl/trainer/grpo_trainer.py
`GRPOTrainer` uses a method `_get_per_token_logps` to compute the per-token logprobs for every token in the input sequence. However, it uses `seq_len * vocab_size` additional memory in order to compute log_softmax, generating full log-probabilities for every possible token in the vocabulary at every index in the sequence. The next step then selects only the the actual input tokens to get the per-token logprobs for the input sequence.
This can be made more efficient by performing the selection first to get per-token logits, computing the softmax denominator (a reduction over the full set of logits), and then directly computing the logits only for the relevant tokens. This requires only `seq_len` additional memory.
NA but I'm happy to file an issue if needed
Pull Request …
> 💡  GRPO vram-efficiency improvement; only compute relevant logprobs

- docs/source/grpo_trainer.md
- tests/test_cli.py
- tests/test_grpo_trainer.py
- trl/models/utils.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
In the current implementation of GRPO, each device samples `N` prompts. For these `N` prompts, `G` generations are produced, and the loss is computed over them. However, this approach is highly memory-intensive, especially when using `G ≥ 8`, often leading to OOM errors, even with a batch size of just 1 prompt per device.
This PR introduces a more flexible approach:  
- Instead of defining `per_device_batch_size` as the number of prompts per device, it now represents the **number of generations per device**.  
- This allows for much greater flexibility in choosing the number of generations (`G`) and the batch size per device.  
- The only constraint is that the global batch size (`num_processes * per_device_batch_size`) must be divisible by `G`.
Note that these settings should be …
> 📉 Optimize GRPO memory usage by redefining `per_device_batch_size` as generations per device

- trl/trainer/grpo_trainer.py
move the model load to vllm to its own protected method. I've got a follow on PR to handle moving PEFT models to vllm, but this makes it cleaner/easier
> 📤 GRPO refactor loading the model weights to vllm

- trl/trainer/grpo_trainer.py
Fixes the issue described in https://github.com/huggingface/trl/pull/2776#issuecomment-2649053292
> 🫘 Add `set_seed()` call in GRPO to ensure unique seed for each process

- trl/trainer/grpo_trainer.py
This pull request fixes a bug in the code where an extra `len` call in the `ValueError` message caused a `TypeError` to be thrown instead of the expected `ValueError`. The issue arises when checking the length of `args.reward_weights` against `reward_funcs`.
---
The original code contains an unnecessary nested `len` call:
```python
len(len(args.reward_weights))
```
This results in a `TypeError: object of type 'int' has no len()`, because `len(args.reward_weights)` returns an integer, and integers cannot be passed to `len()`.
[Here (grpo_trainer.py#L278)](https://github.com/huggingface/trl/blob/7347c292c3d18ff9209ad745ede6fce7e3b94155/trl/trainer/grpo_trainer.py#L278) is the problematic code:
```python
if args.reward_weights is not None:
if len(args.reward_weights) != len(reward_funcs): …
```
> 🪆 Fix for Incorrect ValueError Handling in reward_weights in grpo_trainer.py

- tests/test_grpo_trainer.py
- trl/trainer/grpo_trainer.py
unlocks PEFT + GRPO + vllm without the complexity of shipping lora weights to vllm via the REST API. This implementation simply merges the lora weights into the base model and ships that to vllm using the existing python API.
> 👨‍👩‍👧 GRPO + PEFT + vLLM

- setup.py
- trl/trainer/sft_trainer.py
Covers the edge case when an AutoLigerKernelForCausalLM is passed to the SFTTrainer and use_liger is the default
fixes https://github.com/linkedin/Liger-Kernel/issues/568
> [SFT] fix check for AutoLigerKernelForCausalLM

- setup.py
Bumps vllm as there were a number of throughput improvements in vllm==0.7.2
Also may resolve issues such as https://github.com/huggingface/trl/issues/2851
> 🆙 Bump vLLM min version to 0.7.2

- trl/trainer/grpo_trainer.py
The `state_dict` obtained from the PEFT model seems to be a shallow copy of model weights.
Therefore, if we `unmerge` the model before generation, the weights are "rolled-back" to the base weights without the adapter.
I move the unmerge operation to the end of generation.
Fixes #2856  (issue)
> 🧶 [GRPO][vLLM + LoRA] Move unmerge of PEFT model after weight loading

- trl/trainer/grpo_trainer.py
Adds an optimization of vllm batching by using `n=num_generations` in the vllm `SamplingParameters`.
@qgallouedec I looking at some examples in the debugger and the ordering of the gathered prompts always seems to be always `[num_generations] * [num_prompts]` but I am concerned there could be edge cases where this is not the case, what do you think?
> Optimize vllm num_generations

- trl/scripts/env.py
```
$ trl env
[2025-02-24 10:22:41,365] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Copy-paste the following information when reporting an issue:
- Platform: Linux-5.15.0-1048-aws-x86_64-with-glibc2.31
- Python version: 3.12.2
- TRL version: 0.16.0.dev0+5975879
- PyTorch version: 2.2.2
- CUDA device(s): NVIDIA H100 80GB HBM3
- Transformers version: 4.47.0
- Accelerate version: 1.2.1
- Accelerate config: not found
- Datasets version: 3.2.0
- HF Hub version: 0.25.0
- bitsandbytes version: 0.45.0
- DeepSpeed version: 0.16.3
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: 0.13.2
- vLLM version: not installed
``` …
> 📋 Add vLLM version to environment printout

- trl/trainer/sft_trainer.py
Fixes an issue where `use_liger=True` threw an error in the loss computation because the fix in #2874 was partially reverted in [this line](https://github.com/huggingface/trl/pull/2890/files#diff-67e157adfcd37d677fba66f610e3dfb56238cc550f221e8683fcfa0556e0f7caR180) of #2890. Without this change, one gets errors on the loss computation
```
[rank0]:     shift_logits = outputs.logits[..., :-1, :].contiguous()
[rank0]:                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
[rank0]: TypeError: 'NoneType' object is not subscriptable
```
Command to test:
```shell
trl sft --model_name_or_path Qwen/Qwen2.5-0.5B     --dataset_name trl-lib/Capybara     --output_dir Qwen2.5-0.5B-SFT --use_liger true
```
[documentation …
> 🐯 Fix LigerKernel for SFTTrainer

- README.md
- docs/source/index.md
- setup.py
- Add Open-R1 blog post in the index page of the doc
- Reorganise README/Doc to highlight our top trainers (SFT, GRPO, DPO, Reward)
- Drop some old content
> 📜 Update README and doc index

- trl/trainer/grpo_trainer.py
Fixes #2953
I couldn't reproduce myself the bug, but numerous users reported that it solved the issue. AFAIK `no_grad` and `inference_mode` are mostly equivalent. The rule of thumb from the torch forum whose ref I no longer have is to prefer inference mode, and if it raises an error use no grad.
> 🛣️ `inference_mode` to `no_grad` when computing `old_per_token_logps`

- trl/data_utils.py
`apply_chat_template` is a method of `PreTrainedTokenizerBase`, so we can be slightly looser on the type hint here
> 🗜️ Loosened tokenizer type hint on `apply_chat_template`

- trl/models/utils.py
Fixes https://github.com/huggingface/trl/issues/2962
> 🚀  Supporting `deepspeed>=0.16.4`'s rename

- trl/trainer/grpo_trainer.py
It fixes the temperature scaling omission when computing the model's and reference model's log probabilities, potentially causing highly biased policy gradients.
This should be consistent with other TRL implementations as PPO and RLOO.  Omitting this term has been evidenced to potentially cause detrimental instabilities when fine-tuning LLMs with RL (e.g., [see here](https://huggingface.co/blog/the_n_implementation_details_of_rlhf_with_ppo)). Consistently with these results, using my own custom implementation after this fix also seems to work better. I tried doing additional research, but I could not find references that mention purposefully biasing the optimization leads to benefits... am I missing something?
[documentation …
> 🌡️ Fix temperature inconsistency in GRPO trainer

- trl/trainer/grpo_trainer.py
If you use a custom EOS token in the tokenizer input to `GPROTrainer`, it won't be used in generation.
The `GPROTrainer` code already passes the pad token ID, now it passes the BOS and EOS token IDs too.
> 🏁 Passing custom BOS/EOS token to `GPROTrainer.generation_config`

- tests/test_gkd_trainer.py
- trl/trainer/gkd_trainer.py
This PR fixes the JSD loss computation in GKDTrainer.
The issue was in following code:
https://github.com/huggingface/trl/blob/e3244d2d096ff1e2e248c931d06d39e165e20623/trl/trainer/gkd_trainer.py#L192-L204
This code snippet from the main branch computes the mixture distribution as per `beta*student + (1-beta)*teacher`; however, the definition is `beta*teacher + (1-beta)*student`. This small change fixes the loss equation, but for `beta = 0` and `beta = 1`, the loss becomes 0 (which is, by definition, correct). Therefore, for the correct behaviour of the loss, we need to handle these edge cases separately and compute KL(teacher || student) when `beta = 0` and KL(student || teacher) when `beta=1`.
This also needed a change in the JSD loss tests since the expected loss was calculated wrongly …
> Fixing JSD loss computation in GKDTrainer as per definition

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
allow setting the cache_implementation for GenerationConfig in the GRPO Trainer for faster generation via Transformers
> 🫣 [GRPO] add cache_implementation option in GRPO

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
> ⛔ Add EOS token to processed input in SFT

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/prm_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/sft_trainer.py
This PR fixes a race condition that arises in our trainers when they are run on >16 nodes, for example:
```
[ip-26-0-160-242:0]:Converting train dataset to ChatML:  98%|█████████▊| 40000/40665 [00:15<00:00, 2123.26 examples/s][ip-26-0-160-242:0]:
[ip-26-0-161-142:0]:
[ip-26-0-161-142:0]:Applying chat template to train dataset:   1%|          | 335/40665 [00:00<00:12, 3297.59 examples/s][ip-26-0-161-142:0]:
[ip-26-0-161-142:0]:Applying chat template to train dataset:   2%|▏         | 825/40665 [00:00<00:09, 4231.38 examples/s][ip-26-0-161-142:0]:
[ip-26-0-161-142:0]:Applying chat template to train dataset:   4%|▎         | 1466/40665 [00:00<00:13, 2930.79 examples/s][ip-26-0-161-142:0]:
[ip-26-0-161-142:0]:Applying chat template to train dataset:   5%|▍         | 1953/40665 [00:00<00:11, …
```
> Use main process for dataset.map

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
According to [DAPO](https://arxiv.org/abs/2503.14476) paper training detail, setting the upper_bound epsilon will result in higher entropy for the generation. Therefore, we added this feature to the default GRPO trainer!
> 🎬 Clip higher

- .github/workflows/pr_style_bot.yml
- docs/source/data_utils.md
- tests/test_data_utils.py
- trl/__init__.py
- trl/data_utils.py
- trl/trainer/sft_trainer.py
Adds fast packing/truncation logic that operates directly on PyArrow arrays to avoid expensive Python-to-PyArrow and PyArrow-to-Python conversions. This makes these steps almost instantaneous regardless of the input dataset's size. 
> ⚡ Pack 300 times faster, truncate 100 times faster

- setup.py
- tests/testing_utils.py
- trl/import_utils.py
- trl/trainer/bco_trainer.py
This PR fixes to some issues that I identified with the BCOTrainer on the latest version upgrade:
- remove extra shuffles, super class already handles data shuffling. These destroy training reproducibility
- fix serialization of UDM classifier, not all parameters were saved previously
- accelerate.gather not hanging on empty lists anymore
- convert delta to tensor before logsigmoid, this led to numeric errors
- do not update delta value in eval mode
Let me know if you have any questions
[documentation guidelines](https://github.com/huggingface/trl/tree/main/docs). - changes do not affect docs
@kashif @qgallouedec
> BCOTrainer version upgrade fixes

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
- trl/trainer/utils.py
This PR exposes a `num_completions_to_print` arg in the `GRPOConfig` so that users can control how many completions are printed to the terminal. I found the default (log everything) made the logs very verbose / large.
After discussing with @edbeeching I decided not to expose this for WandB since there we don't have to worry about the logs becoming overloaded.
> Enable number of printed completions to be set

- trl/scripts/vllm_serve.py
It solves two warnings:
```
[rank0]:[W325 17:16:26.189312881 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```
and 
```
WARNING 03-25 17:11:56 [worker_base.py:561] passing worker_cls as a class object is strongly deprecated, as the serialization of class objects can be tricky and error-prone. To be safe, please keep the class in a separate module and pass the qualified name of the class as a string.
```
> 👨‍🍳 vLLM serve: destroy process group on exit and pass `worker_cls` as string

- trl/trainer/grpo_trainer.py
Below, let me briefly explain my motives and reasons, the code mainly uses the part marked in the figure.
if (coef_1 < (1 - self.epsilon_low) and advantage > 0) or (coef_1 > (1 + self.epsilon_high) and advantage < 0)
then coef_1 * advantage < (1 - self.epsilon_low) * advantage
coef_1 * advantage < (1 + self.epsilon_high) * advantage
min(per_token_loss1, per_token_loss2) = per_token_loss1
**From the perspective of loss, it is actually not clipped.**
`clip_ratio = (is_clipped * completion_mask).sum() / completion_mask.sum()`
**And this code also calculates an effective clip_ratio**       
**original code:** `is_clipped = (coef_1 < (1 - self.epsilon_low)) | (coef_1 > (1 + self.epsilon_high))`
**Therefore, we must combine the sign of the advantage with the original code to calculate …
> 📎 Fix is_clipped to compute the effective clip_ratio

- docs/source/reducing_memory_usage.md
Small fix to docs page because reference is incorrect: 
~flash_attention2~ > flash_attention_2
> Fix breaking typo for flash_attention reducing_memory_usage.md

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
For GRPO we generate N completions per prompt which can make it hard to navigate the table of completions in WandB. This PR exposes a `wandb_log_unique_prompts` which shows just one completion per prompt and is useful when trying to compare the diversity of responses in a single batch.
> Show unique prompts in GRPO WandB tables

- docs/source/grpo_trainer.md
- trl/trainer/grpo_trainer.py
- Adds min, mean and max logging of completion lengths
- Also logs min, mean, max completion logs for sequences that terminate in EOS
- Adds clipped completion ratio from [SimpleRL-Zero](https://arxiv.org/pdf/2503.18892)
Example:
> [GRPO] Improve completion length logging

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
This PR fixes a bug where the `rich` and `wandb` tables were not logging the complete set of unique prompts for `gradient_accumulation_steps > 1`. Previously what happened is that the tables we logged for each gradient accumulation step, which is confusing when inspecting the logs for unique prompts.
Here's two runs with/without the fix for:
* `main`: https://wandb.ai/huggingface/huggingface/runs/j3vwwb5t/workspace?nw=nwuserlewtun
* `this_pr`: https://wandb.ai/huggingface/huggingface/runs/78q63hev/overview
These runs have:
* `gradient_accumulation_steps=4`
* `num_generations=16`
* `per_device_train_batch_size=4`
* `num_gpus = 8`
so we expect `num_unique_prompts=8`:
```
num_unique_prompts = num_gpus * per_device_train_batch_size * gradient_accumulation_steps / num_generations = 8
```
We …
> 📚 Accumulate completions for logging

- docs/source/grpo_trainer.md
- trl/trainer/grpo_trainer.py
Aligns the completions metrics to be grouped with the same prefix (like we do for rewards). This makes it easier to get an overview in WandB because the metrics get grouped in different sections:
> Group completion metrics by common prefix

- trl/trainer/online_dpo_trainer.py
> [!IMPORTANT]
> This PR is on `release v0.16` branch!
This PR addresses a breaking change introduced in the `transformers` dev branch: https://github.com/huggingface/transformers/pull/36973. This was fixed in the `trl` main branch with #3176, but this fix is not part of TRL 0.16, which could cause issues once transformers new release goes live. To prevent this, we will release v0.16.1, which includes a fix.
By releasing this patch ahead of the upcoming `transformers` release, users will avoid potential bugs caused by the breaking change in `transformers` dev branch. This ensures that `trl` remains compatible with the new `transformers` version as soon as it's released.
This breaking case was reported thanks to this CI: https://github.com/huggingface/trl/actions/workflows/tests_latest.yml
> 📉 Add `learning_rate` argument to `_maybe_log_save_evaluate`

- trl/trainer/grpo_trainer.py
This PR fixes a confusing error message when users try to use `num_generations=1` with the GRPO trainer.
**Current Message:**
`ValueError: The global train batch size (1 x 4) must be evenly divisible by the number of generations per prompt (1). Given the current train batch size, the valid values for the number of generations are: [2, 4].`
This is mathematically incorrect since 1 is a valid divisor of any number, and confused me in the beginning. The real issue is that GRPO requires at least 2 generations to function properly.
**Changes**
Just raise a ValueError if `num_generations<2` with a more informative message.
> 📢 Improve GRPO trainer error message for invalid num_generations

- trl/trainer/grpo_trainer.py
> 🌊 Add error for iterable datasets in GRPOTrainer

- trl/trainer/grpo_config.py
Adds dict parsing logic to `model_init_kwargs` in `grpo_config`, enabling dynamic configuration via CLI. Users can now pass dictionary-like strings (e.g., `--model_init_kwargs '{"torch_dtype":"bfloat16"`) through command-line arguments, which are automatically parsed into Python dicts for the target fields.
Logic is the same as [TrainingArguments](https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L226).
> ⛏️ Add cli dict parsing for grpo_config

- trl/import_utils.py
- trl/scripts/env.py
- trl/trainer/grpo_trainer.py
- trl/trainer/kto_trainer.py
From @lewtun 
> FYI I just install `trl@main` and got this from trying to run GRPO:
> 
> ```
> Traceback (most recent call last):
>   File "/fsx/lewis/git/hf/dev/open-r1/openr1/bin/trl", line 4, in <module>
>     from trl.cli import main
>   File "/fsx/lewis/git/hf/dev/open-r1/openr1/lib/python3.11/site-packages/trl/cli.py", line 24, in <module>
>     from .scripts.grpo import make_parser as make_grpo_parser
>   File "/fsx/lewis/git/hf/dev/open-r1/openr1/lib/python3.11/site-packages/trl/scripts/grpo.py", line 22, in <module>
>     from trl import GRPOConfig, GRPOTrainer, ModelConfig, ScriptArguments, TrlParser, get_peft_config
>   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
>   File "/fsx/lewis/git/hf/dev/open-r1/openr1/lib/python3.11/site-packages/trl/import_utils …
```
> 🐯 `is_liger_kernel_available` with min version

- trl/trainer/online_dpo_trainer.py
This pull request fixes the issue described in https://github.com/huggingface/trl/issues/3063 by implementing the solution also proposed in the original issue.
Essentially, we now check whether the model is an encoder-decoder model at initialisation and store it in self. This avoids a check during training when the model may have been wrapped in a DataParallel object. 
Fixes https://github.com/huggingface/trl/issues/3063
> 🕷 Fix online DPO crash when model is a DataParallel object

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
Adds an option to disable dropout. 
The RLOOTrainer disables dropout in policy, ref_model and reward model. This PR adds the option to disable dropout to the GRPOTrainer, which may improve training stability. 
[The N+ Implementation Details of RLHF with PPO: A Case Study on TL;DR Summarization](https://arxiv.org/pdf/2403.17031)
Provides more insight about why this option may improve training stability:
> We disable the dropout layers during training, similar to the settings in Ziegler et al. (2019); Huang
et al. (2024). This is important for PPO training, especially because with dropout activated, the log
probabilities of tokens will not be reproducible, making calculating the KL penalty unreliable while
also causing the ratios of the PPO to be not 1s during the first epoch, causing PPO …
> 👎 [GRPO] Adds option to disable dropout

- setup.py
See https://github.com/huggingface/trl/actions/runs/14362283321/job/40266585968#step:19:140
> 🚧 Temporarily restrict diffusers to <0.33.0 due to ftfy optional dep issue breaking doc builds

- tests/test_modeling_value_head.py
This PR https://github.com/huggingface/transformers/pull/37173 removes `GenerationMixin` inheritance by default in `PreTrainedModel`. Consequently, `AutoModel` now returns object without method `prepare_inputs_for_generation`.
This line:
https://github.com/huggingface/trl/blob/1d7b8c4f706a0df9fd4d3e8d0d576e8dd5dedb28/trl/models/modeling_base.py#L91
causes a premature error in this test `test_modeling_value_head.py::Seq2SeqValueHeadModelTester::test_raise_error_not_causallm`
https://github.com/huggingface/trl/blob/1d7b8c4f706a0df9fd4d3e8d0d576e8dd5dedb28/tests/test_modeling_value_head.py#L384-L390
which is bound to fail anyway, because that's what we're testing.
I propose to remove this test, which in fact tests a part of the codebase that is very little used, with a model that is also …
> ♾️ [CI] Remove `test_raise_error_not_causallm`

- tests/test_vllm_client_server.py
- tests/testing_utils.py
- trl/extras/vllm_client.py
```
$ pytest tests/test_vllm_client_server.py -v
================================== test session starts ===================================
platform linux -- Python 3.12.9, pytest-8.3.5, pluggy-1.5.0 -- /fsx/qgallouedec/miniconda3/envs/trl/bin/python
cachedir: .pytest_cache
rootdir: /fsx/qgallouedec/trl
configfile: pyproject.toml
plugins: rerunfailures-15.0, cov-6.0.0, anyio-4.9.0, xdist-3.6.1
collected 7 items                                                                        
tests/test_vllm_client_server.py::TestVLLMClientServer::test_generate PASSED       [ 14%]
tests/test_vllm_client_server.py::TestVLLMClientServer::test_generate_with_params PASSED [ 28%]
tests/test_vllm_client_server.py::TestVLLMClientServer::test_reset_prefix_cache PASSED [ 42%] …
```
> 🦾 Test vLLM client-server

- trl/trainer/sft_config.py
- trl/trainer/sft_trainer.py
This PR exposes `eos_token` in the `SFTConfig` to give users fine-grained control on which token in a given chat template should be used to indicate the end of a turn or sequence. 
Here's an example using a Qwen base model:
```
ACCELERATE_LOG_LEVEL=info TRANSFORMERS_VERBOSITY=info trl/scripts/sft.py \
--model_name_or_path Qwen/Qwen2.5-1.5B \
--dataset_name trl-lib/Capybara \
--learning_rate 2.0e-5 \
--max_seq_length 2048 \
--num_train_epochs 2 \
--per_device_train_batch_size 16 \
--gradient_accumulation_steps 1 \
--gradient_checkpointing \
--bf16 \
--use_liger_kernel \
--logging_steps 5 \
--eval_strategy steps \
--eval_steps 100 \
--eos_token '<|im_end|>' \
--output_dir data/Qwen2-1.5B-SFT-no-packing
```
Before this change, the `sft.py` script would:
* Inherit the [base model's EOS …
> Expose EOS token in SFTConfig

- trl/extras/vllm_client.py
- trl/import_utils.py
- trl/scripts/vllm_serve.py
closes https://github.com/huggingface/trl/pull/3211
Note: This PR needs to be used with the main branch of vllm and vllm-ascend to work properly
cc @qgallouedec
> 🧗 Add Ascend NPU support for vLLM server

- tests/test_grpo_trainer.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
This PR optimizes the generation process in GRPO when using gradient accumulation by ensuring that generation happens only once per effective batch, rather than once per micro-batch. This significantly improves performance—particularly with large gradient accumulation values—by leveraging the efficiency of vLLM with large batch sizes.
Currently, when using GRPO with gradient accumulation, generation is triggered at every micro-batch. For instance, with a gradient accumulation factor of 16, generation is launched 16 times before a single network update. This is inefficient, especially given that vLLM performs better with larger batches.
This PR modifies the logic so that generation occurs only once per *effective batch* (i.e., after all gradient accumulation steps). To enable this:
- The …
> ☝️ [GRPO] Generate once per effective batch

- tests/test_grpo_trainer.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
> 🎲 [GRPO] Make training dataset shuffle optional

- trl/scripts/vllm_serve.py
This pull request introduces a new optional flag, `enforce_eager`, to the VLLM serving script. This enhancement gives users control over the execution mode of the model, allowing them to choose between eager execution or the default hybrid CUDA graph approach based on their specific needs. See https://docs.vllm.ai/en/stable/api/offline_inference/llm.html#vllm.LLM
* Added a new boolean parameter `enforce_eager_flag` to the `ScriptArguments` class in `trl/scripts/vllm_serve.py`
* Updated the `main` function to pass this flag as `enforce_eager` to the model configuration
* Set the default value to `False` to maintain backward compatibility with existing behavior
* **Memory Optimization**: Enforcing eager execution can reduce memory usage in certain scenarios
* **Performance Flexibility**: …
> 🙋 Add Optional Eager Execution Mode for vLLM Serving

- trl/trainer/grpo_trainer.py
Fixes #3287 
This quietly solves the issue where an auto initialized tokenizer lacks a padding token, by setting it to the EOS token. I considered adding a `pad_token` as an input parameter to GRPOTrainer but at that point you may as well initialize the tokenizer yourself and pass it to GRPOTrainer as `processing_class=`. 
> 🧸 Fix unset tokenizer pad_token

- trl/trainer/grpo_trainer.py
> 💡 Fix type hint in `_generate_and_score_completions`

- trl/scripts/vllm_serve.py
This PR adds an optional flag `log_level` to `vllm-serve`. This flag is used to set the log level for uvicorn used in `vllm_serve.py`, the default value is `"info"`. 
> 🦄 Add optional uvicorn log level for vLLM serve

- trl/trainer/grpo_trainer.py
Fixes #3202
Before this PR, running this with ZeRO3 would fail:
```python
from trl import GRPOConfig, GRPOTrainer
dataset = load_dataset("trl-lib/tldr", split="train")
training_args = GRPOConfig(output_dir="data/Qwen2-0.5B-GRPO", bf16=True)
model="Qwen/Qwen2-0.5B-Instruct",
reward_funcs="trl-lib/Qwen2-0.5B-Reward",
)
```
> 🍡 Fix using reward model and DeepSpeed ZeRO 3

- trl/trainer/grpo_trainer.py
- trl/trainer/sft_trainer.py
Use `model.training` instead of `control.should_evaluate` to determine if the model is in evaluation mode.
It is not accurate to use `should_evaluate` to determine the `mode`. For example, if the trainer needs to evaluate and log at a certain training step, then `log` will be executed twice at this step. The first log should be for the training metrics, but at this time `should_evaluate=True`, since `should_evaluate` means to evaluate after one step. 
> 🎭 Fix train and eval mode checking in `GRPOTrainer` and `SFTTrainer`

- trl/models/utils.py
- trl/trainer/bco_trainer.py
- trl/trainer/callbacks.py
- trl/trainer/dpo_trainer.py
- trl/trainer/gkd_trainer.py
- trl/trainer/grpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/orpo_trainer.py
Whenever we run `import deepspeed`, CUDA is initialised which is (a) slow and (b) interferes with the `vllm`  server when DP=8 and TP=1 (see https://github.com/vllm-project/vllm/issues/17079):
```
ERROR:    Traceback (most recent call last):
File "/fsx/lewis/git/hf/trl/trl-env/lib/python3.11/site-packages/starlette/routing.py", line 692, in lifespan
async with self.lifespan_context(app) as maybe_state:
File "/admin/home/lewis/.local/share/uv/python/cpython-3.11.11-linux-x86_64-gnu/lib/python3.11/contextlib.py", line 210, in __aenter__
return await anext(self.gen)
^^^^^^^^^^^^^^^^^^^^^
File "/fsx/lewis/git/hf/trl/trl/scripts/vllm_serve.py", line 362, in lifespan
msg = connection.recv()
^^^^^^^^^^^^^^^^^
File "/admin/home/lewis/.local/share/uv/python/cpython-3.11.11-linux-x86_64-gnu/lib/pyth …
```
> Better guards for DeepSpeed imports

- tests/test_cli.py
- trl/cli.py
- trl/scripts/utils.py
This PR makes it possible to specify all required arguments in a config.yaml file and call this via cli, e.g.
```bash
trl sft --config examples/cli_configs/example_config_dummy.yaml --output_dir test-trl-cli --lr_scheduler_type cosine_with_restarts
```
This line is directly from [the trl docs](https://huggingface.co/docs/trl/main/en/clis) but didn't work since `config` is no known argument of the `TrlParser` when calling `parse_args` which is always called.
Fixes #3102
- ~[ ] Did you make sure to update the documentation with your changes?~
> 📋 Allow calling trl cli in sft mode with config file

- trl/trainer/dpo_trainer.py
A [refactor](https://github.com/huggingface/trl/commit/8fb267ff1ece596c9ca0f810f4f54f9ee1fe7b66) broke the ability to run evaluations in DPO trainer as it drops the "prompt" column needed for evals.
Additionally, on non-zero ranks, the evals will error with the error below because wandb is only initialized on rank0:
`[rank1]: wandb.errors.errors.Error: You must call wandb.init() before wandb.log() `
> DPO fixes for evaluations

- trl/trainer/grpo_trainer.py
The current check for if FSDP is enabled is incorrect
https://github.com/huggingface/trl/blob/09b669fbf7a18ac017c36573b194405c4f229038/trl/trainer/grpo_trainer.py#L412
as the `fsdp_config` is always post initialized to [a dictionary](https://github.com/huggingface/transformers/blob/7a3e208892c06a5e278144eaf38c8599a42f53e7/src/transformers/training_args.py#L1867-L1929). You can easily test this with
```
from trl import GRPOConfig, GRPOTrainer, TrlParser
model_name_or_path = "Qwen/Qwen2.5-0.5B-Instruct"
parser = TrlParser(GRPOConfig)
(training_args,) = parser.parse_args_into_dataclasses()
trainer = GRPOTrainer(model=model_name_or_path, reward_funcs=[], args=training_args)
```
and printing the `ref_model`
I propose to move the `ref_model` initialization till after `Trainer` has been …
> [GRPO] Reference model initialization bug fix

- trl/extras/profiling.py
Bring parity between MLFlow and Wandb in terms of metrics populated for profiling the training run. This gets used in the grpo trainer. 
Made changes locally, and verified metrics being populated on the MLFlow UI 
@qgallouedec
> 🌊 Add MLflow metrics in profiling context

- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
Some suggestions for PR #3388:
- Move `generation_batch_size` under the section `Parameters that control generation`
- use `int | None` instead of `int | str` because the the CLI parser doesn't support multi-type (that's why the CI is failing)
- rephrase some comments to be more precise (are we one the same page on these terms?):
| Term | Size |
|----------|----------|
| Local batch | `per_device_train_batch_size` |
| Local accumulated batch | `per_device_train_batch_size * gradient_accumulation_steps` |
| Global batch | `per_device_train_batch_size * world_size` |
| Effective batch | `per_device_train_batch_size * world_size * gradient_accumulation_steps` |
| Local generation batch | `per_device_train_batch_size * steps_per_generation ` |
| Generation batch | `per_device_train_batch_size …
> Suggestions for Decouple gradient accumulation from the number of minibatches generated

- setup.py
License classifier are deprecated, see https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license
> 🪪 Remove license classifier

- tests/test_dpo_trainer.py
fixes the CI test failure on transformer-dev as the param name now starts with `model.`
> [CI] fix CI failure of transformer dev

- trl/trainer/ppo_trainer.py
Simple change to the typing and default value of value_model in PPOTrainer. Since it cannot be None, it should not default to None or be marked Optional. See [this issue](https://github.com/huggingface/trl/issues/3292).
> 🙅 PPO value_model can't be None, so it shouldn't be Optional

- trl/trainer/grpo_config.py
Disabling `top_k` in GRPO sampling as a default and setting the sampling temperature default to `1.0`
> [GRPO] disabling top_k sampling default

- trl/trainer/grpo_trainer.py
This change initializes the reward_kwargs variable as an empty dictionary to avoid potential UnboundLocalError during its usage in the GRPOTrainer class. This ensures that the variable is defined before it is accessed.
This PR addresses a potential `UnboundLocalError` that can occur in `trl.trainer.GRPOTrainer._generate_and_score_completions`.
The `reward_kwargs` dictionary is intended to store additional arguments (beyond prompt and completion) that are passed to custom, non-module-based reward functions. This dictionary is populated within an `else` block when iterating through `self.reward_funcs`.
If `self.reward_funcs` is empty (e.g., when a downstream library or user provides an empty list, intending to bypass TRL's internal reward calculation and supply pre-computed …
> 🛠️ Initialize reward_kwargs to prevent UnboundLocalError in GRPOTrainer

- trl/trainer/grpo_trainer.py
Fixes #3476
I'm testing using this tiny script on two gpus:
for server:
```python
CUDA_VISIBLE_DEVICES=0 trl vllm-serve --model Qwen/Qwen3-0.6B
```
trianing script: 
```python
from trl import GRPOTrainer, GRPOConfig
dataset = load_dataset("trl-lib/tldr", split="train[:1%]")
def reward_num_unique_chars(completions, **kwargs):
return [len(set(c)) for c in completions]
training_args = GRPOConfig(
output_dir="qwen3-mask-completions",
bf16=True,
gradient_checkpointing=True,
logging_steps=10,
use_vllm=True,
mask_truncated_completions=True,
)
model="Qwen/Qwen3-0.6B",
reward_funcs=reward_num_unique_chars,
)
```
for training:
```python
CUDA_VISIBLE_DEVICES=0 accelerate launch …
```
> 📏 Completion length logging fix + remainder logging fix

- setup.cfg
I think the latest release of vLLM introduced dependencies that are too large for our doc builder to support. In any case, vLLM does not need to be installed for the doc builder to work, so we can exclude it from dev.
> 📚 Fix doc building by removing vLLM from dev dependencies in `setup.cfg`

- tests/test_cli_utils.py
- trl/scripts/utils.py
When a config.yaml file is parsed by the `TRLParser` there is an option to return remaining strings. But otherwise we do not check that all of the parsed args have been consumed by the config classes. 
It would be easy for a user to mistype an argument in a config file and not be aware that the parameter was not set correctly.
This PR adds an option to the `TRLParser` `fail_with_unknown_args`, which is `True` by default. This ensures that errors in the config file are quickly flagged to the user.
> 💽 [TRLParser] Fail when unknown args are provided in the config file.

- trl/trainer/alignprop_trainer.py
- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/ddpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/gkd_trainer.py
- trl/trainer/grpo_trainer.py
- trl/trainer/iterative_sft_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/nash_md_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/prm_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/sft_trainer.py
- trl/trainer/xpo_trainer.py
`*Trainer::create_model_card()` fails to convert a list of tags into a set, causing an `AttributeError` for users who pass tags as a list.
Properly normalize tags -> set, for all allowed input types.
Fixes #3610 
> Fix: list-typed tags handling in `Trainer::create_model_card`

- tests/test_grpo_trainer.py
- trl/extras/vllm_client.py
- trl/scripts/vllm_serve.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
This PR is an attempt to address #3562 to allow users to specify additional arguments that can be passed to either vllms `SamplingParams` or HFs `GenerationConfig` to give a user more control over how the old policy generates sample responses.
Fixes #3562
> 🧬 Add `generation_kwargs` as a property of `GRPOConfig` to support additional generation arguments.

- trl/trainer/grpo_trainer.py
Currently, If the user does not pass `generation_kwargs`, then you should not face any issues (i.e. default values). Yet, this is what you get if you specify `vllm_mode=colocate`:
```
generatigeneration_kwargson_kwargs.update(self.args.)
TypeError: 'NoneType' object is not iterable
```
This PR simply fixes that !
Fixes #3633 
@qgallouedec 
> fix grpo generation_kwargs

- trl/trainer/grpo_config.py
% and * have the same order of precedence so we need to add paranthesis to ensure that the `generation_batch_size` check is accurate.
Fixes #3656
> Add paranthesis to correct the check.

- docs/source/grpo_trainer.md
- tests/test_grpo_trainer.py
- trl/trainer/grpo_trainer.py
This allows for implementing dynamic reward strategies like curriculum learning, where rewards can be adjusted based on training progress. Fixes #3668
> feat: Pass trainer state to reward functions

- tests/test_sft_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/sft_trainer.py
When using ffd packing with flash attention we should drop the attention_mask since with the attention mask the flash-attention2 ignores the positon_ids... with this fix it will use the position_ids
> [SFT] drop attention_mask if we have position ids for fa2

- trl/scripts/vllm_serve.py
Fixes [#3676 ](https://github.com/huggingface/trl/issues/3676)
This PR solves the bug reported at the issue #3676. In the issue it was reported a hanging in the training of GRPOTrainer using vllm server. The hanging was identified at a pynccl_comm group barrier called in the client side (trl/extras/vllm_client.py:283) that is hanging the execution until all workers in the group have processed the broadcast of the weights.
The problem that generates this hanging occurs in the vllm server side. The vllm workers are triggered to receive the weights broadcast in the following way:
1. **`trl.extras.vllm_client.VLLClient.update_named_param`**
- This is the method called during training by GRPOTrainer that will update the weights on the vllm server
**1.1** Execute a post request to the …
> Fix non-serializable torch.dtype bug in VLLM weight sync

- trl/trainer/dpo_trainer.py
Add type hints to `trainer/dpo_trainer.py`
> Add type hints to `dpo_trainer.py`

- tests/test_data_utils.py
- tests/test_sft_trainer.py
- trl/data_utils.py
- trl/trainer/sft_config.py
- trl/trainer/sft_trainer.py
PR #3645 correctly identifies that our current default packing implementation (`ffd`) is actually an implementation of the Best-fit decreasing algorithm. We're querying for the "tightest" bin fit rather than the first open one.  
Rename to Best-fit decreasing (BFD).
Fixes #3645.
> Fix mislabeling: "First-fit decreasing" is actually "Best-fit-decreasing"

- setup.cfg
Before this fix I'd get this warning when building the package (`python -m build`):
```
/tmp/build-env-xjot1w65/lib/python3.12/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'trl.accelerate_configs' is absent from the `packages` configuration.
!!
********************************************************************************
############################
############################
Python recognizes 'trl.accelerate_configs' as an importable package[^1],
but it is absent from setuptools' `packages` configuration.
This leads to an ambiguous overall configuration. If you want to distribute this
package, please make sure that 'trl.accelerate_configs' is explicitly added
to the `packages` configuration field.
Alternatively, you can also rely on setuptools' discovery …
```
> 🔭 Fix package discovery configuration in setup.cfg

- trl/trainer/sft_trainer.py
To avoid cross-contamination when training with packed sequences, we pass `position_ids` to FA2. This was introduced in PR #3526, which calculated `position_ids` during packing and added them to the dataset. To ensure these are retained, `position_ids` must be set as a signature column; otherwise, the `Trainer` will discard them as unused.
https://github.com/huggingface/transformers/blob/ca7e1a3756c022bf31429c452b2f313f043f32de/src/transformers/trainer.py#L1007
While this was implemented correctly, PR #3649 introduced an optimized approach where `position_ids` are computed within the data collator using a new dataset column, `seq_lengths`. However, the latter PR failed to update the signature column from `position_ids` to `seq_lengths`. As a result, `seq_lengths` is not passed to the …
> [SFT] Add `seq_lengths` to signature columns

- trl/trainer/orpo_trainer.py
This PR addresses an issue in `ORPOTrainer` where the training loss is not correctly scaled when using gradient accumulation. When `gradient_accumulation_steps` > 1, the loss was not being divided by the number of accumulation steps, leading to an incorrectly inflated reported training loss.
The fix is identical to the fix applied in other PRs, such as #2645.
Fixes #2628
> Fix ORPOTrainer loss scaling with gradient accumulation

- docs/source/grpo_trainer.md
- trl/trainer/grpo_trainer.py
Late review for #3638
If you've also time to review @toslali-ibm 
```python
from trl import GRPOTrainer, GRPOConfig
train_dataset = load_dataset("trl-internal-testing/zen", "standard_prompt_only", split="train")
def main():
training_args = GRPOConfig(
max_completion_length=8,
per_device_train_batch_size=3,  # reduce the batch size to reduce memory usage
num_generations=3,  # reduce the number of generations to reduce memory usage
use_vllm=True,
vllm_mode="colocate",
report_to="none",
)
model="Qwen/Qwen3-0.6B",
reward_funcs="trl-internal-testing/tiny-Qwen2ForSequenceClassification-2.5",
train_dataset=train_dataset,
)
if __name__ == "__main__":
main()
```
this now work, tested with 2 GPUs
> 📥 Set environment variables for vLLM distributed training in GRPOTrainer

- trl/trainer/grpo_trainer.py
When using activation offloading, the `_checkpoint_wrapped_module.` needs to be removed in all cases, not just FSDP. I moved this to a helper method in case other such cases crop up later which can be overridden much easier downstream.
> [GRPO] remove common activation offloading substring in all cases

- trl/trainer/iterative_sft_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/sft_trainer.py
Updated `processing_class` docs for trainers to also include `BaseImageProcessor` and the rest of possibilities.
Forgot a few updates in the previous PR (https://github.com/huggingface/trl/pull/3737) 😅 
> Updated missing `processing_class` docs for rest of trainers

- trl/trainer/grpo_trainer.py
- vllm `max_num_seqs` should reflect the actual maximum number of sequences that can be passed to vLLM. Since `steps_per_generation` determines the effective batch size with the dataloader, it should be used instead of `gradient_accumulation_steps`.
> uses `steps_per_generation` in vllm max_num_seqs

- tests/test_grpo_trainer.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
Some minor change, late review from https://github.com/huggingface/trl/pull/3563
1. Don't use/unittest private method: `_compute_entropy_mask` -> `get_high_entropy_mask`
2. `token_entropy_percentile_threshold` -> `top_entropy_quantile` top better align with the _top-20%_ message (its more a quantile than a percentile here.
3. Fix the doc: link and var name (rho, not tau)
4. I better like `_get_per_token_logps_and_entropies` returning a tuple, but personal preference
cc @pramodith happy to have you thoughts on this
> 🏗️ Refactor top-entropy in GRPO

- trl/trainer/grpo_trainer.py
Until commit d6a969f, ref_per_token_logps was calculated inside _compute_loss or compute_liger_loss, which gets input of size per_device_batch_size. 
Since it moved to _generate_and_score_completions it now need to be passed a batch_size. Without it, memory consumption is not independent of the number of gradient accumulations and can spike when beta != 0
> [GRPO] Fix: Processing ref logprobs in batches

- trl/trainer/alignprop_trainer.py
- trl/trainer/ddpo_trainer.py
Usage for these trainers are very low. We will deprecate them and remove in three versions.
> 🔔 Add deprecation warnings for `AlignPropTrainer` and `DDPOTrainer`

- examples/scripts/alignprop.py
- examples/scripts/bco.py
- examples/scripts/cpo.py
- examples/scripts/ddpo.py
- examples/scripts/dpo_online.py
- examples/scripts/dpo_vlm.py
- examples/scripts/evals/judge_tldr.py
- examples/scripts/gkd.py
- examples/scripts/grpo_vlm.py
- examples/scripts/kto.py
- examples/scripts/nash_md.py
- examples/scripts/orpo.py
- examples/scripts/ppo/ppo.py
- examples/scripts/ppo/ppo_tldr.py
- examples/scripts/prm.py
- examples/scripts/reward_modeling.py
- examples/scripts/rloo/rloo.py
- examples/scripts/rloo/rloo_tldr.py
- examples/scripts/sft_gemma3.py
- examples/scripts/sft_video_llm.py
- examples/scripts/sft_vlm.py
- examples/scripts/sft_vlm_gemma3.py
- examples/scripts/sft_vlm_smol_vlm.py
- examples/scripts/xpo.py
- trl/scripts/dpo.py
- trl/scripts/env.py
- trl/scripts/grpo.py
- trl/scripts/kto.py
- trl/scripts/sft.py
I did my best to guess the dependencies, lmk if it sounds good to you !
Btw for `trl` I require `trl @ git+https://github.com/huggingface/trl.git` but for releases it would be nice to require `trl==VERSION`, and then set the git URL back when setting the dev version `VERSION.dev0`
`transformers` has a `utils/release.py` file to do this automatically, that I updated to account for uv scripts in https://github.com/huggingface/transformers/pull/39635
cc @lewtun @qgallouedec
> Add uv scripts headers

- trl/trainer/grpo_trainer.py
In my previous PR merged today (PR #3762), one of the change was to pass the device of the main training process as an argument to `VLLMClient.init_communicator`, instead of the hardcoded `0` that was set before:
```python
self.vllm_client.init_communicator(device=self.accelerator.device)
```
This is valid since this argument is used to instantiate the `PyNcclCommunicator` class, that accepts this argument as `str`, `int` or `torch.device`.
But in some scenarios that I was doing experiments I started to get this error:
```
Traceback (most recent call last):
File "/workspace/trl/main.py", line 32, in <module>
File "/workspace/trl/trl/trainer/grpo_trainer.py", line 797, in __init__
self.vllm_client.init_communicator(device=self.accelerator.device)
File …
```
> 🩹 [Hotfix] Fix pynccl communicator assertion error with VLLMClient

- docs/source/distributing_training.md
- docs/source/using_llama_models.md
This PR updates a broken documentation link in `docs/source/using_llama_models.md`. The original link to the PEFT + TRL docs produced a missing page or 404 error. I replaced it with the correct link to the current PEFT integration documentation to ensure users have access to the right resources.
@qgallouedec
> Fix broken PEFT+TRL docs link in `using_llama_models.md`

- trl/mergekit_utils.py
from `mergekit` 0.1.3, we added a `device` field into `MergeOptions` to support other pytorch accelerators as Intel XPU. For versions before 0.1.3, since `MergeOptions` uses the default `ignore`  way to handle extra fields, so it's still OK for these older versions to input extra `device` to it.
@kashif , pls help review and comment, thx very much.
> add xpu support for mergekit

- examples/scripts/bco.py
- examples/scripts/cpo.py
- examples/scripts/grpo_vlm.py
- examples/scripts/gspo.py
- examples/scripts/gspo_vlm.py
- examples/scripts/kto.py
- examples/scripts/mpo_vlm.py
- examples/scripts/orpo.py
- examples/scripts/sft_video_llm.py
- examples/scripts/sft_vlm.py
- examples/scripts/sft_vlm_gemma3.py
- examples/scripts/sft_vlm_smol_vlm.py
~~The argument parser needs that `bf16` is explicitly set so adding `True` to the scripts.~~
Removing `bf16` in scripts since it's True by default.
If only passing `--bf16`:
```bash
error: argument --bf16: expected one argument
```
> 👋 Remove `--bf16` value in scripts

- tests/test_grpo_trainer.py
- trl/trainer/grpo_trainer.py
This PR fixes a bug in `GRPOTrainer` where `TrainerState` objects inside `reward_kwargs` were incorrectly treated as subscriptable, leading to the following error:
```
File ".../trl/trainer/grpo_trainer.py", line 1332, in _calculate_rewards
row_reward_kwargs = {key: value[nan_row_idx] for key, value in reward_kwargs.items()}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'TrainerState' object is not subscriptable
```
The issue was introduced in [#3669: *feat: Pass trainer state to reward functions*](https://github.com/huggingface/trl/pull/3669), which added `trainer_state` to `reward_kwargs`:
https://github.com/huggingface/trl/blob/e04f7eb3b993b5278733a793853ed3a85d1c69c8/trl/trainer/grpo_trainer.py#L1035
This PR ensures that the `trainer_state` entry is …
> 🗞 bugfix 'TrainerState' object is not subscriptable

- examples/scripts/evals/judge_tldr.py
When running this example code with vllm, it returns error like
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
exitcode = _main(fd, parent_sentinel)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
prepare(preparation_data)
File "/usr/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "/usr/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
main_content = runpy.run_path(main_path,
^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen runpy>", line 291, in run_path
File "<frozen runpy>", line 98, in _run_module_code
File "<frozen runpy>", line 88, in …
```
> 📦 Wrapping the main execution code to avoid multi-processing issues from vLLM

- docs/source/grpo_trainer.md
- docs/source/logging.md
- docs/source/paper_index.md
- tests/test_grpo_trainer.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
Updates the `scale_rewards` parameter to accept three different valid values `none`, `group` and `batch` to determine the level at which the std of rewards will be aggregated.
With this feature users can now train a model using the PPOLite technique outlined in https://arxiv.org/html/2508.08221v1, by setting `scale_rewards` = `group` and `loss_type='bnpo'` (for token level loss aggregration).
Fixes #3920
> 🪶 [GRPO] PPO Lite: Scale rewards by Std of Batch

- docs/source/grpo_trainer.md
- tests/test_grpo_trainer.py
- trl/trainer/grpo_config.py
- trl/trainer/grpo_trainer.py
This PR introduces the true DAPO aggregation method for the loss. Previously, we were only able to achieve partial equivalence, because the normalizer was local and not accumulated. In other words, you could only achieve DAPO with gas=1 and num GPUs=1.
I checked that this new loss type is working and correct with both gradient accumulation and distributed training!
> 🏌️ DAPO loss type

- docs/source/paper_index.md
This PR updates the paper index documentation to include additional research papers and their corresponding implementation configurations within the TRL package.
- Added new paper entries with proper references and configuration examples
- Included implementation details and parameter settings for reproducibility
- Enhanced documentation to help users understand and reproduce training configurations
This update expands the paper index to provide better coverage of research implementations available in TRL, making it easier for users to find and use relevant configurations for their research and experiments.
> 🗂 Update paper_index section

- trl/trainer/sft_trainer.py
The `transformers` package has supported `flash_attention_3` for a few weeks. However, when `--attn_implementation flash_attention_3` is passed to SFTTrainer, the loss becomes 0.0, because the `position_ids` are only passed to the model when attn_implementation is set to `flash_attention_2` or `kernels-community/vllm-flash-attn3`. Simply adding `flash_attention_3` to the `use_flash_attention` list can help solve the problem.
> 📸 Return `position_ids` for `flash_attention_3`

- trl/models/utils.py
`dataclasses.replace` re-instanciate the data class, and cause #3980.
Fixes #3980
> 🪃 `args.gradient_checkpointing = False` instead of `args = dataclasses.replace(args, gradient_checkpointing=False)`

- tests/test_dpo_trainer.py
- trl/trainer/dpo_trainer.py
The function `shift_tokens_right` did not return its result, which made it unusable in practice.
- Added `return shifted_input_ids` at the end of the function.
- Ensures `shift_tokens_right` now correctly returns a `torch.Tensor`.
- No breaking changes expected.
> ⏰ fix: add return to shift_tokens_right

- trl/trainer/ppo_trainer.py
PPOTrainer._save_checkpoint is declared as
```python
def _save_checkpoint(self, model, trial):
```
but is invoked with
```python
self._save_checkpoint(model, trial=None, metrics=None)
```
Remove the extra `metrics=None` argument so the call matches the method signature
> 💾 [bugfix] fix PPO save_checkpoint

- tests/test_utils.py
- trl/trainer/utils.py
In SFT and GRPO, the entropy computation induces huge memory spike when training on long context. This PR fixes it, basically from 80 GB spike to around 0.23 GB spike. No significant slowdown observed.
```python
import torch
import torch.nn.functional as F
def entropy_from_logits_before(logits, chunk_size: int = 1) -> torch.Tensor:
per_token_entropies = []
for logits_chunk in logits.split(chunk_size, dim=0):
logps = F.log_softmax(logits_chunk, dim=-1)
chunk_entropy = -(torch.exp(logps) * logps).sum(-1)
per_token_entropies.extend(chunk_entropy)
per_token_entropies = torch.stack(per_token_entropies)
return per_token_entropies
def entropy_from_logits_after(logits: torch.Tensor, chunk_size: int = 128) -> torch.Tensor:
original_shape = logits.shape[:-1]
num_classes = logits.shape[-1] …
```
> 🌵 Refactor entropy_from_logits for memory efficiency

- docs/source/quickstart.md
This PR updates the GRPO example in the quickstart to make it work. Before this PR, the example referenced a keyword argument `reward_function` that doesn't exist on the GRPOTrainer. After this PR, a user can copy/paste the example and have it run correctly.
The example in the GRPOTrainer reference documentation has the correct keyword argument `reward_funcs`.
https://huggingface.co/docs/trl/en/grpo_trainer#trl.GRPOTrainer.example
```
model="Qwen/Qwen2-0.5B-Instruct",
reward_funcs=reward_func,
)
```
Before (erroring out)
```
Traceback (most recent call last):
File "/Users/freebie/code/python/llm_chess_rlvr/grpo_hello_world.py", line 9, in <module>
^^^^^^^^^^^^
TypeError: GRPOTrainer.__init__() got an unexpected keyword …
```
> Fix typo in GRPO quickstart

- trl/trainer/ddpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/grpo_trainer.py
- trl/trainer/judges.py
- trl/trainer/rloo_trainer.py
- trl/trainer/sft_trainer.py
Fix formatting errors in docstrings.
This PR addresses the issue where parameter definitions in docstrings span multiple lines before the separating colon (`:`), causing incorrect parsing.
For example, previously the following docstring was not handled correctly: https://huggingface.co/docs/trl/v0.22.2/en/sft_trainer#trl.SFTTrainer
```python
"""
Args:
eval_dataset ([`~datasets.Dataset`], [`~datasets.IterableDataset`] or `dict[str, Union[Dataset,
IterableDataset]]`):
Dataset to use for evaluation. It must meet the same requirements as `train_dataset`.
"""
```
producing
Changes:
- Fix definition of parameters `eval_dataset`, `optimizers`, `optimizer_cls_and_kwargs`, and `preprocess_logits_for_metrics` in the docstrings of `DPOTrainer`, `SFTTrainer`, `GRPOTrainer`, and `RLOOTrainer` classes …
> Fix formatting errors in docstrings

- examples/scripts/sft_vlm.py
- trl/trainer/prm_config.py
- trl/trainer/reward_config.py
- trl/trainer/sft_config.py
Now we require transformers 4.56
> ⚖️ Remove `average_tokens_across_devices` default replacement

- tests/slow/test_grpo_slow.py
- tests/test_online_dpo_trainer.py
CI hotfix: xfail test_training_with_transformers_paged for:
- OnlineDPOTrainer
- GRPOTrainerSlowTester
This PR marks tests as expected to fail for transformers < 4.56.2.
Changes:
- Add a version check for `transformers` in the `test_training_with_transformers_paged` test:
- Mark the test as expected to fail (`xfail`) for versions below 4.56.2 due to an upstream bug (commented by @kashif in: https://github.com/huggingface/trl/pull/4043#issuecomment-3269066097):
- huggingface/transformers#40692
- Fail the test if run on newer versions to remember reverting this PR and remove the xfail mark
Fix #4035.
Supersede and close #4043.
> CI hotfix: xfail test_training_with_transformers_paged

- docs/source/best_of_n.md
- trl/extras/best_of_n_sampler.py
Add autodoc for `BestOfNSampler` classes and improve docstrings.
> Add autodoc for BestOfNSampler and improve docstrings

- trl/scripts/sft.py
SFT script is not necessarily used for instruction tuning. Plus, the right way to set a chat template is now to use the arg `SFTConfig.chat_template_path`
Closes #3995
> 💬 Remove setting chat template in sft script

- .github/workflows/slow-tests.yml
Align slow tests with regular tests.
This PR:
- Aligns slow tests with regular tests architecture for consistency and maintainability
- Replaces custom Docker images (`huggingface/trl-latest-gpu`, `huggingface/trl-source-gpu`) with standard `pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel`
- Removes problematic `--no-deps` flag that prevented VLM dependencies from being installed
See previous PR addressing the issue of misaligned dependencies:
- #4064
The slow tests used custom Docker images with pre-installed dependencies and `--no-deps` to avoid conflicts. When VLM extras were added to the install command, the `--no-deps` flag prevented Pillow and other VLM dependencies from being installed, causing import errors.
- Use the same proven approach as regular tests: standard PyTorch image + `uv …
> Align slow tests with regular tests

- Makefile
- pyproject.toml
Add support for testing experimental features.
This PR introduces a minimal testing workflow for the new `experimental` submodule:
- Default behavior unchanged: pytest and make test now exclude experimental tests automatically via `addopts = ["-k", "not experimental"]` in pyproject.toml
- New target: `make test_experimental`: runs only the experimental tests
- Directory structure: All tests for features under the `trl.experimental` namespace should be placed in the directory:
- `tests/experimental/`
This setup keeps CI fast and stable (running only the main test suite) while making it easy for contributors to run experimental tests locally (or in a future separate CI job).
Follow-up to:
- #4073
> Add support for testing experimental features

- examples/scripts/grpo_vlm.py
- examples/scripts/gspo.py
- examples/scripts/online_dpo_vlm.py
- examples/scripts/rloo.py
- setup.cfg
Pin `num2words` to avoid supply chain attack: https://www.stepsecurity.io/blog/supply-chain-security-alert-num2words-pypi-package-shows-signs-of-compromise
> ⌨️ Pin num2words

- trl/trainer/online_dpo_config.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/rloo_config.py
- trl/trainer/rloo_trainer.py
Add deprecation warnings to docstrings.
This PR adds deprecation notices to docstrings for documentation consistency: the docstring should match the actual behavior of the code.
This approach is better than removing it entirely because:
- The parameter still exists in the code and will accept values (even if it shows a warning)
- Users need the documentation of the parameter to better understand the deprecation message
> Add deprecation warnings to docstrings

- trl/trainer/bco_trainer.py
- trl/trainer/cpo_trainer.py
- trl/trainer/dpo_trainer.py
- trl/trainer/gkd_trainer.py
- trl/trainer/grpo_trainer.py
- trl/trainer/kto_trainer.py
- trl/trainer/nash_md_trainer.py
- trl/trainer/online_dpo_trainer.py
- trl/trainer/orpo_trainer.py
- trl/trainer/ppo_trainer.py
- trl/trainer/prm_trainer.py
- trl/trainer/reward_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/xpo_trainer.py
#3550 changed `tags` from `list` to `set`. It added conversion of `tags` to `list` when calling `generate_model_card` in `SFTTrainer` but not in other trainers. This PR _fixes_, though nothing is really broken since `tags` is later implicitly converted to list with 
https://github.com/huggingface/trl/blob/e2b18ec4e7eb63bf9cd7829e0c39b8473b09f9a8/trl/trainer/utils.py#L1252
> 📜 Convert `set` to `list` of tags

- scripts/generate_tiny_models.py
This PR fixes the configs for VLMs within `scripts/generate_tiny_models.py`. The main change is switching from direct attribute assignment on the config object to passing configuration dictionaries as arguments to `AutoConfig.from_pretrained`, which streamlines and clarifies the configuration process.
Configuration refactoring:
* Replace manual assignment of individual attributes on `config.text_config` and `config.vision_config` with `text_config` and `vision_config` dictionaries passed directly to `AutoConfig.from_pretrained`. This makes the code cleaner and less error-prone.
* Add a `"layer_types": None` entry to `text_config`, indicating it should be set automatically based on `num_hidden_layers`, so we avoid a ValueError
Fix #4099.
We can check that the fix works.
Before the fix: …
> Fix VLM configs in generate_tiny_models

- docs/source/grpo_trainer.md
- docs/source/reducing_memory_usage.md
The option `vllm_sleep_enabled` mentioned in the docs does not exist. It seems like `vllm_enable_sleep_mode` is the correct one. This PR fixes this. https://github.com/huggingface/trl/blob/20cc58d7772ae660792c7b5249d8b817986a547d/trl/trainer/grpo_config.py#L143C9-L143C31
> docs: correct option name to enable vllm sleep mode

- tests/test_utils.py
- trl/experimental/gfpo/gfpo_trainer.py
- trl/trainer/grpo_trainer.py
- trl/trainer/rloo_trainer.py
- trl/trainer/utils.py
This PR is the first of a sequence of PR that aims to refactor the generation part of GRPO/RLOO to allow for easier customization. While refactoring, I realized that having `image_split_sizes` actually doesn't help much, and is redundant with `image_grid_thw`. Consequently, I suggest to revert #4032
> 🟩 Drop `image_split_sizes` in favour of `image_grid_thw`

- scripts/generate_tiny_models.py
Align the remaining VLM config params and pass them as arguments to `AutoConfig.from_pretrained`.
This is the recommended way to update subconfigs: https://github.com/huggingface/transformers/issues/41020#issuecomment-3314879813
Follow-up to:
- #4101
> 🔭 Align param passing to VLM configs in generate_tiny_models

- tests/test_sft_trainer.py
- trl/trainer/sft_trainer.py
DFT loss training crashes in an eval step because the HF Trainer's `prediction_step` function doesn't pass the `num_items_in_batch` param to the loss function.
This PR fixes it by calculating the `num_items_in_batch` when the model is in `eval` mode. We also additionally add a sanity unit-test for validating that dft loss works as desired.
Fixes #4096 
> [SFTrainer]: Fix DFT Loss

- tests/test_gkd_trainer.py
For some reason, we have a memory spike with liger that regularly breaks the CI. Marking this test as xfail.
```
13970 Addr: b7fa734000000_0, Size: 777.6MiB (815351040 bytes) allocation, Total memory used after allocation: 11.5GiB (12341773448 bytes), timestamp Tue Sep 23 2025 13:14:13 GMT-0600 (Mountain Daylight Time)
CUDACachingAllocator.cpp:0:c10::cuda::CUDACachingAllocator::Native::DeviceCachingAllocator::malloc(signed char, unsigned long, CUstream_st*)
:0:c10::cuda::CUDACachingAllocator::Native::NativeCachingAllocator::malloc(void**, signed char, unsigned long, CUstream_st*)
:0:c10::cuda::CUDACachingAllocator::Native::NativeCachingAllocator::allocate(unsigned long)
:0:c10::StorageImpl::StorageImpl(c10::StorageImpl::use_byte_size_t, c10::SymInt const&, c10::Allocator*, bool) …
```
> 🌵 Mark GKD trainer test as expected failure due to OOM issue

- trl/experimental/gfpo/gfpo_trainer.py
- trl/experimental/grpo_with_replay_buffer/grpo_with_replay_buffer_trainer.py
- trl/experimental/gspo_token/grpo_trainer.py
- trl/trainer/grpo_trainer.py
- trl/trainer/rloo_trainer.py
Pass required `token_type_ids`.
Follow-up to `transformers` PR:
- https://github.com/huggingface/transformers/pull/40917
> 🚨 BC-breaking: `paligemma` processor now returns `token_type_ids` by default. This is required to disambiguate forward passes, due to the bidirectional attention mask in the prompt. Advanced generation methods may run forward passes with prompt + generated tokens, so they will fail without `token_type_ids`.
Fix #4142, fix #4150.
This PR extends support for the `token_type_ids` input across the GRPO and RLOO trainers, ensuring that models using token type information can correctly handle these inputs during training, evaluation, and loss computation. 
The changes are applied consistently to:
- GRPO
- RLOO
**Token type IDs support:**
* Added `token_type_ids` as an …
> Pass required token_type_ids

- trl/trainer/nash_md_trainer.py
- trl/trainer/xpo_trainer.py
This PR replaces the `.. deprecated::` Sphinx directives with the `<Deprecated>` tag in the docstrings of:
- `NashMDTrainer`
- `XPOTrainer`
The Sphinx directives were introduced in:
- #3783
> Fix docstrings with 'deprecated' Sphinx directive

- docs/source/sft_trainer.md
- trl/trainer/gkd_trainer.py
- trl/trainer/ppo_trainer.py
Fix PEFT interlinks in docstrings
The interlink will be properly rendered (as it is already the case for other HF libs, like `transformers` or `datasets`) once this PR in `doc-builder` is merged:
- https://github.com/huggingface/doc-builder/pull/628
> Fix PEFT interlinks in docstrings

- tests/test_grpo_trainer.py
Replace remaining `trainer.tokenizer` with `trainer.processing_class` in GRPO `TestUpdateWithReplayBuffer`.
For context, `trainer.tokenizer` was removed in upstream `transformers`:
- https://github.com/huggingface/transformers/pull/41128
Follow-up to:
- #4185
> Replace remaining trainer.tokenizer with trainer.processing_class in GRPO test

- docs/source/_toctree.yml
- docs/source/lora_without_regret.md
This is draft PR for a docs page to implement the blog post 'lora without regret' in TRL. 
@edbeeching is going to review and share a script.
@sergiopaniego 
```
hf jobs uv run \
--flavor a100-large \
--timeout 8h \
--secrets HF_TOKEN \
"https://gist.githubusercontent.com/burtenshaw/fce24305833f2ecacfe8da181901d345/raw/sft_lora.py" \
--model_name_or_path Qwen/Qwen2.5-3B-Instruct \
--dataset_name open-thoughts/OpenThoughts-114k \
--learning_rate 2.0e-5 \
--num_train_epochs 1 \
--packing \
--per_device_train_batch_size 2 \
--gradient_accumulation_steps 16 \
--gradient_checkpointing \
--eval_strategy no \
--use_peft \
--lora_r 256 \
--lora_alpha 16 \
--lora_target_modules all-linear \
--output_dir Qwen2.5-3B-OpenThoughts-LoRA \
--report_to trackio \
--push_to_hub
```
```
hf jobs uv run \ …
```
> [DOCS] Lora without regret

- .github/workflows/build_documentation.yml
- .github/workflows/build_pr_documentation.yml
Remove `custome_container` for building the docs:
- Fix DDPO ImportError: cannot import name 'FLAX_WEIGHTS_NAME'
This PR makes a small update to the GitHub Actions workflows for building documentation. The change removes the use of a custom Docker container for the documentation build jobs.
Currently the CI GitHub Action to build the main docs is broken, due to an issue with the versions of `diffusers` and `transformers`: https://github.com/huggingface/trl/actions/runs/18184074495/job/51765142515
```python
ImportError: cannot import name 'FLAX_WEIGHTS_NAME' from 'transformers.utils' (/usr/local/lib/python3.10/site-packages/transformers/utils/__init__.py)
```
After investigation:
- the issue is already fixed in diffusers but not released yet: 
- …
> Remove custome_container for building the docs

- trl/trainer/ppo_trainer.py
The `processing_class` parameter cannot be optional because it doesn't have a default value and is later used without checking whether it's `None`.  
As a result, it must always be provided when initializing the class, since the code assumes it is not `None`.
> Remove `Optional` from `processing_class` in `PPOTrainer`

- docs/source/lora_without_regret.md
Update LoRA params in Python
`lora_r` is `r` in `LoraConfig`. Same for `lora_target_modules`. It's `target_modules`. It's correct for the rest of the cases since it goes through TRL.
@burtenshaw
> Fix LoRA params in Python in LoRA without regret

- docs/source/lora_without_regret.md
This make the text about lr match the figures in the above table.
> [DOCS] fix prose in lora guide
