huggingface/trl

.github/workflows/build_documentation.yml, .github/workflows/tests.yml
renames `master` to `main` in actions
=> update GitHub actions to `main`

docs/source/sentiment_tuning.mdx, examples/notebooks/gpt2-sentiment-ppo-training.ipynb, examples/scripts/ppo-sentiment-adam-8bit.py, examples/scripts/ppo-sentiment.py
=> Collater -> collator

tests/test_ppo_trainer.py, trl/trainer/ppo_trainer.py
This PR adds LR scheduler support. It adds also a nice CI test 
cc @lvwerra
=> [API] LR scheduler support

README.md, examples/sentiment/scripts/gpt2-sentiment.py
This PR fixes few things:
1- missing function in the example script
2- slight refactor of the readme
cc @lvwerra
=> Fix nits & missing things

trl/core.py
@natolambert quickly adding your fix to the patch release. We can continue the rest on the other PR.
=> Fix `Mapping` in core for Python 3.10

docs/source/models.mdx, docs/source/trainer.mdx, tests/trainer/test_ppo_trainer.py
This PR is just a small update to the docs.
=> update docs with Seq2seq models, set_seed, and create_reference_model

trl/trainer/ppo_trainer.py
This PR addresses comment #44. It seems to have no effect in convergence and makes the code more consistent. 
W&B logs: https://wandb.ai/lvwerra/trl/runs/4ap5xup6
=> realign values

tests/trainer/test_ppo_trainer.py
This PR replaces `gpt2` with a tiny `gpt2` with a correct `vocab_size` to make tests faster
cc @lvwerra
=> [`tests`] Add correct repo name

tests/trainer/test_ppo_trainer.py, trl/trainer/ppo_trainer.py
Fixes #148 - adds also a cool test
cc @lvwerra @edbeeching
=> [`core`] Fix dataloader issue

examples/sentiment/notebooks/gpt2-sentiment.ipynb
Made a new clean pull request with only the changes. Please ignore the other one.
=> Added imports

examples/sentiment/scripts/gpt2-sentiment_peft.py
cc @edbeeching 
needs to use it with https://github.com/huggingface/peft/pull/121 !
=> Fix peft + int8

examples/sentiment/notebooks/gpt2-sentiment.ipynb
Fix some bugs in `examples/sentiment/notebooks/gpt2-sentiment.ipynb`.
- replace `tokens` with `input_ids` during model inspection.
- added a line to import pandas. `import pandas as pd`
=> fix bugs in tutorial

docs/source/detoxifying_a_lm.mdx
This PR replaces the previous plot of toxicity example with a nice TRL-themed barplot 
cc @lvwerra
=> [`Docs`] Fix barplot

examples/toxicity/scripts/evaluate-toxicity.py
Allow running evaluate-toxicity with cpu
=> Allow running evaluate-toxicity with cpu

Makefile, examples/sentiment/scripts/gpt2-sentiment.py, examples/sentiment/scripts/t5-sentiment.py, examples/summarization/scripts/reward_summarization.py, examples/toxicity/scripts/evaluate-toxicity.py, examples/toxicity/scripts/gpt-j-6b-toxicity.py
Fixes quality check that were not being run on the examples to avoid extra files being modified such as in https://github.com/lvwerra/trl/pull/190
cc @lvwerra
=> [`core`] Fix quality issue

trl/trainer/ppo_trainer.py
PR #220 did not detach the logprob ratio.
=> adds a missing detach to the ratio

trl/trainer/ppo_config.py
The lines were swapped and the text didn't match.
=> Fix swapped helper texts

examples/sentiment/notebooks/gpt2-sentiment.ipynb
=> fix typo in gpt2-sentiment.ipynb

examples/stack_llama/scripts/rl_training.py
Fix arguments description, `output_max_length` was descripted as "the learning rate"
=> Fix arguments description

trl/trainer/ppo_trainer.py
trl/trainer/ppo_trainer.py has a small typo in line 511
=> fixed typo in error message

docs/source/customization.mdx
Addresses: https://github.com/lvwerra/trl/issues/317#issuecomment-1521454031 
I think we should give minimal instructions on how to run your scripts on multiple GPUs & nodes
=> [`Docs`] Add details on multi-GPU / multi-node

docs/source/sft_trainer.mdx, trl/trainer/sft_trainer.py
This PR fixes minor issues with SFT (in fact I forgot to push the last changes before merging #323 )
cc @lvwerra
=> [`SFT`] Fix sft issues

examples/stack_llama/scripts/reward_modeling.py
Thanks for the great project.
This PR fixes a minor issue in the argument's description.
=> Fix argument's description

trl/trainer/ppo_trainer.py
Addresses https://github.com/lvwerra/trl/pull/315#issuecomment-1525832522
With #315 being merged, the tensorboard logging was slightly broken. This PR fixes that issue by adding a small check
cc @lvwerra
=> [`PPOTrainer`] Fix tensorboard issue

trl/trainer/ppo_trainer.py
=> [`core`] Fix warning issue

docs/source/lora_tuning_peft.mdx, trl/models/modeling_base.py, trl/trainer/ppo_trainer.py
Adds 4bit QLora quantization support to TRL
Related: https://github.com/huggingface/transformers/pull/23479
Users just needs to replace `load_in_8bit` with `load_in_4bit`
=> [`core`] Add 4bit QLora

trl/trainer/sft_trainer.py
=> [`bnb`] fix 4 bit SFT

setup.py
Related: https://github.com/huggingface/accelerate/pull/1561
cc @lvwerra
=> Pin accelerate version

setup.py
as per title 
check: https://github.com/huggingface/accelerate/releases/tag/v0.20.2
cc @lvwerra
=> [`core`] unpin accelerate

.github/workflows/stale.yml, scripts/stale.py
As per title. This PR copies the stale bot from PEFT: https://github.com/huggingface/peft/blob/main/scripts/stale.py originally copied from transformers, originally inspired from a repo from AllenAI
cc @lvwerra @vwxyzjn
=> [`core`] Add stale bot

docs/source/logging.mdx, examples/sentiment/scripts/gpt-neo-1b-multi-gpu/gpt-neo-1b_peft.py, examples/sentiment/scripts/gpt-neox-20b_peft/gpt-neo-20b_sentiment_peft.py, examples/sentiment/scripts/gpt2-sentiment.py, examples/sentiment/scripts/gpt2-sentiment_peft.py, examples/toxicity/scripts/gpt-j-6b-toxicity.py, trl/trainer/ppo_config.py, trl/trainer/ppo_trainer.py
accelerate moved from `logging_dir` to use ProjectConfiguration, updating examples to reflect.
=> Update accelerate arg passthrourgh for tensorboard logging to reflect logging_dir deprecation.

examples/multi-adapter-rl/reward_modeling.py
pass `gradient_checkpointing` to both `prepare_model` and `TrainingArgs` 
switch from discontinued `int8` to new peft `kbit` api
pass `max_length` to `RewardTrainer`
=> correctly implement gradient checkpointing to multi-adapter example

examples/scripts/sentiment_tuning.py
Fixes a small nit on sentiment script
cc @lvwerra
=> [`examples`] Fix sentiment nit

trl/trainer/ppo_trainer.py
FIxes https://github.com/lvwerra/trl/issues/530
I propose to add a (risky) bare except to handle the offline cases
cc @lvwerra
=> [`core`] Fix offline case

trl/trainer/dpo_trainer.py, trl/trainer/reward_trainer.py
Fixes https://github.com/lvwerra/trl/issues/535
We should relax the constraint for users in case they implement their own Data collator when using `RewardTrainer`.
cc @lvwerra
=> Relax reward trainer constraint

trl/trainer/dpo_trainer.py, trl/trainer/utils.py
removed unused argument to collator
=> [DPO] remove unnecessary batch size arg to Collator

examples/scripts/sft_trainer.py
Added save the model, because by default it saves only checkpoints not the final version.
=> Update the example sft_trainer.py

setup.py, trl/__init__.py
=> Release: v0.5.0

setup.py, trl/__init__.py
=> Set dev version

docs/source/dpo_trainer.mdx, examples/research_projects/README.md, examples/research_projects/stack_llama_2/scripts/README.md, examples/research_projects/stack_llama_2/scripts/dpo_llama2.py, examples/research_projects/stack_llama_2/scripts/requirements.txt, examples/research_projects/stack_llama_2/scripts/sft_llama2.py
Training scripts for the DPO training of stack-llama-2 via a 7B model
=> [DPO] stack-llama-2 training scripts

examples/dpo.py, trl/trainer/__init__.py, trl/trainer/dpo_trainer.py, trl/trainer/utils.py
Helps stabilising training.
For now, I only added `disable_dropout` to DPO Training, but let me know if you think it should go to `DPOTrainer` with a config to disable
cc @kashif
=> Disable dropout in DPO Training

README.md, tests/test_ppo_trainer.py, trl/trainer/ppo_config.py, trl/trainer/utils.py
=> Add checks on backward batch size

examples/research_projects/stack_llama_2/scripts/sft_llama2.py
Addressed https://github.com/huggingface/trl/issues/629#issuecomment-1683538661 and fixes #629
cc @lvwerra
=> [`sft_llama2`] Add check of arguments

setup.py, trl/__init__.py
=> Release: v0.6.0

setup.py, trl/__init__.py
=> Release: v0.7.1

docs/source/learning_tools.mdx
=> Update docs on gms8k

setup.py
Fixes https://github.com/huggingface/trl/issues/580
cc @lvwerra
=> [`core`] Bump peft to 0.4.0

trl/trainer/dpo_trainer.py
=> [DPO] fixed metrics typo

.github/workflows/benchmark.yml
This PR adds the benchmark CI workflow so that we can follow up with separate PRs to trigger it.
=> Add benchmark CI

docs/source/dpo_trainer.mdx, examples/dpo.py, trl/trainer/utils.py
Instead of asserts, mask out EOS tokens in the attention mask to.
my dev setup for TRL is out of day. Will fix the precommit stuff.
CC @kashif
=> EOS token processing for multi-turn DPO

examples/dpo.py
Comparison here: https://wandb.ai/huggingface/huggingface/reports/RMSProp-DPO--Vmlldzo1Mzc2NDQ3
=> Add default Optim to DPO example

docs/source/sft_trainer.mdx
Fixes https://github.com/huggingface/trl/issues/786
Adds a simple sentence on how to continue training with adapters
cc @lvwerra
=> [`Docs`] Clarify PEFT docs

docs/source/sft_trainer.mdx
as https://github.com/huggingface/transformers/pull/25598 will be merged, let's emphasize that you can use flash attention
cc @lvwerra for your information
=> Update sft_trainer.mdx to highlight Flash Attention features

examples/dpo.py
To be merged only after https://github.com/huggingface/transformers/pull/26425 is merged, and we update `setup.py` for the needed version of this.
I installed the transformers PR from source and ran with the DPO script, looks to be running 🤗
=> Add RMSProp back to DPO

trl/trainer/dpo_trainer.py
=> [DPO] add option for compute_metrics in DPOTrainer

docs/source/ppo_trainer.mdx
One outstanding issue is that ppo_trainer.save_model doesn't exist. How do we actually save the model after training?
=> Small fixes to the PPO trainer doc and script.

setup.py, trl/__init__.py
=> Release: v0.7.2

docs/source/dpo_trainer.mdx, tests/test_dpo_trainer.py, trl/trainer/dpo_trainer.py
from the [RSO paper]( https://arxiv.org/pdf/2309.06657.pdf) equation (12)
#816
=> [DPO] add SLiC hinge loss to DPOTrainer

examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
Fixes #926 
I think there was a typo or a mistake in the DPO stack-llama 2 script that I explained here: https://github.com/huggingface/trl/issues/926#issuecomment-1787389686
cc @kashif @lvwerra
=> Fix dpo_llama2.py

scripts/stale.py
Fixes similar patch than https://github.com/huggingface/accelerate/pull/2052/
cc @lvwerra
=> Fix stale bot

setup.py, trl/__init__.py
=> Release: v0.7.3

.github/workflows/tests.yml, setup.py, tests/test_ddpo_trainer.py, tests/testing_utils.py
This PR adds in the test workflow a workflow to test TRL testing suite without optional packages as we were not able to flag some minor issues that can occur during releases, e.g. https://github.com/huggingface/trl/pull/967
cc @lvwerra
=> [`Tests`] Add non optional packages tests

trl/trainer/dpo_trainer.py
This reverts commit 6d9ea38ae18c7e266f797b62de4a68a12a13aba4.
=> Revert "[DPO] Refactor eval logging of dpo trainer (#954)"

trl/trainer/dpo_trainer.py
The same problem as described in #877, just with the reference model.
=> Fix DPOTrainer + PEFT 2

trl/import_utils.py
This if always evaluates true since the function is never called
=> Fixing accelerator version function call.

setup.py
The description in `setup.py` was outdated and I've aligned it with the one within the repository.
=> Update `description` in `setup.py`

trl/trainer/dpo_trainer.py
=> [DP0] save eval_dataset for subsequent calls

setup.py, trl/__init__.py
=> Release: v0.7.5

setup.py, trl/__init__.py
=> Release: v0.7.6

examples/scripts/ppo_multi_adapter.py
Add npu support for `examples/script/ppo_multi_adapter.py`
=> Add npu support for ppo example

setup.py, trl/__init__.py
=> Release: v0.7.7

trl/trainer/sft_trainer.py, trl/trainer/utils.py
Issue [#1122](https://github.com/huggingface/trl/issues/1122)
takes care of an inconsistency between `_prepare_packed_dataloader`
and `_prepare_non_packed_dataloader`
Fixes #1122
=> Address issue #1122

setup.py, trl/__init__.py
=> Release: v0.7.8

trl/trainer/sft_trainer.py, trl/trainer/utils.py
=> Revert "Address issue #1122"

setup.py, trl/__init__.py
=> Release: v0.7.9

trl/trainer/utils.py
1. adjust the parameter description.
2. Correct the parameter type in the comment.
=> Fix args type

.github/workflows/slow-tests.yml
cc @lvwerra @glegendre01 as discussed offline, I need to first merge this PR to test https://github.com/huggingface/trl/pull/1218 in order to trigger the workflow
=> Add slow test workflow file

trl/trainer/sft_trainer.py
fixes the current slow CI that is red cc @lvwerra
=> Fixes slow tests

trl/trainer/utils.py
Fixes a bug in the docs
https://huggingface.co/docs/trl/sft_trainer#answer-answer
cc @lvwerra
=> Fix weird doc bug

trl/trainer/dpo_trainer.py, trl/trainer/ppo_trainer.py, trl/trainer/reward_trainer.py
1. Fixed loss_type, "kto" -> "kto_pair"
2. Fixed some bugs related to parameter description
=> fix: fix loss_type and some args desc

setup.py, trl/__init__.py
=> Release: v0.7.10

trl/models/utils.py
This PR updates the generation config, which is used by default when using model.generate. Therefore we should update the token ids to make sure user has the expected behavior. 
cc @younesbelkada
=> Update Model Generation config to reflect new special tokens

trl/trainer/sft_trainer.py
Currently the TRL gpu CI is broken after #1255 - this PR fixes it
cc @lvwerra FYI
=> FIx SFTTrainer bugs on TRL main

tests/test_dpo_trainer.py, trl/trainer/dpo_trainer.py
This tiny PR add support for multi process preprocessing in the DPO trainer. 
Added support for num_proc to tokenize the training dataset.
=> Add multiprocessing in the DPO trainer.

docs/source/sft_trainer.mdx
As requested here: https://github.com/huggingface/trl/issues/1303#issuecomment-1920437586
Fixes #1303
=> Update sft_trainer.mdx to add note on launching DDP training

.github/workflows/tests.yml
=> ENH: Run CI only if relevant files are modified

docs/source/multi_adapter_rl.mdx
Just fixed up a few typos, nothing really significant
=> Fix typos in docs for Multi Adapter RL (MARL).

setup.py, trl/__init__.py
=> Release: v0.7.11

examples/research_projects/stack_llama_2/scripts/dpo_llama2.py
Update example to accommodate for changes made in [#aa35fec](https://github.com/huggingface/trl/commit/aa35fec0997095a59bd9c49993a675ec4adc6d04)
=> Update stack llama 2 example to reflect #aa35fec

trl/trainer/utils.py
Fixes https://github.com/huggingface/trl/issues/1349
cc @lvwerra
=> FIX: More user friendly error when users don't have PEFT

tests/test_kto_trainer.py, trl/trainer/kto_trainer.py
exception if there is no eval dataset
=> [KTO] merge eval dataset only if it exists

.github/workflows/tests-main.yml, .github/workflows/tests.yml, tests/test_cli.py, trl/commands/cli.py
To avoid silent failures
cc @lvwerra
=> CI / CLI: Properly raise error when CLI tests failed

setup.py, trl/__init__.py
=> Release: v0.8.0

setup.py, trl/__init__.py
=> Release: v0.8.1

README.md, commands/run_dpo.sh, docs/source/clis.mdx, example_config.yaml, examples/scripts/dpo.py, tests/test_cli.py, trl/commands/cli_utils.py
This PR uses the standard dataset created in #1424 and also updates the DPO CLI docs.
=> Use the standard dataset for DPO CLI

.gitignore, docs/source/clis.mdx
Ignores files created by symlinking from `make dev`
=> Ignore chat files

README.md
=> Add DPO link in README

trl/trainer/reward_trainer.py
To be consistent with other TRL Trainers + avoid issues such as: https://github.com/huggingface/transformers/pull/30126
=> FIX: use kwargs for RMTrainer

trl/__init__.py
=> [CLI] fix imports

trl/trainer/cpo_trainer.py
=> [CPO] fix memory leak due to retained value

commands/run_sft.sh
Forgot to add the changes of #1545 so that the text will run the correct command
cc @lvwerra
=> FIX: Fix slow test

examples/scripts/sft.py, trl/commands/cli_utils.py
cc @lvwerra 
Fixes: https://github.com/huggingface/trl/issues/1487
=> FIX: make the train / test fields modulable

trl/commands/cli_utils.py
Fixes https://github.com/huggingface/trl/issues/1564
=> CLI: Add warning when ignored params are passed + parse config file if config if passed

setup.py, trl/__init__.py
=> Release: v0.8.6

setup.py
Fixes https://github.com/huggingface/trl/issues/1606
=> Removing `tests/` from package data

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml
as per title and discussed offline
cc @mishig25 @Wauplin
=> Docs: Fix build main documentation

docs/source/dpo_trainer.mdx, tests/test_dpo_trainer.py, trl/trainer/dpo_config.py, trl/trainer/dpo_trainer.py
corrects implementation mentioned in https://github.com/huggingface/trl/pull/1612. arxiv: https://arxiv.org/abs/2405.00675
=> corrects loss function for Self-play Preference Optimization hard label version

trl/trainer/kto_trainer.py
This PR fixes the issues with KTOTrainer logs described here #1631 
Fixes: https://github.com/huggingface/trl/issues/1631
=> Fixed wrong logs prefixes in KTOTrainer

docs/source/dpo_trainer.mdx, tests/test_dpo_trainer.py, trl/trainer/dpo_config.py, trl/trainer/dpo_trainer.py
Paper: https://arxiv.org/pdf/2402.05369
This adds pairwise preference NCA loss to the DPO trainer.
=> Pairwise Noise Contrastive Alignment

trl/trainer/ppo_trainer.py
Fixes: https://github.com/huggingface/trl/issues/1629
Adds the possibility for users to pass a custom datacollator for training - see that issue for more details
cc @vwxyzjn
=> FEAT: Add support for training collator in PPOTrainer

tests/test_dpo_trainer.py, tests/test_kto_trainer.py, tests/test_sft_trainer.py
fix some remaining `eval_strategy` calls missed by #1559 and add some tests for #1653
=> [Tests] update eval_strategy API

trl/trainer/sft_trainer.py
FIxes: https://github.com/huggingface/trl/issues/1656 
Follows the same approach as in HF trainer: https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/trainer.py#L385
cc @kashif @vwxyzjn
=> FIX / SFTTrainer: Fix SFTTrainer with `args=None`

docs/source/sft_trainer.mdx, trl/trainer/sft_trainer.py
Fixed a few things in the docs, typing and doc strings related to the SFTCfongi change. Mostly nit picks, but this actually confused me when trying to use the new version of TRL.
Lmk if I need to change / add anything -- first time contributor 😅
=> Fixed doc string and related docs for the SFTConfig update

setup.py, trl/__init__.py
Patch release to fix some backward compatibility issues.
=> 0.9.4 release

.github/workflows/docker-build.yml, .github/workflows/tests-main.yml
As per title for the trl + transformers main CI and docker image build CI
cc @vwxyzjn FYI - we use that workflow on other libs successfully: https://github.com/huggingface/peft/blob/25c0fe9a551350749426d7c0a8464db32c0cb2b6/.github/workflows/build_docker_images.yml#L48
=> Workflow: Notify tests results on slack channel

examples/scripts/dpo.py
=> change the `process` function in the example of DPO

tests/test_dpo_trainer.py
`evaluation_strategy` is deprecated.
=> `evaluation_strategy` to `eval_strategy`

examples/datasets/tldr_preference.py
Remove the leading space to be consistent with other TRL preference datasets.
=> Remove the leading space in the tldr preference dataset

.github/workflows/benchmark.yml, .github/workflows/clear_cache.yml, .github/workflows/docker-build.yml, .github/workflows/slow-tests.yml, .github/workflows/stale.yml, .github/workflows/tests-main.yml, .github/workflows/tests.yml
Fixes the deprecation warnings in the CI
=> Upgrade GitHub actions

tests/test_rich_progress_callback.py, trl/__init__.py, trl/trainer/__init__.py, trl/trainer/callbacks.py, trl/trainer/dpo_trainer.py, trl/trainer/sft_trainer.py, trl/trainer/utils.py
move trainer callbacks to their own file from utils
=> refactor trainer callbacks

README.md, docs/source/customization.mdx, docs/source/dpo_trainer.mdx, docs/source/kto_trainer.mdx, docs/source/quickstart.mdx, examples/hello_world.py, examples/notebooks/gpt2-sentiment-control.ipynb, examples/notebooks/gpt2-sentiment.ipynb, examples/research_projects/tools/calculator.py, examples/scripts/bco.py, examples/scripts/dpo.py, examples/scripts/dpo_visual.py, examples/scripts/kto.py, tests/test_ppo_trainer.py
Fortunately, no breaking change
=> Uniform `model_ref` naming

trl/trainer/kto_trainer.py
@kashif Hi, I submit the fix here for issue #1834
=> Fix issues of KTOTrainer

examples/accelerate_configs/fsdp_qlora.yaml, trl/trainer/utils.py
add fsdp_qlora config and bnb_4bit_quant_storage
=> fix fsdp & qlora support

docs/source/sft_trainer.mdx
…nOnlyLM
Added ```dataset_text_field``` in the SFTConfig while training
=> Bug Fix while training using SFTTrainer with DataCollatorForCompletionOnlyLM

tests/test_modeling_value_head.py
Llama is now fully supported. Follows #261
=> Llama in modelling value head tests

tests/test_modeling_value_head.py
@kashif for some reason, https://github.com/huggingface/trl/pull/1876 didn't work, can you approve this one?
=> Re-add BigBird Pegasus save/load test

tests/test_online_dpo_trainer.py
`evaluation_strategy` is deprecated
=> `evaluation_strategy` -> `eval_strategy`

examples/scripts/orpo.py
Fixes #1886
Fixes #1582
```
Hi, I want to learn to play horseshoes. Can you teach me?
```
```
<|im_start|>user
Hi, I want to learn to play horseshoes. Can you teach me?<|im_end|>
<|im_start|>assistant
I can, but maybe I should begin by telling you that a typical game consists of 2 players and 6 or 8 horseshoes.<|im_end|>
<|im_start|>user
Okay. What else is needed to play, and what are the rules?<|im_end|>
<|im_start|>assistant
A horseshoe is usually made out of metal and is about 3 to 3.5 inches long and around 1 inch thick. The horseshoe should also have a 2 inch by 3 inch flat at the bottom where the rubber meets the metal. We also need two stakes and six horseshoes.<|im_end|>
```
Rejected:
```
<|im_start|>user
Hi, I want to learn to play horseshoes. Can you teach me?<|im_end|> …
```
=> Fix data processing in ORPO example script

scripts/stale.py
A lot of issues are closed before being answered. I think unanswered issues shouldn't be closed automatically.
=> Don't mark issues as stale if nobody answered

Makefile, setup.py
Fixes flaky tests with Hub timeouts by enabling a rerun mechanism. See internal Slack thread: https://huggingface.slack.com/archives/C02EMARJ65P/p1718635566000569?thread_ts=1718631080.742169&cid=C02EMARJ65P
=> Fix flaky Hub tests

Makefile
In #1981 I noticed that the tests weren't actually run for some reason and the PR got merged while I was trying to figure out what went wrong. This PR restores the reuns - for some reason it is still only showing 2 checks, but I propose we merge and see if `main` works as intended
=> Restore reruns for flaky tests

trl/models/modeling_base.py
=> `torch.load` with `weights_only=True`

.github/workflows/slow-tests.yml
=> move slow-tests CI to new cluster

examples/scripts/dpo_online.py, setup.py, tests/slow/test_sft_slow.py, tests/test_online_dpo_trainer.py, tests/testing_utils.py, trl/__init__.py
update the script and run the online dpo tests
=> [Online-DPO] fixes to the training scripts and setup.py

trl/core.py
It removes unused functions in `core.py`. I could not find any usage of them and these are probably old remnants of previous code, but if these are support functions and are used, just let me know and I'll close the PR.
=> Remove unused functions in `core.py`

.github/workflows/tests-main.yml, .github/workflows/tests.yml
Tests that the fix on `transformers` fixes the CI here
=> [Draft, don't merge] Fix failing windows

examples/scripts/gkd.py
I added the wrong dataset name in a prior commit 🙈. 
=> Fix dataset in GKD script

trl/trainer/bco_trainer.py, trl/trainer/dpo_trainer.py
https://github.com/huggingface/transformers/pull/32858 introduced a breaking change. The order of arg in processor must be reverted.
Cause of https://github.com/huggingface/trl/actions/runs/10899672686/job/30245604639#step:5:3406
Also added a missing commit from #2057: handle special case where `model` is `str` in `BCOTrainer`
Fixes the CI
=> `processor(prompt, images=image)` to `processor(images=image, text=prompt)`

examples/scripts/orpo.py
Fixes a typo in the ORPO example.
=> Fix typo in ORPO example.

trl/trainer/sft_trainer.py
In https://github.com/huggingface/transformers/pull/33154, logic was introduced to fix `low_cpu_mem_mode`, in which the weights will be accordingly moved to either `cpu` or `meta` device depending on device rank. However, this causes a problem here as `is_sharded_qlora` could then be potentially set to `True` on device `0` and `False` on all others. 
This PR fixes this problem which will be experienced in the upcoming transformers release.
Fixes [transformers#33154](https://github.com/huggingface/transformers/pull/33154)
@mdouglas
members/contributors who may be …
=> Fix Inconsistency with IsSharedQLoRA Setting

docs/source/nash_md_trainer.md, docs/source/online_dpo_trainer.md, docs/source/xpo_trainer.mdx
=> Fix documentation links

tests/test_sft_trainer.py
A test is failing after I've updated the chat template of gpt2: https://huggingface.co/trl-internal-testing/dummy-GPT2-correct-vocab/commit/817d77b56056283e8f9df3a4e10d76d8d2132d79
The issue with the chat template was that
```python
tok.apply_chat_template(prompt, add_generation_prompt=True) + tok.apply_chat_template(completion) != tok.apply_chat_template(prompt + completion)
```
Which is a needed.
So the new chat template produces longer sequences, and the number of packed sequences increases.
=> Fix pack test

docs/source/nash_md_trainer.md, docs/source/online_dpo_trainer.md, docs/source/xpo_trainer.mdx
Almost had a stroke reading the part about EOS token encouragement in the MD, online DPO, and XPO trainers. This PR clears up the confusing wording.
=> Eos token encouragement Clarification

examples/datasets/hh-rlhf-helpful-base.py, examples/datasets/lm-human-preferences-descriptiveness.py, examples/datasets/lm-human-preferences-sentiment.py, examples/datasets/tldr.py, examples/datasets/tldr_preference.py, examples/datasets/tokenize_ds.py, examples/datasets/ultrafeedback-prompt.py, examples/datasets/ultrafeedback.py, examples/datasets/zen.py, examples/research_projects/tools/python_interpreter.py, examples/research_projects/tools/triviaqa.py, examples/scripts/alignprop.py, examples/scripts/bco.py, examples/scripts/cpo.py, examples/scripts/ddpo.py, examples/scripts/dpo.py, examples/scripts/dpo_online.py, examples/scripts/dpo_visual.py, examples/scripts/evals/judge_tldr.py, examples/scripts/gkd.py, examples/scripts/nash_md.py, examples/scripts/orpo.py, examples/scripts/ppo.py, examples/scripts/reward_modeling.py, examples/scripts/sft.py, examples/scripts/sft_vlm.py, examples/scripts/xpo.py
Instances of `ScriptArguments` are named `script_args`
=> ♻️ Standardize `script_args`

CONTRIBUTING.md, trl/trainer/bco_trainer.py, trl/trainer/gkd_trainer.py
=> arXiv to HF Papers

trl/trainer/callbacks.py
Small fix to make it clear in WandB which table it which
=> Add correct label for `WinRateCallback` table

examples/scripts/chat.py, trl/commands/cli.py
Fixes #2146 and run chat cli with python instead of accelerate (bug introduced in #2104)
=> Fix attention mask warning chat cli

trl/trainer/bco_trainer.py, trl/trainer/cpo_trainer.py, trl/trainer/dpo_trainer.py, trl/trainer/iterative_sft_trainer.py, trl/trainer/kto_trainer.py, trl/trainer/orpo_trainer.py, trl/trainer/ppov2_trainer.py, trl/trainer/rloo_trainer.py
Revert #2163 since https://github.com/huggingface/transformers/pull/33911 is merged
=> ↩️ Revert tokenizer hotfix #2163

tests/test_cli.py
=> chore: update test_cli.py

docs/source/alignprop_trainer.mdx, docs/source/bco_trainer.mdx, docs/source/cpo_trainer.mdx, docs/source/ddpo_trainer.mdx, docs/source/dpo_trainer.mdx, docs/source/gkd_trainer.md, docs/source/iterative_sft_trainer.mdx, docs/source/kto_trainer.mdx, docs/source/nash_md_trainer.md, docs/source/online_dpo_trainer.md, docs/source/orpo_trainer.md, docs/source/ppo_trainer.mdx, docs/source/ppov2_trainer.md, docs/source/reward_trainer.mdx, docs/source/rloo_trainer.md, docs/source/sft_trainer.mdx, docs/source/xpo_trainer.mdx
=> 🏷️ Model badges in trainer documentation

README.md, docs/source/cpo_trainer.mdx, docs/source/dpo_trainer.mdx
Fixes #2176 
@qgallouedec 
Did I miss any?
=> Capybara replaced with ultrafeedback_binarized

.github/workflows/tests.yml
=> [CI] Use transformers from source in "tests_no_optional_dep"

trl/trainer/dpo_trainer.py
To resolve #2197, this PR makes DPOTrainer to access and store `router_aux_loss_coef` in the model config before the model is wrapped. A warning is also added to make it easier to know if the coefficient is 0, which makes aux_loss meaningless.
Fixes #2197 
Below is the patch and the output of the script I shared in https://github.com/huggingface/trl/issues/2197#issue-2572091940. I confirmed that the specified value is used as a coefficient.
```patch
diff --git a/trl/trainer/dpo_trainer.py b/trl/trainer/dpo_trainer.py
index ce21afd..418c4df 100644
--- a/trl/trainer/dpo_trainer.py
+++ b/trl/trainer/dpo_trainer.py
@@ -1523,6 +1523,8 @@ class DPOTrainer(Trainer):
metrics[f"{prefix}nll_loss"] = policy_nll_loss.detach().mean().cpu()
if self.aux_loss_enabled:
+            print("type(model):", …
```
=> Fix the bug of DPOTrainer where the coefficient of aux_loss is always 0 during training

trl/trainer/gkd_trainer.py
fix the JSD by interpolating in the prob. space
fixes #2202
=> [GKD] interpolate in prob. space

tests/test_judges.py, trl/trainer/judges.py
Add a flag to return the probability of the first completion being preferred over the 2nd instead of a hard judge
=> [Judges] Soft judges for PairRM

docs/source/bco_trainer.mdx, docs/source/cpo_trainer.mdx, docs/source/dataset_formats.mdx, docs/source/dpo_trainer.mdx, docs/source/gkd_trainer.md, docs/source/kto_trainer.mdx, docs/source/nash_md_trainer.md, docs/source/online_dpo_trainer.md, docs/source/orpo_trainer.md, docs/source/reward_trainer.mdx, docs/source/xpo_trainer.mdx, tests/test_data_utils.py, trl/data_utils.py
I realize that there are many instances of confusion between dataset type and format. this PR solves them.
=> 📒 Fix type/format confusions

trl/commands/cli_utils.py
Fixes #2229
- [*] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
@qgallouedec
=> Updated `ScriptArguments` warning messages

trl/commands/cli.py
Fixes #2234 
```python
capture_output=True
```   
prevented outputs from being printed
@qgallouedec
=> Setting capture output to False

scripts/log_reports.py
This PR introduces several improvements to the `log_reports.py` script, including:
1. **Logging Enhancements:**
- Added a context-managed `setup_logging` function to configure logging with a more detailed format for better debugging.
2. **File Processing Refactor:**
- Created a new `process_log_file` function to encapsulate log file processing, reducing redundancy and improving error handling.
- Enhanced error handling to include specific exceptions like `FileNotFoundError` and `JSONDecodeError` for more precise logging.
3. **Slack Payload Handling Improvements:**
- Refactored the Slack message preparation to improve readability and structure.
- Included a fallback message when the total message length exceeds the maximum allowed.
4. **Code Cleanup:**
- Improved code readability by …
=> Refactor `log_reports.py` for Improved Logging, File Processing, and Slack Payload Handling

examples/scripts/bco.py, examples/scripts/cpo.py, examples/scripts/dpo.py, examples/scripts/dpo_online.py, examples/scripts/dpo_vlm.py, examples/scripts/gkd.py, examples/scripts/kto.py, examples/scripts/nash_md.py, examples/scripts/orpo.py, examples/scripts/ppo/ppo_tldr.py, examples/scripts/reward_modeling.py, examples/scripts/rloo/rloo_tldr.py, examples/scripts/sft.py, examples/scripts/sft_vlm.py, examples/scripts/xpo.py
=> Don't pass `eval_dataset` in to trainers when no eval strategy

trl/trainer/judges.py
=> 🧽 Fix judge doc

trl/trainer/dpo_trainer.py
Fixes the CI for the dev dependencies.
Not sure why it's needed but probably minor.
=> 🪪 Check with `token_id` instead of `token` in `DPOTrainer`

setup.py
This fixes HF grad acc and other fixes/features/optimizations
=> Bump liger-kernel to 0.4.0

trl/trainer/dpo_trainer.py
Remove unnecessary version check: https://github.com/huggingface/trl/pull/2129#discussion_r1835666295
=> 💣  Remove transformers version check

examples/scripts/sft_video_llm.py
=> Adding video llm fine-tuning example

trl/trainer/bco_trainer.py, trl/trainer/gkd_trainer.py, trl/trainer/iterative_sft_trainer.py, trl/trainer/nash_md_trainer.py, trl/trainer/xpo_trainer.py
=> 👋 Remove deprecated `tokenizer` argument in BCO, GKD, Iterative SFT, Nash MD and XPO

Makefile
Fixes an issue where repeated use of `make dev` fails due to the symbolic link creation. The fix is to check/unlink an existing symlink and recreate it if needed.
=> Fix dev install

trl/trainer/online_dpo_trainer.py
Follows https://github.com/huggingface/transformers/pull/34507
cc @SunMarc @muellerzr for visibility
=> ⏰ Add `start_time` to `_maybe_log_save_evaluate`

examples/datasets/hh-rlhf-helpful-base.py
Fixed a Typo in the dataset converge example for hh-rlhf
- [Y] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
=> 📝 Fix typo in dataset generation script

trl/trainer/bco_trainer.py, trl/trainer/cpo_trainer.py, trl/trainer/dpo_trainer.py, trl/trainer/kto_trainer.py, trl/trainer/orpo_trainer.py
Some missing occurences from #2373 
=> ⌛ Update log method to include `start_time` parameter

trl/trainer/ppo_trainer.py
2 warnings were forget in #2392 
=> 🤐 Fix deprecation warnings

trl/trainer/kto_trainer.py
Currently you've a indentation when warning is raised
=> 🖋️ Fix warning message formatting in `KTOTrainer`

docs/source/_toctree.yml, docs/source/script_utils.md, trl/commands/cli_utils.py, trl/utils.py
=> 🖨 Add Script Utilities section to the documentation

trl/models/modeling_base.py
Hi thanks for the lib! When looking at source code (indeed looking at DPO code) there seems to be a super tiny typo.
=> Super tiny typo fix

docs/source/rloo_trainer.md
Doc has different grad_accumulation_steps and per_device_batch size than the actual hyperparameters, can be verified from the official wandb [run](https://wandb.ai/huggingface/trl/runs/u2sqci34/overview).
=> 🗂️ Harmonize run and example batch sizes in RLOO docs

.github/workflows/tests_latest.yml
This workflow tests the latest version of TRL (currently in branch `v0.12-release`) daily to ensure compatibility with the development versions of required dependencies (`datasets`, `accelerate`, and `transformers`). 
By running these tests, we can quickly identify and address breaking changes in these libraries before they are released.
This workflow currently fails because we removed old tiny models as part of #2287.
=> ⚖️ Add `tests_latest.yml` workflow file

docs/source/community_tutorials.md
=> 🎞️ Add "Fine-tuning open AI models using Hugging Face TRL" YouTube video to community tutorials

docs/source/customization.mdx
=> 📥 Fix missing `BitsAndBytesConfig` import in doc

docs/source/dpo_trainer.mdx, docs/source/index.mdx, docs/source/orpo_trainer.md, docs/source/sft_trainer.mdx
=> 👨‍🏫 smol course links and badges

trl/trainer/utils.py
Fixes `formatting_func`'s documentation in ConstantLengthDataset.
=> ✒️ Fix typo in `formatting_func`'s documentation in `ConstantLengthDataset`

docs/source/rloo_trainer.md, trl/trainer/rloo_config.py, trl/trainer/rloo_trainer.py
Add suggestions from the Reinforce++ report to the RLOO trainer.
=> [RLOO] Reinforce++

trl/trainer/alignprop_trainer.py, trl/trainer/bco_trainer.py, trl/trainer/cpo_trainer.py, trl/trainer/ddpo_trainer.py, trl/trainer/dpo_trainer.py, trl/trainer/gkd_trainer.py, trl/trainer/iterative_sft_trainer.py, trl/trainer/kto_trainer.py, trl/trainer/nash_md_trainer.py, trl/trainer/online_dpo_trainer.py, trl/trainer/orpo_trainer.py, trl/trainer/ppo_trainer.py, trl/trainer/prm_trainer.py, trl/trainer/reward_trainer.py, trl/trainer/rloo_trainer.py, trl/trainer/sft_trainer.py, trl/trainer/xpo_trainer.py
=> ✨ Refine model card method docstring

.github/ISSUE_TEMPLATE/bug-report.yml
=> 🐛 Simplify bug report template

tests/test_dpo_trainer.py, tests/test_prm_trainer.py
CI broken after #2587 (merged to fast, sorry about that!)
=> 🫢 Add `max_prompt_length` parameter in tests

.github/workflows/build_pr_documentation.yml, trl/trainer/grpo_trainer.py
See https://github.com/huggingface/trl/issues/2608#issuecomment-2610270249
=> 💎 Rename an inner var in GRPO to improve clarity

trl/trainer/dpo_trainer.py
fixes issue reported in https://github.com/huggingface/transformers/issues/35856
=> 🥞 Fix DPO gradient accumulation loss scaling

trl/trainer/cpo_trainer.py
=> 🥞 Fix CPO gradient accumulation loss scaling 

trl/trainer/grpo_trainer.py
=> 🥞 Fix GRPO gradient accumulation loss scaling

trl/trainer/kto_trainer.py
=> 🥞 Fix KTO gradient accumulation loss scaling

docs/source/grpo_trainer.md, tests/test_grpo_trainer.py, trl/trainer/grpo_config.py, trl/trainer/grpo_trainer.py
=> 🚛 Provide all columns of the dataset to the reward function

trl/trainer/grpo_trainer.py
=> 📍 Disable caching when grad checkpointing enable in GRPO

docs/source/grpo_trainer.md, trl/trainer/grpo_trainer.py
=> 📏 Log completion length in GRPO

trl/trainer/grpo_config.py
=> 🌀 Fix GRPO default completion length doc

trl/trainer/grpo_trainer.py
=> 🏷️ Add model tags to model trained with GRPO

docs/source/bco_trainer.md, docs/source/ddpo_trainer.md, docs/source/detoxifying_a_lm.md, examples/datasets/hh-rlhf-helpful-base.py, examples/datasets/lm-human-preferences-descriptiveness.py, examples/datasets/lm-human-preferences-sentiment.py, examples/datasets/math_shepherd.py, examples/datasets/prm800k.py, examples/datasets/rlaif-v.py, examples/datasets/tldr.py, examples/datasets/tldr_preference.py, examples/datasets/ultrafeedback-prompt.py, examples/datasets/ultrafeedback.py, tests/test_data_utils.py, trl/trainer/gkd_trainer.py
=> 🖊 Fix typos

.github/workflows/tests_latest.yml, CITATION.cff, setup.py, trl/__init__.py
=> ⬆️ Bump dev version

docs/source/grpo_trainer.md
[open-r1#47](https://github.com/huggingface/open-r1/issues/47#issuecomment-2618020024)
=> 📄 Add GRPO batch size note in docs

docs/source/grpo_trainer.md
I noticed a typo in the documentation where "ingored" was used instead of "**ignored**."
I’ve corrected it to ensure the text reads clearly.
Anyone
=> 🙈 Fixed typo in the GRPO documentation

README.md
_I replaced RLOOTrainer with GRPOTrainer because you thought you might want to keep it limited, but let me know if you want both._
This PRs add GRPOTrainer to README.md
=> 📖 Add GRPOTrainer to README.md

tests/test_dpo_trainer.py, trl/trainer/dpo_config.py, trl/trainer/dpo_trainer.py, trl/trainer/grpo_trainer.py
`num_logits_to_keep` is deprecated.
=> 🏰 `num_logits_to_keep` to `logits_to_keep`

trl/trainer/grpo_trainer.py
Since we're rolling out the same prompt several times, this is a quick win.
https://docs.vllm.ai/en/v0.6.4/automatic_prefix_caching/apc.html 
@qgallouedec @kashif 
=> 🔂 Use vLLM prefix caching for speedup

trl/trainer/reward_config.py
Please let me know if any further rectification is required and I will make the necessary changes.
Fixes #2488
@qgallouedec
=> 📖 Clarification max len in Reward documentation

README.md
=> ➖ Fix GRPO example in README

trl/trainer/grpo_config.py, trl/trainer/grpo_trainer.py
=> 🙌 Share vLLM device with training when only 1 available

tests/test_callbacks.py, tests/test_dpo_trainer.py
=> 👴 Update `tokenizer` parameter to `processing_class` in tests

trl/data_utils.py, trl/trainer/grpo_trainer.py
=> 🥾  Allow bootstrap GRPO

trl/models/utils.py, trl/trainer/dpo_trainer.py, trl/trainer/sft_trainer.py
=> ⚰️ Remove deprecated

.github/workflows/pr_style_bot.yml
=> 🤖 Style bot

.pre-commit-config.yaml, examples/scripts/evals/judge_tldr.py, scripts/log_reports.py, tests/test_data_collator_completion_only.py, trl/environment/base_environment.py, trl/models/modeling_base.py, trl/trainer/ppo_trainer.py
=> 🧼 Upgrade ruff

trl/trainer/sft_trainer.py
=> ♻️ Fix caching in SFT

trl/trainer/grpo_config.py, trl/trainer/grpo_trainer.py, trl/trainer/utils.py
- Update `GRPOConfig` to replace `log_completions` with `log_completions_steps`
- Add `print_prompt_completions_sample()` utility function for rich console logging
- Modify `GRPOTrainer` to additionally print 5 random prompt-completion pairs every log_completions_steps steps
Fixes #2948 
=> 📇 GRPO: print completions to console and update docs

docs/source/grpo_trainer.md
=> 🔢 Fix GRPO doc about `num_iterations`

trl/trainer/model_config.py, trl/trainer/utils.py
This simple pull request integrates DoRA support into trl by adding the use_dora parameter to the ModelConfig and LoraConfig. Given that DoRA has already been extensively tested and optimized with the HF PEFT framework, further testing is unnecessary.
=> 👧🏽 Adding DoRA support to model config

docs/source/_toctree.yml, docs/source/distributing_training.md
This is just a first step. There are plenty of things to add of course, but we can do it iteratively
=> 🕸 Add distributing training guide

tests/test_bco_trainer.py, tests/test_cpo_trainer.py, tests/test_dpo_trainer.py, tests/test_kto_trainer.py, tests/test_orpo_trainer.py, trl/trainer/bco_trainer.py, trl/trainer/cpo_trainer.py, trl/trainer/dpo_trainer.py, trl/trainer/kto_trainer.py, trl/trainer/orpo_trainer.py
=> 🌌 Fix logits computation in trainer prediction step

docs/source/_toctree.yml, docs/source/others.md, trl/extras/profiling.py, trl/trainer/grpo_trainer.py
- Adds a more fine-grained profiling context
- Adds profiling contexts around vllm.generate and each reward function
=> 🪪 Adds a more fine-grained profiling context

trl/trainer/grpo_trainer.py
Just reading the code and fix typo.
=> 🧬 Fix typo in grpo_trainer.py

docs/source/kto_trainer.md
=> 📑 Fix logged metrics for KTO

trl/trainer/grpo_config.py
=> 🔍 Update GRPO config documentation for beta parameter stability

docs/source/customization.md, docs/source/deepspeed_integration.md
=> 🚀 DeepSpeed integration documentation

trl/trainer/sft_trainer.py
=> 🪙 [SFT] Log `num_tokens` and some logging fixes

.github/codeql/custom-queries.qls, .github/workflows/codeQL.yml
=> Improve ci

trl/trainer/sft_trainer.py
remove double compute of sum (sft_trainer.py) (optimize finetuning)
=> ✌️Remove double compute of sum in SFTTrainer

docs/source/customization.md, docs/source/distributing_training.md
Check https://moon-ci-docs.huggingface.co/docs/trl/pr_2991/en/distributing_training
=> 📚 Update customization and distributing training documentation

trl/trainer/grpo_trainer.py
Fixes normalization in the mean KL divergence for logging to match the global normalization of the per-token losses. 
Fixes #2995  (partial; [see comment](https://github.com/huggingface/trl/issues/2995#issuecomment-2695599136)).
=> 🌍 Use global normalization for KL logging (to match normalization for loss)

trl/trainer/grpo_trainer.py
=> 👯 [GRPO] Relax the assumption that prompts are unique within a batch

trl/trainer/grpo_trainer.py
set the `text` argument for the processing class as the Gemma3 processing class has `images` in the first arguments
=> [GRPO] use argument names with processing_class

examples/scripts/sft_gemma3.py, trl/scripts/sft.py, trl/trainer/sft_config.py, trl/trainer/sft_trainer.py
=> 💎 Gemma 3 SFT example on Codeforces dataset

docs/source/reducing_memory_usage.md
=> ☎️ Documentation for disable gathering of model weights for generation in DeepSpeed ZeRO-3

tests/test_grpo_trainer.py, trl/trainer/grpo_config.py, trl/trainer/grpo_trainer.py
=> ⚖️ Add option not to scale rewards (Dr. GRPO)

trl/trainer/cpo_trainer.py, trl/trainer/orpo_trainer.py
=> Fix: Multi gpu hang for ORPO and CPO Trainer

tests/test_utils.py, trl/trainer/grpo_trainer.py, trl/trainer/utils.py
=> 💰 Richer rich table - log all the rewards

tests/test_online_dpo_trainer.py, trl/trainer/online_dpo_config.py, trl/trainer/online_dpo_trainer.py
For:
https://github.com/huggingface/trl/pull/3174
=> ❤️‍🩹 [CI] fix transformers dev CI failure

.github/workflows/trufflehog.yml
See internal Slack thread: https://huggingface.slack.com/archives/C01TETY5V8S/p1739874785157679
Fixes the CI, adapted from TGI workflow: https://github.com/huggingface/text-generation-inference/blob/014255009651cd3233c6c9fc0e5e3c8a3df9ff89/.github/workflows/trufflehog.yaml#L18
=> 🐗 [CI] Fix trufflehog false positives

trl/extras/vllm_client.py
=> 🗝️ Fix type hint in vLLM client

.pre-commit-config.yaml, pyproject.toml, trl/data_utils.py, trl/extras/profiling.py, trl/scripts/utils.py, trl/scripts/vllm_serve.py, trl/trainer/callbacks.py, trl/trainer/grpo_trainer.py, trl/trainer/sft_trainer.py
Update ruff and apply its fixes.
=> Update ruff to 11.3 and base Python version to 3.9

.github/PULL_REQUEST_TEMPLATE.md
=> ☑ Update PULL_REQUEST_TEMPLATE.md

docs/source/sft_trainer.md, docs/source/using_llama_models.md, trl/trainer/utils.py
=> 🗑️ Deprecate `ConstantLengthDataset`

trl/trainer/sft_trainer.py
=> 💠 Fix multi-gpu padding free

setup.py, trl/scripts/vllm_serve.py
Fixes https://github.com/huggingface/trl/issues/3142, https://github.com/huggingface/trl/issues/3157#issuecomment-2751994102. Support vLLM V1 Engine for faster generation.
=> ⏱️ Fix vLLM server to support V1 Engine

examples/scripts/sft_vlm_gemma3.py
Modified the output_dir so it matches the actual dataset.
@qgallouedec
=> 🏷️ Fixed naming error in output_dir for Gemma 3 VLM script

trl/trainer/sft_trainer.py
Fixes typo in `SFTTrainer` doc string
=> 🅾️ Fixes typo in SFTTrainer

docs/source/text_environments.md
=> Fix typo in text_environments.md

docs/source/sft_trainer.md
"x" may mean don't use flash_attn, so i recommend "✓"
=> ✅ [doc] Update sft_trainer.md in table x->✓

trl/trainer/cpo_trainer.py
Fixes #3339 
As mentioned in the issue I'm not sure this is necessary, the docs are pretty clear already but I guess it doesn't hurt?
=> [CPO] Check that `max_prompt_length < max_length`

trl/trainer/dpo_trainer.py
This PR fixes two things:
- Incorrect input for liger:  The input_ids, attention_mask and loss_mask were being created differently in the liger and regular implementations. This PR fixes that in the `_compute_loss_liger` method.
- Incorrect handling of loss_mask: This PR correctly masks the labels with the `ignore_index` to make sure that liger is correctly ignoring the tokens that are not required for loss calculation.
- Changes `all_logps = per_token_logps.sum(-1)` to `all_logps = per_token_logps[:,1:].sum(-1)`. This ensures that the metrics are same for liger and non-liger case. **NOTE: This is just for metrics and can be removed.** 
The changes were tested on a single GPU setup.
```
from trl.trainer.dpo_trainer import DPOTrainer
from …
```
=> Fix liger loss mask and input for liger

.github/workflows/tests_latest.yml, CITATION.cff, setup.py, trl/__init__.py
=> Release: v0.17

docs/source/vllm_integration.md, trl/trainer/sft_config.py, trl/trainer/sft_trainer.py
This PR is following the #3362 to give the freedom for user to be able to `pad_to_multiple_of`.  It is tested using simple following script:
```python
from trl import SFTTrainer, SFTConfig
dataset = load_dataset("roneneldan/TinyStories", split="train[:1%]") 
config = SFTConfig(
output_dir="sft_pad_multiple_of_2",
max_steps=10, 
pad_to_multiple_of=4,
logging_steps=1,
report_to=[],
)
if __name__ == "__main__":
trainer = SFTTrainer(
model="Qwen/Qwen2-0.5B-Instruct",
args=config)
```
=> 🥸🔢 Adding pad_multiple to SFT trainer

tests/test_trainers_args.py, trl/trainer/dpo_trainer.py, trl/trainer/grpo_config.py, trl/trainer/grpo_trainer.py, trl/trainer/sft_config.py
=> ⚰️  Remove deprecated

docs/source/vllm_integration.md
=> 📝 vLLM-integration documentation

trl/scripts/vllm_serve.py
=> 🏹 Support kv_cache_dtype to quantize kv-cache in vllm

trl/trainer/ppo_trainer.py, trl/trainer/rloo_trainer.py
=> use device agnostic empty_cache in ppo & rloo

docs/source/_toctree.yml, docs/source/rewards.md, tests/test_rewards.py, trl/rewards/__init__.py, trl/rewards/format_rewards.py, trl/scripts/grpo.py
This PR creates a sub-module dedicated to reward functions.
Please note that this PR is not intended to integrate _all_ reward functions; this may be done in the future. Its purpose is simply to create a structure for future additions.
=> 🎁 Reward submodule

tests/test_nash_md_trainer.py, tests/test_xpo_trainer.py, trl/trainer/nash_md_trainer.py, trl/trainer/xpo_trainer.py
=> [NashMD] fix the edge case where the model is a peft model

trl/trainer/bco_trainer.py, trl/trainer/grpo_trainer.py, trl/trainer/kto_trainer.py
=> [CI] fix sampler api to make the CI green

docs/source/logging.md
Sync the logging docs to the current logs and add GRPO section.
Fixes #3437
=> [Docs] sync logging doc to current metrics

examples/scripts/gkd.py
The gkd trainer will apply the chat template so need for it in the script itself.
=> [GKD] fix the gkd script

docs/source/grpo_trainer.md, setup.cfg, tests/test_utils.py, trl/trainer/grpo_trainer.py, trl/trainer/utils.py
This PR implements:
- Logging of advantages in the wandb table
- Logging the fraction of samples which have a reward std of zero.
=> 🔭 [GRPO] Log advantages and fraction of samples with an std of zero

.github/workflows/tests_latest.yml, CITATION.cff, setup.cfg, trl/__init__.py
=> Release: v0.18

docs/source/index.md
=> Add "🐯 Liger GRPO meets TRL"

trl/trainer/bco_trainer.py, trl/trainer/cpo_trainer.py, trl/trainer/dpo_trainer.py, trl/trainer/kto_trainer.py, trl/trainer/orpo_trainer.py
`TrainingArguments` always contain `gradient_checkpointing`
=> 🎯 Don't use `getattr` to get `gradient_checkpointing`

scripts/generate_tiny_models.py, tests/test_data_utils.py
The CI is expected to fail, https://github.com/huggingface/trl/pull/3522 is supposed to fix it
=> 🐳 Add DeepseekV3 model configurations and update tests for new models

trl/trainer/utils.py
Fixes some type hints in `trainer/utils.py`
=> 💡 Fix type hints in trainer/utils.py

trl/trainer/sft_trainer.py
Fix #3583 . The type hint problem of formatting_func argument in SFTTrainer. 
=> 💡 Fix wrong type hint for formatting_func argument in SFTTrainer

trl/trainer/grpo_trainer.py
You can't use `trl vllm-serve ..` if you are working on custom models. They need `trust_remote_code` and it's missing as an argument. 
=> 🛡️ Adding trust_remote_code to vllm-serve

tests/test_data_utils.py, trl/data_utils.py, trl/trainer/sft_trainer.py
=> 🦘 Skip no-op ChatML conversion for datasets already in ChatML format

trl/trainer/grpo_trainer.py
The PR makes the `GRPOTrainer` more modular by creating a separate function to calculate rewards `_calculate_rewards`. This should facilitate subclassing the `GRPOTrainer` class such that reward execution can be changed independent of `_generate_and_score_completions`.
=> 🎁 Put the reward computation in a separate function

tests/test_sft_trainer.py
=> 🔍 Add test to verify chat template consistency

examples/accelerate_configs/single_gpu.yaml
=> fixing num_processes

docs/source/grpo_trainer.md
=> env var for vllm colocate exp added

trl/scripts/grpo.py
We should pass the list of functions to the Trainer, and not just the reward model (that is actually None most of the time)
=> ☕️ GRPO script reward_funcs error

trl/trainer/grpo_config.py
fix docs error mentioned in [issue-3653](https://github.com/huggingface/trl/issues/3653)
previous commit is [here](https://github.com/huggingface/trl/commit/cf5183db7fa0e41b3739538e5eba8aaa4541c965)
=> Update steps_per_generation default description grpo_config.py

trl/trainer/sft_trainer.py
Fixes #3641 (issue)
to it if that's the case. #3641 
=> fix: support dict access in SFT Trainer

docs/source/sft_trainer.md, trl/scripts/vllm_serve.py, trl/trainer/grpo_trainer.py
We now check if flash_attn is installed and if not use the `sdpa_paged` in the transformers paged attention slow test
=> [CI] Fix slow grpo CI

trl/trainer/online_dpo_trainer.py
=> [Online DPO] Safeguard logit slice against empty prompt

docs/source/online_dpo_trainer.md, examples/scripts/dpo_vlm.py, trl/scripts/kto.py
Because it's now default.
Late review for #3629
=> 👋 Remove `--bf16` flag from training scripts

.github/workflows/tests.yml, requirements.txt, setup.cfg, tests/slow/test_grpo_slow.py, trl/trainer/grpo_config.py, trl/trainer/grpo_trainer.py
Padding side was wrong, this PR is a fix
A few cleanup, late review for #3471
cc @ArthurZucker for viz
=> ↔️ Fix CB in GRPO

trl/trainer/prm_config.py, trl/trainer/reward_config.py, trl/trainer/sft_config.py
Ref: https://github.com/huggingface/transformers/pull/39395
=> Add comment for `average_tokens_across_devices`

tests/test_online_dpo_trainer.py, trl/trainer/online_dpo_config.py, trl/trainer/online_dpo_trainer.py
Support initializing onlinedpo via model_id str
Fixes #3759
=> 🔠 Support model str in OnlineDPO

docs/source/logging.md
Minor addition to docs.
This was supposed to be apart of #3700.
=> 🤓 [GRPO] Documentation for entropy metric

docs/source/sft_trainer.md, docs/source/training_vlm_sft.md, examples/scripts/sft_vlm.py, examples/scripts/sft_vlm_gemma3.py, examples/scripts/sft_vlm_smol_vlm.py, tests/test_modeling_value_head.py, tests/test_sft_trainer.py, trl/models/modeling_base.py
=> 📐 Fix CI and `GeometricMixtureWrapper`

tests/test_sft_trainer.py, trl/trainer/sft_trainer.py
=> 🍿 [SFT] Fix dataset indexing which crashed with a IterableDataset 

tests/test_sft_trainer.py, trl/trainer/sft_trainer.py
=> 📍 Support training peft model with gradient checkpointing

.github/workflows/tests_latest.yml, CITATION.cff, setup.cfg, trl/__init__.py
=> Release: v0.20

trl/trainer/grpo_config.py
Sorry, I did not review the code carefully in the last submission. I updated my submission(origin: #3796). Thanks.
https://github.com/huggingface/trl/blob/9269f9f151881ab6476035adc0f409a1b6a0ab4e/trl/trainer/grpo_config.py#L205-L206
https://github.com/huggingface/trl/blob/9269f9f151881ab6476035adc0f409a1b6a0ab4e/trl/trainer/grpo_config.py#L544
@qgallouedec 
=> Correction parameter description

docs/source/index.md
=> 🔗 Fix collection link in doc

README.md
=> Small style fix in README

tests/test_dpo_trainer.py, tests/test_grpo_trainer.py, tests/test_sft_trainer.py, trl/models/__init__.py, trl/models/utils.py, trl/trainer/grpo_trainer.py, trl/trainer/online_dpo_trainer.py, trl/trainer/ppo_trainer.py, trl/trainer/prm_trainer.py, trl/trainer/reward_trainer.py, trl/trainer/sft_trainer.py
=> ✨ Integrate PEFT model preparation across trainers and utilities

docs/source/index.md
=> 👁️ VLM blog

trl/trainer/grpo_config.py
During GRPO training, extend validation of generation_batch_size and steps_per_generation 
previously applied only to the train batch size to the eval batch size as well. 
Remove logic that considers steps_per_generation when self.steps_per_generation is None.
=> ☑️  Check eval batch size in grpo

trl/trainer/callbacks.py
=> 📚 Update BEMACallback documentation to ignore docstyle and fix lag parameter description

docs/source/sft_trainer.md, trl/trainer/sft_trainer.py
=> 🎆 Add entropy logging in SFT

tests/test_sft_trainer.py, trl/trainer/sft_trainer.py
=> 🤸 [SFT] Drop entropy calculation when using liger

docs/source/paper_index.md
Lite PPO should use `batch` as the value of `scale_rewards`
=> 🪶 LitePPO: Fix Docs for paper index

docs/source/unsloth_integration.md
Updating Unsloth integration for TRL.
Feel free to make any further adjustments as necessary!
As requested, we've updated the documentation for [Unsloth](https://github.com/unslothai/unsloth) integration via TRL.
=> 🦥 Unsloth Docs update

docs/source/jobs_training.md, trl/trainer/alignprop_trainer.py, trl/trainer/bco_trainer.py, trl/trainer/cpo_trainer.py, trl/trainer/ddpo_trainer.py, trl/trainer/dpo_trainer.py, trl/trainer/gkd_trainer.py, trl/trainer/grpo_trainer.py, trl/trainer/iterative_sft_trainer.py, trl/trainer/kto_trainer.py, trl/trainer/nash_md_trainer.py, trl/trainer/online_dpo_trainer.py, trl/trainer/orpo_trainer.py, trl/trainer/ppo_trainer.py, trl/trainer/prm_trainer.py, trl/trainer/reward_trainer.py, trl/trainer/rloo_trainer.py, trl/trainer/sft_trainer.py, trl/trainer/xpo_trainer.py
Adds new tag `generated_with_hf_jobs` when the model is created via [HF jobs](https://huggingface.co/docs/huggingface_hub/guides/jobs)
@lewtun @qgallouedec
=> Add HF jobs tag when creating model card via jobs

tests/test_modeling_geometric_mixture_wrapper.py, tests/test_modeling_value_head.py, tests/test_utils.py, trl/trainer/dpo_trainer.py, trl/trainer/gkd_trainer.py, trl/trainer/kto_trainer.py
Updated model initialization and input tensors to use the appropriate device (CPU or CUDA) to fix CI failures
=> [CI] Modify tests to handle device allocation for models

trl/trainer/dpo_trainer.py, trl/trainer/online_dpo_trainer.py
`AutoVision2Seq` --> `AutoModelForImageTextToText`
=> Update VLM arch check to `AutoModelForImageTextToText` for DPO and Online DPO

docs/source/jobs_training.md
=> Reviewed HF jobs updated docs

docs/source/community_tutorials.md
=> Community Tutorials design adaptation for videos

scripts/generate_zen_dataset.py, tests/test_sft_trainer.py, trl/trainer/ppo_trainer.py
Fix code style with `make precommit`.
=> Fix code style with make precommit

trl/data_utils.py, trl/trainer/sft_trainer.py
This PR improves typing of SFT trainer
=> Improve typing of SFT trainer

tests/test_grpo_trainer.py
=> Fix import statement and GRPO test case

trl/experimental/grpo_with_replay_buffer/grpo_with_replay_buffer_trainer.py
#4111 for GRPO with replay buffer
=> 🟩 Drop `image_split_sizes` in favour of `image_grid_thw`

tests/test_bco_trainer.py, tests/test_kto_trainer.py
We forgot some in https://github.com/huggingface/trl/pull/2349 and https://github.com/huggingface/trl/pull/2828
=> 🔣 Fix test: replace `trainer.tokenizer` by `trainer.processing_class`

docs/source/lora_without_regret.md
lr is wrong way round in table:
- full ft is 1.0e-6
- best lora is 1.0e-5
=> [DOCS/FIX] lora without regrets - fix lr

examples/scripts/dpo_vlm.py, examples/scripts/grpo_vlm.py, examples/scripts/gspo_vlm.py, examples/scripts/mpo_vlm.py, examples/scripts/reward_modeling.py, examples/scripts/rloo_vlm.py, examples/scripts/sft_gpt_oss.py, examples/scripts/sft_video_llm.py, examples/scripts/sft_vlm.py, examples/scripts/sft_vlm_gemma3.py, trl/scripts/dpo.py
Removing tokenizer/processor creation from example scripts when possible. The idea comes from [this comment](https://github.com/huggingface/trl/pull/4197#issuecomment-3369715750) 
In some trainers, it's still needed to pass directly the tokenizer/processor so they're not updated here.
=> Removed tokenizer/processor creation from example scripts
